### ISSUE TITLE
Request: Add Option to show line numbers

### ISSUE THREAD

**Issue by nonplayer** [wereturtle/ghostwriter#100]
Maybe this is already a feature but I can't for the life of me find it. Being able to quickly scan a doc for line numbers would be a blessing when working with larger documents.

**Comment by tmr232** [comment]
This would also be great when narrow settings make lines overflow. Currently there is no way to discern an overflown line from a regular line.

**Comment by wereturtle** [comment]
Sorry, but I feel that feature is out of scope for the tool.  It's supposed to straddle the line between text editor and word processor--and word processors don't typically display line numbers.

**Comment by nonplayer** [comment]
That's really unfortunate. It's a solid feature, found in all other Markdown editors I've tried including Smartdown, Remarkable, Markdownpad, Haroopad, as well as both Atom and Notepad++ (with Markdown extensions). They're even available when editing Markdown directly in Bitbucket and Github. Both Libreoffice and Word have options for them, too, if you're only looking at Word Processor apps, and there are plugins for doing the same in Google Docs.

I respect that you might not want them personally, but if the reasoning is that Word Processors typically don't display them, that's not really accurate anymore today.

**Comment by nonplayer** [comment]
In fact, the only editor I've used that doesn't have this feature - text or processor alike - is MacDown, and it could even simply be because I'm just not mac-savvy enough to figure that one out.

**Comment by wereturtle** [comment]
I'm truly sorry, but I honestly don't have the time or energy to put such a feature into the tool.  I have a job, and other interests.  As such, I tend to stick to implementing features that are low hanging fruit or that would be useful to me as well.  Even if I did agree to implement this feature, you will be waiting a good year to see it anyway, since I'm about to take a long break from further development after 1.4.0 is released.  (I will be available to contribute bug fixes, however.)

You are welcome to contribute this feature via a pull request.  This is in part why I open-sourced the tool--so that the community can contribute to make it better.  If you decide to do so, please make sure that you test your implementation against large documents (100,000 - 200,000 words) to ensure that performance doesn't become sluggish while typing.  Also, please keep both theming aesthetics and right-to-left languages in mind as you code.

I'll reopen the issue and put a "help wanted" tag on it, in case anyone else wants to help implement this feature.

**Comment by nonplayer** [comment]
Totally understandable!

I'll try and take a crack at it =)

**Comment by houserockr** [comment]
I'm absolutely with @wereturtle here. It's a markdown editor, not a regular/enhanced text editor. The tools you mentioned above (atom, notepad++, et al.) all aim to be source code editors; or let's say editors for "enhanced" tasks. IMHO ghostwriter is more like "i.A. Writer" for OSX. These editors focus on minimalism and simplicity.

**Comment by wereturtle** [comment]
Well, @houserockr, apparently Ulysses III does have an option to show line numbers, at least as far as I can tell based on screenshots.  It's just that Qt makes that feature rather difficult to do.  You have to paint the line numbers yourself and line them up with the wrapped text perfectly.  Ugh.  And as you said, I do like ghostwriter being more like "i.A. Writer".  It's how ghostwriter began for me.  I saw that OSX had all the pretty Markdown editors and wanted to make one for Linux and Windows.  I honestly also use Sublime text for some documents, depending on the need.  Sometimes it's better to have different tools for different purposes, than to try to make one tool that does everything and loses its focus.

**Comment by nonplayer** [comment]
Just update that I've not been able to add anything worthwhile. I don't know qt as well as I would like and like @wereturtle don't have the spare time to commit to it - that time is spent editing massive markdown docs instead. =)

But contrary to @houserockr who only commented on two of the apps I mentioned for some reason (_all_ of the others are single-focus markdown editors), I think it'd be a great tool for line editing. Markdown is an awesome format, and when working with multi-thousand line files having the ability to look for line numbers after a questionable git conflict is quite useful. I'm still having to use Notepad++ for that one singular feature.

**Comment by wereturtle** [comment]
OK, thanks for the feedback, @nonplayer.  I think I'll close this issue for now, since nobody has time to work on it.  I can always reopen it if somebody becomes interested.
