### ISSUE TITLE
Add theme option to change line spacing

### ISSUE THREAD

**Issue by tmr232** [wereturtle/ghostwriter#103]
In some cases I find the line spacing a bit small. Being able to configure it for a specific theme would be wonderful.

**Comment by wereturtle** [comment]
Sadly, it turns out that QPlainTextEdit does nothing when setting the block formatting to change line height or even margins between paragraphs.  Since switching to QTextEdit will cause a performance hit with the syntax highlighting on large files, I'm afraid I won't be able to implement this feature in the near future (if at all).
