### ISSUE TITLE
Several feature requests

### ISSUE THREAD

**Issue by jeff9315** [wereturtle/ghostwriter#110]
FIrst, I REALLY like Ghostwriter. I've been searching for a Markdown tool that has support for several things and so far Ghostwriter seems to come the closest. However, there are still a few things that I hope fit into your ability to support Ghostwriter, knowing it's not your full-time job :-)

* a keystroke to Insert the current date
* Multiple documents open in a tabbed interface
* A `*` at the beginning of the line (only white space preceding it) or an `'` immediately after a letter or number should NOT be paired with it's opposite
* Need an option to "clean up" bullets and numbers to make them consistent and correctly numbered ... which probably means having a preferred bullet style (which includes whether cycling should be performed)
* Search & Replace -- an option to only perform it on the selected text

Thanks ... Jeff

**Comment by odhondt** [comment]
I recently started using ghostwriter and find it excellent. I use it a lot for journaling,
therefore a keystroke to insert the current date would be really useful to me. Another great thing would be the ability to render LaTeX math in the preview.

**Comment by wereturtle** [comment]
Hi @odhondt ,

Pandoc and MultiMarkdown support MathJax.  I have an example for each in issue #81 that will help you get started.  (Someday I hope to add being able to put in custom JavaScript snippets into the preview without having to put it in your Markdown document, but I should really port from WebKit to the new Chromium-based browser in Qt before I start that.)

**Comment by wereturtle** [comment]
I've taken some time to consider the list of feature requests you've given me.  Here are my responses to each:

    * a keystroke to Insert the current date

Considering all the date/time formats there are, which one should be inserted?  I could make it configurable, but then there's locale/languages to consider as well.  Due to its complexity, I'm inclined to say no to this one, at least for the time being.  Perhaps in the distant future I'll implement a plugin API so that people can insert their own snippets.  But that's a long ways away.  However, I am open to suggestions if you have a simple way to go about it that will make everyone happy (including for multiple languages).

    * Multiple documents open in a tabbed interface

I'd prefer not to.  If I implement that, then another person will ask for a split view, and so on, and before you know it, I've cloned Sublime Text.  I'd rather stick to the original goal of having a clean sheet of paper to write on, distraction-free.

    * A `*` at the beginning of the line (only white space preceding it) or an `'` immediately after a letter or number should NOT be paired with it's opposite

I'll be sure to address that as part of issue #114.

    * Need an option to "clean up" bullets and numbers to make them consistent and correctly numbered ... which probably means having a preferred bullet style (which includes whether cycling should be performed)

I think this is a good idea.  Can you suggest an algorithm for this?  Or do you know of another open-source project that has code that does something like this really well?  It would save me a lot of time implementing the feature.

    * Search & Replace -- an option to only perform it on the selected text

I've added issue #136 for this.

**Comment by wereturtle** [comment]
Closing due to lack of response.
