### ISSUE TITLE
Borderless

### ISSUE THREAD

**Issue by gbo42** [wereturtle/ghostwriter#111]
First of all, GREAT JOB! 
I was wondering if theres a way to make ghostwriter run without borders, to increase the "cleanness" of the design.
I know it's not actually an issue, but I don't found anywhere better to ask this, so if you can consider my humble opinion, it would be great, thank.

**Comment by wereturtle** [comment]
Well, there is a way--the same way I made the HUD windows, which is to tell the OS, "No thanks, I'll draw my own window frame".  The problem is that I would have to implement all the close, minimize, and maximize buttons, as well as other features that go with the frame.

But the good news is, your OS can likely do all this for you.  This depends which OS you are running, of course.  I'm running Linux, where I can have all sorts of themes for my desktop environments that have thin or no borders.  In Windows, you can somewhat tweak this.  In Windows 7, for example, there is the Personalization/Window Color/Advanced appearance settings.  Here, you can set the Border Padding all the way down to zero.  This will give you a very thin border for all your windows.

**Comment by gbo42** [comment]
Hey, thank you very much for the nice response. I'm using Linux too (but a mere beginner user). I will search for themes and learn how tweak the appearance of my windows. Thank you again and keep the good job!

**Comment by wereturtle** [comment]
You're welcome.  And welcome to the wonderful world of Linux!  :)
