### ISSUE TITLE
International time format?

### ISSUE THREAD

**Issue by DeFabro** [wereturtle/ghostwriter#113]
I liked the time display in full screen mode, but the time format is confusing. What do you think about to use 24-hour clock notation (00:00–23:59) by default? This system is the most commonly used time notation in the world today.

Anyway, there is a bug in the current time format.
This is the time format in Linux (Tested in Ubuntu 16.04) — 1.13 PM
The same time in Windows — 1.13

**Comment by wereturtle** [comment]
Hi @DeFabro ,

I'm seeing the "PM" correctly in the time on my Windows installation, so I'm not sure what is causing you to see something different.

However, I did read up on the Qt documentation, and it appears that there is a locale-specific routine that the code should be calling to get a locale-formatted time.  (Of course, it isn't calling that, but something else instead.)  I will fix it to use the locale-specific string format call.  You will then see something more appropriate to your locale, which will probably be a 24-hour format.  (I don't want to deliberately force the clock format to "military time", since many civilians in my own locale don't know how to read it.)

The fix will be in a new release (version 1.4.2) no later than this weekend.
