### ISSUE TITLE
Auto-scroll that shows some of the preceding content in HTML preview

### ISSUE THREAD

**Issue by alajovic** [wereturtle/ghostwriter#122]
The HTML preview window conveniently scrolls to the current editing point on every refresh; I like that. However, I would prefer it to scroll to just a bit _above_ the beginning of the current section so that I could see the content that comes before it.

For example, when editing the first paragraph of a section, the scrolling mechanism hides the section name and I find that confusing.

Another case is when I'm editing a short paragraph at the end of a section and the auto-scrolling adjusts the view so that this short paragraph is right at the top of the screen. The reason I find this mildly annoying is that in my perception, the paragraph contextually belongs to the content _above_ it (which I don't get to see at all) rather than the content _below_ it (which I get to see copious amounts of).

I'm looking at the source in `HtmlPreview.cpp` and I see the point where the scrolling is done (currently at line 613):

```
htmlBrowser->page()->mainFrame()->scrollToAnchor("livepreviewmodifypoint");
```

As a test, I tried inserting the following call just below that:

```
htmlBrowser->page()->mainFrame()->scroll(0, -100);
```

With this, I kind-of get the behaviour that I want. Of course, I used a fixed amount (100 pixels), but that was intended just as a proof of concept. In an actual implementation, it would be wiser to use a configurable amount, or – perhaps even better – an amount proportional to the height of the HTML preview frame.

The feature seems almost trivial to implement and I would gladly contribute a patch, but I would first like to hear your thoughts on it.

cheers, 
andrej

**Comment by wereturtle** [comment]
Sure, that sounds like a great idea!  Thanks for figuring that out!

What do you think about putting the desired previewed text position in the vertical center of the browser?  Perhaps by taking half the height of the window and scrolling there?  Something like this:

    htmlBrowser->page()->mainFrame()->scroll(0, -(height / 2));

Or would that be too far for the user to be able to find the edit point?

**Comment by alajovic** [comment]
Actually, my initial idea was to vertically center the current editing point. :-) I have now implemented it and it turns out that it functions quite well. Jumps from one part of the document to another part might be slightly disorienting, but not more than they were before. When editing the content around the centered point, it is actually very easy to follow.

Implementing this was just a bit more work than I thought, because I needed to improve the way the positioning of the autoscroll anchor is done. Previously, the old and the new HTML codes were compared line-by-line and the anchor was inserted at the beginning of the first line that differed. Therefore the target of the autoscrolling was always at the beginning of a paragraph. This could have been quite annoying with *very* long paragraphs (longer than the preview window) because ghostwriter would keep scrolling to the top of it. Luckily, my paragraphs were never that long. :-P

I have replaced this algorithm with one that compares the HTML codes character-by-character and inserts the anchor just before the first difference. This way, the autoscrolling is much more precise. And, interestingly enough, it actually takes *less* code to do it.

I have pushed the commit to my repository, branch [vertical-centering]. Feel free to comment.
[vertical-centering]: https://github.com/alajovic/ghostwriter/tree/vertical-centering

**Comment by wereturtle** [comment]
Thanks for the code!

I'm afraid, however, that I finally remembered why it is I set the anchor to be at the beginning of the line rather than where the actual character difference is.

If you make a change, say, inside a link, you'll end up with the anchor inside the URL text changes.  In that case, the HTML preview window will fail to scroll to the edit location.  Also, the link will be messed up.  I'm sure there are other corner cases where putting the anchor right at the edit point will cause the scrolling to fail.

As a compromise for now, I put the code in to scroll to the vertical center.  Otherwise I will be leaving the original line-by-line comparison code intact.

For the long run, I think achieving what we want could be possible if we did a diff against the two DOM trees, so that we can intelligently put in the anchor at the desirable location rather than in the middle of an HTML attribute.  It will be painful to diff two trees, however.  How invested into having this feature are you?  :)

**Comment by alajovic** [comment]
Ah, true, true!

I was concerned that placing the anchor _right at the spot_ could have some adverse effects; I thought about it for a little while, but could not come up with a plausible scenario. Well, apparently the gut feeling was right, after all.

> As a compromise for now, I put the code in to scroll to the vertical center. Otherwise I will be leaving the original line-by-line comparison code intact.

I fear that this might not do well in combination with long paragraphs, because the end of the paragraph will get pushed out of the viewport at the bottom. This, as I said before, could have happened even with the old scrolling behaviour, but the paragraph needed to be twice as long before.

As far as I am concerned, there is no need to hurry. Perhaps we'd rather have another round of thought on this.

> For the long run, I think achieving what we want could be possible if we did a diff against the two DOM trees

Definitely. It would require some more effort, but I believe it's doable. I'll look into it. I don't promise anything, however. ;-)

**Comment by alajovic** [comment]
Hey,

a semi-related question – I was looking at the way you do DOM traversal when setting the `id` attributes on headings, and I'm curious about this snippet (HtmlPreview.cpp, lines 385–397 in current master):

    385    QStack<QWebElement> childStack;
    386    element = element.firstChild();
    387    
    388    while (!element.isNull())
    389    {
    390        childStack.push(element);
    391        element = element.nextSibling();
    392    }
    393    
    394    while (!childStack.isEmpty())
    395    {
    396        elementStack.push(childStack.pop());
    397    }

It seems to me that the sole purpose of the `childStack` is to reverse the order of the children before pushing them onto `elementStack` so that they are later popped in the correct order . If this is so, wouldn't it be simpler to start at element.lastChild(), iterate with element.previousSibling() and push the elements straight to the `elementStack`, avoiding the `childStack` altogether?

**Comment by wereturtle** [comment]
OK, I'll back out the change for the vertical scrolling until we figure out the right solution.

> Definitely. It would require some more effort, but I believe it's doable. I'll look into it. I don't promise anything, however. ;-)

Oh, believe me, I understand!  You can't believe how happy I get when someone wants to chip in even a small thing.

> It seems to me that the sole purpose of the childStack is to reverse the order of the children before pushing them onto elementStack so that they are later popped in the correct order . If this is so, wouldn't it be simpler to start at element.lastChild(), iterate with element.previousSibling() and push the elements straight to the elementStack, avoiding the childStack altogether?

Your idea does sound better (I probably just wasn't paying much attention to the full API at the time).  Feel free to play around with it.  As long as it works.

As a heads up, if you do any new DOM traversal code for the diff, keep in mind issue #78.  One day I'll have to migrate from the old Qt WebKit code to the new Chromium-based API, as the Qt WebKit API has been deprecated.  For now, it's fine, but I'm sure whenever Qt 6 comes out, the old API will be gone entirely.  Unfortunately, the new API doesn't have direct C++ access to the DOM.  That means that working with the DOM has to be done in JavaScript.  Thus, it's probably better that you do your new DOM diff algorithm in JavaScript rather than in C++.  It's one less thing to port later.

**Comment by wereturtle** [comment]
Oh, by the way, please don't use the "auto" keyword.  Not everybody is compiling with C++ 11, so it's causing errors in some environments.  I hope you don't mind.  :)

**Comment by alajovic** [comment]
Thanks for your comments. I'll see what I can do.

About the `auto` keyword – I saw the *-std=gnu++0x* flag when compiling and thought it was explicitly set in the project file. Sorry. It must have come from somewhere else, then.
