### ISSUE TITLE
Can't install from provided source tarball

### ISSUE THREAD

**Issue by andy-twosticks** [wereturtle/ghostwriter#131]
```
andy@jenna[~/scratch/ghostwriter-1.4.2]%: qmake                             
fatal: Not a git repository (or any parent up to mount point /home)         
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).  
```

Of course the workaround is trivial -- delete the tarball and start again with `git clone` -- but I thought you should know.  The tarball is right there on your download page...

**Comment by wereturtle** [comment]
Thanks for reporting this.

I've been trying to find a workaround for that for a while.  The issue is in the ghostwriter.pro file.  I try to load a commit version from git into the VERSION variable.  This gives me a pretty number for development work incremental from the last tagged version.  Unfortunately, the $$system call to fire up git simply exits the qmake program when the git repo isn't there, as opposed to politely returning a blank string or non-zero exit code .  Very frustrating.

You wouldn't happen to know a workaround for this?  Or even a better automatic alpha/beta/nightly-build versioning system that doesn't require calling git from the qmake project file?

**Comment by andy-twosticks** [comment]
I'm afraid I'm just a humble Ruby programmer and don't know much about c++.

I take it you can't shell out to call something like `git re-parse --show-prefix` and check the exit status? Probably a stupid thing to say, sorry...

**Comment by houserockr** [comment]
You could rewrite the git command as follows:
```
# Set program version 
VERSION = $$system(git describe --tags 2>/dev/null || echo "")
isEmpty(VERSION) {
    VERSION = v1.4.1
}
message($${VERSION})
```
So if the git command fails, $$VERSION is empty and gets assigned the default value.

**Comment by wereturtle** [comment]
Hi @houserockr,

Thanks for the tip!  I'll try that out, and see if there is a Windows equivalent.

Yes, I do need help for OSX.  Mainly in testing and fixing any problems that are OSX-specific, and especially in putting together an installer package.  If you could do the latter for the source code on the master branch, I could link to your package in the release notes for the latest release.

Thanks for volunteering!
