### ISSUE TITLE
Ghostwriter vs. Typora

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#150]
Asked out of curiosity and to get your view, how do Ghostwriter and [Typora.io](http://www.typora.io/) compare?

**Comment by brylie** [comment]
One difference I noticed is that Typora does not appear to be open source. They have an issue queue on Github, but the Typora source does not seem to be public.

**Comment by suhr** [comment]
The good thing about ghostwriter is it does **not** hide markdown. Another good things are focus and hemmingway modes.

**Comment by orschiro** [comment]
Thanks, Brylie!

And in terms of functionality and features?

Did you notice any striking differences?

**Comment by orschiro** [comment]
Thank you both!

Maybe we can do something like this:
https://en.wikipedia.org/wiki/User:Orschiro/sandbox

**Comment by Vimux** [comment]
Typora: electron-based application. Why is it so bad? Because at high load, it causes lags and work unstable on my laptop. Memory consumption grows unpredictably. Many processes.

Ghostwriter: based on Qt. Memory consumption grows predictably. One process.

`<offtopic>`
I like ghostwriter more than Typora, but...

**Bad naming**. Just try to googling ghostwriter. Thousands of them. Typora is a unique name.
I found ghostwriter three months ago and I can't remember how I did it.
`</offtopic>`

**Comment by orschiro** [comment]
Great, Vimux, thanks!

I've added software type to the comparison table as well as some other
applications that are comparable:

https://en.wikipedia.org/wiki/User:Orschiro/sandbox

**Comment by wereturtle** [comment]
@orschiro why do you have ghostwriter as "no" for focus mode and live preview?  It does both.

Perhaps I need to make animated gifs to showcase some lesser-known features on the website.

@Vimux that's exactly why I made ghostwriter.  So few other editors could handle large documents smoothly.  Live previews for large documents are agony in most tools.  Typing often freezes.  ghostwriter specializes in novel or dissertation-sized documents.  It's not as fancy in some regards to Typora, but it doesn't slow down, and I can navigate to different sections.  I spent a long time comparing different GUI toolkits, including some HTML/Javascript solutions, before settling on Qt.  Sorry for the bad naming, though.  I'm terrible with names.

**Comment by orschiro** [comment]
You're right. I did a mistake regarding Focus mode. Sorry! I corrected it.

Regarding preview, you mean HTML preview? That for me is not a live
preview.

I added a new column "Manual preview" to the editor. What do you think?

**Comment by wereturtle** [comment]
It does do a live preview.  Put the Preview window side by side with the main window, and start typing.  When you stop typing, it will update the HTML preview automatically.  (I made it so that it only updates the preview when you stop typing so that with large documents it doesn't freeze as you type.)

**Comment by orschiro** [comment]
Oh, wow. This is cool!

I will update the table.

Thanks!

**Comment by JohnBlood** [comment]
@brylie mentioned the Typora is not open source. That fact is very important to me. I used to use MardownPad on Windows (it's Windows only). The problem was that MP had not been updated since the end of last year and I could not get a hold of the of the creator. So, I went looking for an open-source, cross-platform and found Ghostwriter. I'm glad it does not have preview panel because my system was bogging down when I tried to work on a long doc and the real-time preview had to keep up with my changes. 

Overall, great program, @wereturtle

**Comment by orschiro** [comment]
Very useful, thanks, John!

I took down notes of all your remarks in the table. :-)

https://en.wikipedia.org/w/index.php?title=User:Orschiro/sandbox&section=1

**Comment by JohnBlood** [comment]
Don't forget that ghostwriter runs Windows, too.

**Comment by orschiro** [comment]
Good catch, thanks, John!

Updated the table
<https://en.wikipedia.org/w/index.php?title=User:Orschiro/sandbox&section=1>
.
