### ISSUE TITLE
Feature Request: CJK support for PDF exporting

### ISSUE THREAD

**Issue by tonghuix** [wereturtle/ghostwriter#159]
Hi, 

Several Chinese people using this tool, but we cannot export PDF due to the source content CJK characters. Could you please add CJK support for PDF exporting. 

I am working with Pandoc to convert markdown to PDF (CJK included), need some hacking for latex template file.

**Comment by wereturtle** [comment]
Can you provide such a latex template file with an example command line invocation (to show me what you need it to do), as well as some sample Chinese text?  I need to see what it is *supposed* to look like, so that I can ensure that the export is done correctly.

Just to confirm, you are indeed able to use Pandoc from the command line directly (i.e., without ghostwriter), to convert to PDF?

In the meantime, you might be able to workaround the problem by exporting to ODT first, and then using LibreOffice to export from ODT to PDF.

**Comment by tonghuix** [comment]
Here is a example project https://github.com/beijinglug/fsfs-zh template.tex under pdf directory.

I am the founder and maintainer of the project, so if you have any program I would like to answer.

**Comment by wereturtle** [comment]
Hi @tonghuix ,

I've looked into this a bit further, and it appears that you can simply replace your template files in your Pandoc user directory.  See this link [here](http://pandoc.org/MANUAL.html#templates) for more details.  Basically, replace the `default.latex` with your Chinese-friendly one.  This way, Pandoc is fixed for good.  You don't have to specify the template on the command line, and ghostwriter doesn't need to change.

If after trying the above method you find it isn't working, let me know.

**Comment by stockphrase** [comment]
I have a similar interest here. I have several different latex templates for various things: articles, personal letters, business letters, memos, etc. I write in markdown and then use a makefile in order to get Pandoc to run the markdown through the template and output to .pdf. 

The command for this goes something like this:

`pandoc -s --latex-engine=xelatex --template=personalstationary.tex letter.md -o letter.pdf`

It would be fantastic if I could do this directly in Ghostwriter by selecting a template, rather than the ugly Pandoc generic.
