### ISSUE TITLE
Add setting (bool) to remove a backup after close

### ISSUE THREAD

**Issue by joede** [wereturtle/ghostwriter#164]
It would be nice to have a setting to enable the removal of backup files after the original file has been closed.

**Comment by joede** [comment]
@wereturtle Would you except a pull request with an implementation?

**Comment by wereturtle** [comment]
I'd prefer not to have that setting.  Sorry.  The point of backup files, at least for me, is to have a backup around in case something bad happens--especially if it happens during closing!

**Comment by joede** [comment]
I'm using GhostWriter in conjunction with ownCloud "Notes". I have a synced folder with Markdown files. My ownCloud installation keeps track of all versions synced to the server. So I don't need the backup file as permanent safety copy.

>  in case something bad happens--especially if it happens during closing!

That's why I want to remove the backup *after* a *successfully* written file. ;-)

**Comment by wereturtle** [comment]
Yes, but if autosave is enable, when the application is closed, another save operation happens.  If something goes wrong, you might risk having the backup file wiped and your main file corrupted on closing.

Also, since you have version control anyway, you can always turn the backup feature off entirely.  It's in the options under the "Settings" menu.
