### ISSUE TITLE
Find/Replace regex matching newline

### ISSUE THREAD

**Issue by joshg253** [wereturtle/ghostwriter#174]
I can't figure out how to match newline in Find/Replace. I've tried: \n, \N, \r, \R

Example:
I have tons of sections like this copied from various Bandcamp pages:
> Spectres
> by Bast
> 2013
> https://burningworldrecords.bandcamp.com/album/spectres

And I run regex replace in [other text editor] like so:
Find: `^(.+)\Rby (.+)\R(\d\d\d\d)\R(http.+)\R`
Replace: `$2\t$1\t$3\t$4`

Which outputs changes the lines to:
> Bast [TAB] Spectres [TAB] 2013 [TAB] https://burningworldrecords.bandcamp.com/album/spectres

**Comment by wereturtle** [comment]
Believe it or not, Qt uses the backslash character (\\) rather than the dollar sign ($) to signify captured group replacements.

So you're last sample replace string should have `\1`, `\2`, etc rather than `$1`, `$2`, etc.

As for tabs and newlines in the replacement string, specifying characters like `\t` for tab doesn't seem to work.  This is due to a limitation in the QString::replace() method.  It will let you put characters like `\t` into the search string, but the replacement string isn't interpreted in the same way.  I know;  it's not ideal.  But it's what we have to work with.  You can, of course, paste in a real tab character directly.

Newlines don't seem to be recognized in the QRegExp class.  It's just not as powerful as Perl's, I'm afraid.

But, now you have the two class names you need to read documentation on how to do your regular expressions in Qt.  The pages for each are [here](http://doc.qt.io/qt-5/qregexp.html) and [here](http://doc.qt.io/qt-5/qstring.html).

**Comment by joshg253** [comment]
Ok, thanks.
