### ISSUE TITLE
When text clicked on, cursor now barely visible in most themes

### ISSUE THREAD

**Issue by mcfadzgit** [wereturtle/ghostwriter#178]
This problem only occurred a few days (?) ago, and must have been caused by updates to other dependent packages. Am using fully updated 64-bit Arch Linux (eg. with qt5-base 5.8.0-2) and have recompiled with latest Ghostwriter commit (1.4.2.r53.ge3b136f), but same problem evident as older version (v1.4.2.r1.g812199f).

When you click on the text in the editor, the cursor can hardly be seen, unless a very dark theme is used. (Text selection still works okay)

Sorry can't be more specific, but a lot of qt5 packages were updated in the past few days; Ghostwriter was fine before that.

**Comment by wereturtle** [comment]
I tried installing Manjaro testing in VirtualBox, which has Qt 5.8.  I can't get the AUR ghostwriter packages to even build, nor even build it myself.  It appears the qt-webkit package dependencies are missing from the repository and won't even download/install.  Bizarre.  And frustrating.  I'll try again with Antergos when I have more time and keep you posted.

**Comment by burij** [comment]
Same problem here. Arch (Apricity) 64x, Gnome 3.22.2, Intel® Haswell Mobile. If you need pictures or test, just say.

**Comment by wereturtle** [comment]
I've investigated further, and I found to my dismay that as of Qt 5.8, you can no longer set the color of the text cursor in the editor.  Apparently, the color is now determined based on the background color of the editor.  Unfortunately, this causes another issue where the graphics effect for the fading text at the bottom of the editor ends up painting an invisible cursor, because the background color has not yet been determined at that stage.

I've put in a workaround that disables the text fade effect at the bottom of the editor.  It won't be as pretty anymore, and the text cursor color will be chosen by Qt rather than the theme.  However, it will be functional.  The workaround will only be for Qt versions 5.8 and higher.  It is now on the master branch, and I believe the AUR has a package for building ghostwriter against the master, rather than version 1.4.2.  You will want to use that package.  Alternatively, you can compile version 1.4.2 against Qt 4.8, which will allow you to keep all the pretty effects.

In the meantime, I have filed a bug report in the Qt bug tracker, [QTBUG-59093](http://bugreports.qt.io/browse/QTBUG-59093).  If you would kindly chime in there and let the devs know that you have observed this behavior first-hand, we might get some attention to get this fixed.

**Comment by mcfadzgit** [comment]
@wereturtle Thank you for investigating this problem and for quickly implementing a workaround. I've now rebuilt the package from the AUR and editing is a lot easier again!

**Comment by wereturtle** [comment]
Good news!  I found an even better workaround by painting the text cursor myself.  I've likewise merged this fix to the master branch.  Rebuild the AUR package that points to this branch, and you should have the pretty effects back.

I still urge affected users to log into the Qt bug tracker and report what you observed at [QTBUG-59093](http://bugreports.qt.io/browse/QTBUG-59093).  You can also vote for the issue.  By doing so, you will help other affected software applications that rely on being able to set the text cursor color via style sheets.  (Having to paint it manually is not ideal.)
