### ISSUE TITLE
Comments are also counted in word count

### ISSUE THREAD

**Issue by mumeiyamibito** [wereturtle/ghostwriter#183]
I often wrote comment in Markdown window, and the comment line did not display in preview window. 
But, the words in comment line were counted.

I'd like to know the number of words of only preview window.

Would it be possible to change the word counter does not count the words in comment line or display both the number of words with and without the words in comment line in HUD document detail.

**Comment by plgruener** [comment]
What do you mean, HTML comments? As far as I know there is no official "comment" in markdown…

**Comment by jmhibben** [comment]
@plgruener - I think @mumeiyamibito is referring to using `<!-- comment in here -->` for comments.

I find myself wondering how this might be implemented.

**Comment by mumeiyamibito** [comment]
@plgruener Yes, "comment" is HTML comments like "". This markdown was available  when .md convert .md to .docx by pandoc.

@jmhibben It seems that the function can also be used with the shortcut key (Ctrl + /; like sublime text).

**Comment by wereturtle** [comment]
Well, the class that handles the word count doesn't parse the Markdown.  (I designed it to be portable to other non-Markdown applications.)  Since  most use cases don't have that many comments or have them there only temporarily, I am disinclined to spend the time to fix that.  I hope you understand.
