### ISSUE TITLE
Display character count next to word count?

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#187]
Dear @wereturtle, 

Just an idea:

How about adding a character count next to the word count at the bottom?

![image](https://cloud.githubusercontent.com/assets/170947/23703365/d7f4da8a-03ff-11e7-930e-7ca04f5c5ada.png)

**Comment by wereturtle** [comment]
I feel it makes it look cluttered.  But there is a HUD for the character count.  Thank you for your suggestion.

**Comment by thebodzio** [comment]
I'm sorry to revive this but I think it's better and less annoying to do it here rather than opening a new issue :}

Could you perhaps consider making this a matter of a specific setting in preferences? I'm asking because often it's more desirable (e.g. in publishing) to have a character count (with blank characters) rather than a word count. The former allows for more precise page area estimation.

Maybe allowing users to define their own “status” information would be a good alternative? Such setting could be made by e.g. using a form of placeholders (either visual or textual).

Anyway, thank you for a very nice application and consideration.
