### ISSUE TITLE
Cursor invisible

### ISSUE THREAD

**Issue by plgruener** [wereturtle/ghostwriter#188]
ghostwriter v1.4.2, running under ArchLinux und KDE Plasma.

Problem: my Cursor is invisible (or seems to have the same color as the background). I can write text as usual, and when selecting text, I can see the cursor blinking (on the dark selection). Changing Themes (or Fonts) did not work. Until some weeks ago, I did not had this issue.
Any suggestions?

**Comment by wereturtle** [comment]
See #178.  This issue was due to an update to Qt 5.8.  The Qt bug now has a workaround on the master branch, though it has not been formally released yet.  You can switch to using the AUR package of ghostwriter that is built against the latest changes on the master branch (as opposed to the version 1.4.2 AUR package).
