### ISSUE TITLE
How do you build windows installer?

### ISSUE THREAD

**Issue by dbelyaev** [wereturtle/ghostwriter#191]
Which script or SDK you are using to build installer package for windows? 

I could not find any installer script instructions for Windows installer in repository. I can create [Inno Setup](http://www.jrsoftware.org/isinfo.php) based script, if needed.

**Comment by wereturtle** [comment]
I start off with Qt Creator for quick builds and testing on Windows.  Right now I'm on Qt 5.5.1 with mingw.  I can't go to version 5.6 or above due to the QWebKit API being deprecated.  As such, QWebKit's libraries prebuilt libraries no longer ship on on newer versions of Qt.  (See issue #78.)  QWebKit can be hand built in newer versions of Qt, but that is quite a hassle.  I do have a long-term plan to switch to QWebEngine, although I may not need to if the team that is trying to resuscitate QWebKit is successful in un-depricating it.

The bottom line is to use Qt 5.5.1.  I personally use the mingw version.  I do have my own Inno Setup script, which is how I made the installer.  I start off by making the portable version, which involves copying the .exe file from my Qt Creator's project build area into a folder, and then copying (if needed) that Qt version's .dll files from the C:\Qt folder.  (Since I've been on Qt 5.5.1 on Windows for a while, I currently only need to use the last portable version I made and drop in the new .exe file.)  Finally, I run Inno Setup to make the installer from the portable version.

You can see an example of the file structure you'll need with the 1.4.2 release portable version.  Below is the Inno Setup script I used last time I did a release (replace `MY_USER_NAME` with your Windows login name).  I start with the portable version's folder on my desktop, and with my git repository under Documents\GitHub\ghostwriter.

```
[Setup]
AppId={{096AA89D-0275-4F5B-B144-7A0A6E9D614B}
AppName=ghostwriter
AppVersion=1.4.2
;AppVerName=ghostwriter 1.4.2
AppPublisher=wereturtle
AppPublisherURL=http://wereturtle.github.io/ghostwriter
AppSupportURL=http://www.github.com/wereturtle/ghostwriter
AppUpdatesURL=http://www.github.com/wereturtle/ghostwriter
DefaultDirName={pf}\ghostwriter
DefaultGroupName=ghostwriter
LicenseFile=C:\Users\MY_USER_NAME\Documents\GitHub\ghostwriter\COPYING
OutputDir=C:\Users\MY_USER_NAME\Desktop\output
OutputBaseFilename=ghostwriter-v1.4.2-setup
SetupIconFile=C:\Users\MY_USER_NAME\Documents\GitHub\ghostwriter\resources\windows\ghostwriter.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\MY_USER_NAME\Desktop\ghostwriter-portable\*"; DestDir: "{app}"; Flags: ignoreversion      
Source: "C:\Users\MY_USER_NAME\Desktop\ghostwriter-portable\platforms\*"; DestDir: "{app}\platforms"; Flags: ignoreversion      
Source: "C:\Users\MY_USER_NAME\Desktop\ghostwriter-portable\imageformats\*"; DestDir: "{app}\imageformats"; Flags: ignoreversion   
Source: "C:\Users\MY_USER_NAME\Desktop\ghostwriter-portable\printsupport\*"; DestDir: "{app}\printsupport"; Flags: ignoreversion    
Source: "C:\Users\MY_USER_NAME\Desktop\ghostwriter-portable\dictionaries\2\mor-standard\*"; DestDir: "{app}\dictionaries\2\mor-standard"; Flags: ignoreversion   
Source: "C:\Users\MY_USER_NAME\Desktop\ghostwriter-portable\dictionaries\*"; DestDir: "{app}\dictionaries"; Flags: ignoreversion         
Source: "C:\Users\MY_USER_NAME\Desktop\ghostwriter-portable\translations\*"; DestDir: "{app}\translations"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\ghostwriter"; Filename: "{app}\ghostwriter.exe"
Name: "{commondesktop}\ghostwriter"; Filename: "{app}\ghostwriter.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\ghostwriter"; Filename: "{app}\ghostwriter.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\ghostwriter.exe"; Description: "{cm:LaunchProgram,ghostwriter}"; Flags: nowait postinstall skipifsilent

```
