### ISSUE TITLE
Update Translations for version 1.5.0

### ISSUE THREAD

**Issue by wereturtle** [wereturtle/ghostwriter#195]
@suhr @dbelyaev @jggouvea @tajmone @piyo-gh @dhbwmawhd @pafri @pygoliae

Hi everyone!

It's time for another release of *ghostwriter*.  If you have time to volunteer, please update your translations of the application against the **master branch**.  You may submit a pull request with your changes, or you may attach your translation in a comment to this issue.

If I don't hear back from you within a month, I'll assume that you don't have time and will proceed with the release.  If you need more than a month, just let me know, and I'll wait.  There is no particular hurry.

Thanks in advance!

**Comment by tajmone** [comment]
I'm in! 

Might need a week or two though.

**Comment by suhr** [comment]
Looks like there's nothing to translate yet.

Russian translation is complete.

**Comment by dbelyaev** [comment]
Yeah, as @suhr mentioned above, russian translation looks complete. Maybe, it could be possible to incorporate this [PR on dev](https://github.com/wereturtle/ghostwriter/pull/197) into master, as it fixes a typo, but it is not critical, if it adds work to you. 

And maybe one simple `lupdate` on ts file in order to have it synced with sources.

**Comment by jggouvea** [comment]
Hello,

I have just completed the update. However, since I am not actively using ghostwriter as I used to be a couple of months ago (five books finished, now formatting them for publication using LaTeX), there might be some minor problems. If some one comes across an imperfection, please let me know.

**Comment by jggouvea** [comment]
[portuguese-Brazilian.zip](https://github.com/wereturtle/ghostwriter/files/891798/portuguese-Brazilian.zip)

**Comment by wereturtle** [comment]
Hi @jggouvea!  Thank you so much!  And congratulations on finishing five books!
