### ISSUE TITLE
Spanish translation for ghostwriter

### ISSUE THREAD

**Issue by cemetary** [wereturtle/ghostwriter#199]
Hi.

Here's a Spanish translation for ghostwriter.

Cheers! :-)

[ghostwriter_es.zip](https://github.com/wereturtle/ghostwriter/files/876634/ghostwriter_es.zip)
[Uploading ghostwriter_es.zip…]()

**Comment by wereturtle** [comment]
Hi @cemetary,

Thank you for your translation!  FYI, it looks like you were working with a somewhat older version of ghostwriter.  Many of the settings were moved from the Settings menu to the Preferences dialog.  These changes were just recently pushed to the master branch so that translators could begin working on the 1.5.0 release.  If you have time, would you mind grabbing the latest off the master branch and translating the Preferences dialog?  I have put your ghostwriter_es.ts file into the master branch under the translations folder.

If you don't think you'll be able to get around to it, that's OK.  I can release as is.  Just let me know.

Thanks again!

**Comment by cemetary** [comment]
@wereturtle  Oh, fuck. I didn't know that. I'm going to fix it on this weekend. ;-)
