### ISSUE TITLE
Live auto-preview

### ISSUE THREAD

**Issue by dessalines** [wereturtle/ghostwriter#201]
I'd love to use this client, as its native, but its still missing the best feature, that typora currently uses, which is live auto-preview. Typora is basically a WYSIWYG editor, but when you click on something bolded, or linked, or with any markdown, it expands the markdown. Ghostwriter still shows the markdown syntax, which when you have a lot of links per paragraph like I do, makes it pretty unreadable.

**Comment by suhr** [comment]
Ghostwriter already have HTML preview, and it is live. Though, it is extremely slow.

**Comment by dessalines** [comment]
@suhr typora handles auto-preview fine, and its an electron app. No reason why this couldn't do this too.

**Comment by suhr** [comment]
Web UI (even in electron) is much more flexible than Qt. For example, widgets Ghostwriter uses [doesn't allow to implement even elastic tabstops](https://github.com/wereturtle/ghostwriter/issues/193).

Also Ghostwriter seems to be purposely *not* WYSIWYG.

**Comment by wereturtle** [comment]
1. If your paragraphs are unreadable due to many links, use reference IDs.  For example:

    ```
    This is a paragraph with a [link using a reference ID][MYID1].
    
    
    [MYID1]: http://github.com
    ``` 
2. I don't understand what's with the WYSIWYG gimmick and Markdown.  If you need WYSIWYG, why not just use LibreOffice or FocusWriter?  You can always use Pandoc to convert it to something else later, or save as HTML.
3. It may very well be possible to make QTextEdit do WYSIWYG, but that is a very difficult, time-consuming feature to implement, and one I am not particularly passionate about.
4. If I did implement said feature, I would have to lock in everyone into a particular Markdown flavor.  At least without WYSIWYG, if syntax highlighting is too broad or narrow in its embrace of Markdown flavors, it's not going to look horrifically weird.  With WYSIWYG, I would have to choose a flavor to favor.  Many end users would be incredibly angry if I didn't pick *their* favorite flavor.
5. *ghostwriter* is open source under a generous GPL v.3 license.  Make a fork if it's that important to you.  (No, I will not accept a pull request due to reason 4 above.)
6. Why on earth would you even begin a Github issue with, "I'd love to use this client, as its native, but..."?  It's not like my income is at stake if you don't use my editor.
7. *ghostwriter* is free.  What do you want for free?  Rubber biscuits?  Tons of Markdown editors for MacOS that cost real money don't do WYSIWYG editing.  Every feature I add either interests me or is simply an act of kindness.  I am only occasionally thanked.  I am definitely not paid.  I also have other things I would rather do than work on _ghostwriter_ for free all the time, such as actually using my application to _write_.
8. I must politely raise an objection to suhr's calling the live preview "slow".  It waits for typing to stop before refreshing the preview.  This way, your typing doesn't freeze on large documents.  I dare anyone to try typing in a 100,000 or 200,000 word document with Typora.  Your ~~Ton-Ton~~ editor will freeze before you reach the first marker.  It's horribly sluggish.  You won't be writing your epic novel anytime soon in that. *ghostwriter*, on the other hand, is snappy no matter what size your document is.  I'm proud of that feat.
9. Which leads me to my final point.  You obviously are interested in writing much shorter documents.  In which case, Typora sounds like the perfect editor for you.  *ghostwriter* is optimized for large documents.  This is not your use case, which I understand perfectly.

I do hope you'll forgive me my little rant.  I appreciate when people show interest and ask for new features.  However, I don't think it's too much to ask if people would please stop asking for features that don't completely repurpose the application to clone another perfectly good application which you could have used instead.  You have a viable alternative that works for you.  Please use that, and let _ghostwriter_ be _ghostwriter_.

**Comment by suhr** [comment]
> It waits for typing to stop before refreshing the preview. This way, your typing doesn't freeze on large documents.

There's no reason not update DOM (without reloading the page) in parallel for documents that are reasonably small.

**Comment by wereturtle** [comment]
> There's no reason not update DOM (without reloading the page) in parallel for documents that are reasonably sized.

It's not updating the DOM that lowers performance.  It's extracting the text from the editor to hand it to the Markdown processor that really eats performance.  One person told me to basically write my own text editor to be able to extract the text more efficiently.  Obviously, that will never happen.  I have better things to do than to render all the text from scratch with my own text buffer.

As for updating after every key press for a reasonably sized document, what is a reasonably sized document?  That varies based on an individual's hardware.  I have an old clunker lying around that I do performance testing on.  If typing freezes on that, then I don't push the feature.

Besides, I find it strange that someone would stare at the live preview while they are typing.  I would imagine most people would be staring at what they are actually typing, and not the preview.  I can experiment with how long after the last key press that the editor thinks the user has stopped typing, but I have to balance that with the fact that some people are slow typists, which means they will have a longer pause between key presses.  It's a huge balancing act.

**Comment by suhr** [comment]
> It's extracting the text from the editor to hand it to the Markdown processor that really eats performance.

I see... QTextEdit strikes again.

> Besides, I find it strange that someone would stare at the live preview while they are typing.

You don't need to stare directly at it to fell how much sluggish it is.

**Comment by dessalines** [comment]
> ghostwriter is free. What do you want for free? Rubber biscuits? Tons of Markdown editors for MacOS that cost real money don't do WYSIWYG editing. Every feature I add either interests me or is simply an act of kindness. I am only occasionally thanked. I am definitely not paid. I also have other things I would rather do than work on ghostwriter for free all the time, such as actually using my application to write.

Holy shit, WTF is all this. I literally just suggested a cool feature to have, and instead of politely refusing, you're misattributing all this like I'm demanding something without thanking you?, and then saying its only out of simple acts of kindness that you add features? WTF man, I'm an open source dev too, and when people suggest something that I don't feel its worth adding, I just politely decline. 

> I dare anyone to try typing in a 100,000 or 200,000 word document with Typora.

You clearly haven't tested it, because it does work fine. Typora is one of the only ones that I can use that this does work correctly for, I'm guessing because it smartly doesn't try to re-convert already converted sections, but only converts the current line or section that you're on.

**Comment by wereturtle** [comment]
> WTF man, I'm an open source dev too, and when people suggest something that I don't feel its worth adding, I just politely decline.

Then why would you even say, "I'd love to use this client, but...?"  That wording strongly implies that you're not going to use _ghostwriter_ unless it's just like Typora.  That's a veiled threat.  It comes across as very rude.  If you had just asked nicely, I would have simply thanked you for your suggestion and closed the issue.  It's one thing to suggest a feature, and quite another to say you won't use the tool unless it has feature X.  That shows a gross entitlement attitude.  How would you like it if I showed up to your open source project and told you I don't want to use it unless it has feature X?  It wouldn't go over very well, now would it?  I thought I was quite restrained in my response.  I only wished to remind you to be more polite.  Now, maybe you didn't mean to convey a threat, but perhaps you will be more cautious in your wording in the future.

And yes, I have used Typora.  It gets really sluggish on large documents.  Perhaps I only notice because I type really fast.  But, hey, I'm glad you found a tool that works for you!  I truly do wish you well in your choice of software, and I'm sorry that _ghostwriter_ isn't for you.
