### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by yotamN** [wereturtle/ghostwriter#206]
RTL support for Arabic and Hebrew would be nice, couldn't find it in the settings.

**Comment by wereturtle** [comment]
ghostwriter is coded such that it will change the layout to be right to left when a translation is loaded for a locale / language that is right to left.  Since there is no Hebrew or Arabic translation yet, it's not going to do it.  However, if you would like to experiment with the RTL layout in the default language (English) or another language for which it has a translation, you can launch ghostwriter from the command line as follows:

    $ ghostwriter -reverse

This will change the layout of the entire application to be right to left, no matter the language.

Here is some documentation on how RTL works in Qt apps, in case you are interested:

* <http://doc.qt.io/qt-5/qtquick-positioning-righttoleft.html>
* <http://doc.qt.io/qt-5/internationalization.html>

I think I coded ghostwriter to correctly go RTL if a translation file indicates an RTL language.  However, if you happen to be working on an Arabic or Hebrew translation for ghostwriter, and you find that it's not working, please let me know.  You'll need to attach your work-in-progress translation, and I'll play around with it until I can get the RTL layout to load automatically.

Thanks!

**Comment by yotamN** [comment]
I meant RTL for the text that I write, not the GUI, even with the reverse flag the text that I write is still on the left:
![screenshot from 2017-04-04 10-34-23](https://cloud.githubusercontent.com/assets/5249239/24645783/497f4bd6-1922-11e7-9a1f-0ab5edf5c0e1.png)

**Comment by wereturtle** [comment]
Thank you for the clarification.  After several hours of experimentation and beating my head on my desk, I have good news and bad news.

The good news is that if I switch the editor from using QPlaintTextEdit to QTextEdit, Hebrew and Arabic are correctly aligned from right to left.

This leads to the bad news, which comes in two parts.  Apparently there is a bug in QPlainTextEdit that was getting in the way of the editor working with RTL languages properly.  See [QTBUG-7516](https://bugreports.qt.io/browse/QTBUG-7516).  This was closed some years ago.  The developers don't seem to think that this should be how QPlainTextEdit should work.

This wouldn't be a big deal, of course, as we have a viable alternative with QTextEdit, which works perfectly.  However, with QTextEdit, the editor now takes a huge performance hit on large documents whenever it syntax highlights the entire document.  This rehighlighting operation happens when correcting spelling / adding a word to a dictionary, changing heading sizes, switching from italics to underlining for emphasis, and so on.  It is so visibly slow, that the application will hang for at least a minute while it rehighlights the text.  It would not surprise me to see other signs of sluggishness with other operations as I continue to test.

I will keep looking at this to see if I can improve performance.  However, I'm not sure how much I can do.  QPlainTextEdit was supposed to be the editor to choose over QTextEdit because of its speed, which is exactly why I chose it in the first place.  I really don't want to switch to QTextEdit unless I can work around these performance issues.  As such, I cannot 100% promise a fix.  But I will continue to try.

Thanks again for reporting this issue.  I had assumed QPlainTextEdit could handle RTL, since there is nothing in the documentation that says otherwise.  If you are feeling up to it, would you mind joining in on that bug report and voting on it?  The best solution would be for the Qt devs to reopen it and fix the issue.

Here is the bug report:  [QTBUG-7516](https://bugreports.qt.io/browse/QTBUG-7516).

Thanks again!

**Comment by ali-hardan** [comment]
[QOwnNotes](https://www.qownnotes.org) is use QPlainTextEdit, but it works with RTL language properly.

That is open source, so, may can help to fix this issue.

**Comment by ali-hardan** [comment]
I have fixed it. I have used `QMarkdownTextEdit` class, which part of QOwnNotes project. See:

``` C++
/**
 * Overrides QPlainTextEdit::paintEvent to fix the RTL bug of QPlainTextEdit
 *
 * @param e
 */
void QMarkdownTextEdit::paintEvent(QPaintEvent *e) {
    QTextBlock block = firstVisibleBlock();

    while (block.isValid()) {
        QTextLayout *layout = block.layout();

        // this fixes the RTL bug of QPlainTextEdit
        // https://bugreports.qt.io/browse/QTBUG-7516
        if (block.text().isRightToLeft())
        {
            QTextOption opt = document()->defaultTextOption();
            opt = QTextOption(Qt::AlignRight);
            opt.setTextDirection(Qt::RightToLeft);
            layout->setTextOption(opt);
        }

        block = block.next();
    }

    QPlainTextEdit::paintEvent(e);
}
```

The reference:
https://github.com/pbek/qmarkdowntextedit/blob/develop/qmarkdowntextedit.cpp

I have used it on ghostwriter `MarkdownEditor` class, it worked.

I'm a RTL user, so I can confirm that's works correctly.

**Comment by ali-hardan** [comment]
If PR is open, I will submit PR.

**Comment by wereturtle** [comment]
Thanks, @ali-hardan, for looking into this!  I'll test it and see how it goes.

**Comment by ali-hardan** [comment]
@wereturtle, You will need RTL text to test and debug:

    این یک متن راست به چپ است.

**Comment by Sioma112233** [comment]
It does work now, but not in the HTML preview
