### ISSUE TITLE
Theme code blocks have low contrast

### ISSUE THREAD

**Issue by gabm** [wereturtle/ghostwriter#224]
I used the theming capablites to create a solarized dark color scheme. While that worked great and as expected, I see no option to change the color of code blocks (using `). They give very low contrast... How can I change this color?

Further: What is the "Text Area Background Color" useful for?

Otherwise, thanks for this great application, highly recommendable!

**Comment by wereturtle** [comment]
Sorry, I forgot to answer your question.  You asked:

> What is the "Text Area Background Color" useful for?

It's so you can make themes like below.  Here, Text Area Background Color is set to white, with mild opacity lowered in the other tab, as well as the editor aspect being set to Center instead of Stretch.

![image](https://user-images.githubusercontent.com/10375170/27256378-9b1ef548-5367-11e7-91d7-b9231583d9e8.png)

**Comment by pjpjek** [comment]
+1 @gabm is right.

Please let us change font color for code blocks and also add background 
![inline_code](https://user-images.githubusercontent.com/10369607/29832706-a840896e-8cae-11e7-944e-718877f75020.png)

**Comment by wereturtle** [comment]
The fix to allow setting the color of block quotes and code blocks is in the dev branch.  The dev branch version of *ghostwriter* will also add a background to code blocks and block quotes to further help visually.  You can play around with it now, if you're feeling impatient.  It's very stable now, so I recommend grabbing a snapshot of the code on dev and building it before further commits go in.  Otherwise, you'll have to wait a while until the next official release.  (Sorry for the long wait between releases.  I've learned the hard way to do that, though, to ensure maximum testing so that what gets released is very stable and that all features play nicely together.)

**Comment by gabm** [comment]
@wereturtle thanks for the fix. I'll wait for the next release...

Personally I don't think thats the right way to prolong release cycles and block things up -> [RERO](https://en.wikipedia.org/wiki/Release_early,_release_often)

**Comment by wereturtle** [comment]
> Personally I don't think thats the right way to prolong release cycles and block things up -> RERO

The problem is I'm the only serious tester of the dev branch.  I also don't want to be blamed if I mess something up to where a document ends up corrupted.  And I have done that one before!  That's why I stopped the RERO thing.  Better to make sure it's finished and ready.  Finally, putting out a release still takes time.  There's release notes to write, packaging, double checking the packaging, etc.  I have scripts to help me, especially with the PPA, but it's still time consuming.
