### ISSUE TITLE
Latex Template and Pandoc support

### ISSUE THREAD

**Issue by stockphrase** [wereturtle/ghostwriter#226]
Hi,

I read that you don't currently have bandwidth for new features,  but I thought I'd just suggest something in case you thought it worthy. 

I'd like to have my markdown file passed to a latex template by Pandoc so I can output to .pdf. I have templates for a variety of documents: personal letters, business letters of various types, memos, etc. 

Usually, I write these documents in markdown and have Pandoc pass it though a latex template and output to .pdf. The command goes something like this:

`pandoc -s --latex-engine=xelatex --template=personalstationary.tex letter.md -o letter.pdf`

It would be great if Ghostwriter could do this for me so that I don't have to drop into command line. It would be *phenomenal* if the preview could show a real-time preview of the file using the latex template (as in Marked, http://marked2app.com/). I'm  happy to share my templates with you if it would be helpful or worth your time. 

Thanks for sharing this great software!

**Comment by wereturtle** [comment]
What I thought would be cool is if we could get a set of templates not only for LaTeX, but for CSS, Word documents, ODT documents, etc.  In other words, a single style can be selected for export/preview, and it can handle all sorts of different document formats.  Unfortunately, it would be Pandoc-centric.  But perhaps I could have the other Markdown processors generate HTML first, and then feed the HTML to Pandoc for the final document format, with the template/style applied.  Ulysses seems to have styles like this that apply to whatever export format the user chooses.  It would be a lot of work to create all of those, though.  But if the community can pull off a decent set of templates/styles for at least PDF/LaTeX, CSS, ODT, and DOC/DOCX, I'd be interested in doing the code to select the style for export and pass in the parameters to Pandoc.  It would be a lot of work on everyone's part, though.  We would probably want documentation on how to create a template for each format, so that more community members can volunteer for different styles.

What do you think?

**Comment by stockphrase** [comment]
Sounds very cool.

**Comment by SheepRock** [comment]
I came here because I wanted to pass a docx template when exporting by pandoc (it uses the `--reference-docx=template.docx`).  

I think a good option would be a text field in the export window so the user can enter extra arguments to pass to the command line when generating the file. So, ghostwriter would append the contents of the text box to the command that it would pass to cmd. This way everything became more flexible.

**Comment by stockphrase** [comment]
Nice, SheepRock. That would be an elegant solution.

**Comment by ber532k** [comment]
Also see issue #180 which requests exactly that: custom export options. I would suggest having *inputFile* and *outputFile* as shell variables. I believe shell is still the most common general purpose scripting interface, so pandoc could execute whatever the user-defined command is as a shell command and set `$inputFile` and `$outputFile` environment variables. That would also accommodate people like me, who use their own custom wrapper for creating pdf files.

For preview I believe the most important addition would be pdf-preview. Once a docx or odt file is generated somehow, it is easy to run `lowriter --convert-to pdf $outputFile`. The resulting pdf could then be previewed. As an alternative ghostwriter itself could use such external commands for docx or odt preview (and thus rapidly add many formats for preview using only a pdf-viewer really.

I don't know how html preview currently works, but if ghostwriter does indeed generate some html internally exposing `$outputFile` to a shell command would allow for any css-customization one could dream of, wouldn't it?

**Comment by pazos** [comment]
A note on this: 

I'm currently building a latex exporter on top of hoedown. Currently I'm using a fixed template but its ready to support metadata.

By default template is document_a4paper and author, name, subject and date are empty (and thus not wrote)

I didn't look at the UI part yet but I think it shouln't be too difficult to get that data on the exporting/save window.

A combobox for templates, a few lineEdits to introduce data and checkbox(es) to select between true/false statements (like add toc or show date).

The same metadata should be useful for pandoc too, at least for pdf/epub

**Comment by stockphrase** [comment]
*sniff*
