### ISSUE TITLE
New Feature: Chapter position bars

### ISSUE THREAD

**Issue by hirschenberger** [wereturtle/ghostwriter#231]
Hi, I extended the outline HUD with position indicators. You can see the result here: 

![chapter_positionbars](https://user-images.githubusercontent.com/1053180/27797745-078002dc-600f-11e7-9c07-bd2e333a8ff3.png)

I wanted to discuss it first, before opening a PR. There are several possibilities for the styling. This one has a minimal visual impact. It would also be possible, to draw lines under the titles where the position is the position in text, and the length is the length of the section. This makes the section-length more visible, but is more distractive.

What do you think?

EDIT: I adapted the highlighting of the current section, it now uses the selected theme.

**Comment by wereturtle** [comment]
Are these position bars indicating where the caret position is in the chapter?  If that's the case, why are there multiple position bars on each chapter?  Perhaps you can tell me more about this feature, as it is something I have not seen before.

**Comment by hirschenberger** [comment]
It shows the Position of the chapter or subsection heading as absolute Position in the whole document. There's only one indicator for each heading and subheading. As you see for the last three chapters, no text has been written yet. It helps to see the distribution of lengths of each structuring heading. helps to find overlong sections and indicates the current position in the document.

Here's a gimp'ed version of the second proposal, where the length of each section is indicated by a bar. As I said, it may be a little bit too distractive. 

![chapter_positionbars2](https://user-images.githubusercontent.com/1053180/28055620-1157876a-661a-11e7-8025-e2336279df1c.png)

**Comment by pierreporte** [comment]
As is, I don’t see the point of this. Why would one needs or wants to show the relative length of the different sections this way? However, rotating this into vertical lines and fusing it into some sort of minimap (popular feature in modern code editors) seems more useful and intuitive.

**Comment by hirschenberger** [comment]
Minimaps do make sense in inhomogenous text like sourcecode, as it is possible to jump to sections by identifiing them by their appearance. In simple prose, it will be hard to recognize any structure. 

Examples from VS Code:

Code | Prose
--- | ---
![minimap_code](https://user-images.githubusercontent.com/1053180/28075361-8d0dfeac-665b-11e7-919c-94dd06ca3a29.png) | ![minimap_prose](https://user-images.githubusercontent.com/1053180/28075376-92c3253e-665b-11e7-96fb-fbb68073fee6.png)

And if you start to simplify it, it will become a listbox with section titles in it and different heights. When you want to avoid scrolling, you start indicating the position and length horizonatlly  and we're where we are.

**Comment by jmhibben** [comment]
@hirschenberger Do you think it would be possible to toggle the indicators between `none` and the two proposals you have? Personally, I'm not sure which I'd use, but it'd still be nice to have these for some of the documents I write.

**Comment by hirschenberger** [comment]
@jmhibben Sure, but for now I only implemented the first version. I wanted to discuss this topic before polishing the code and opening a PR.

**Comment by wereturtle** [comment]
Well, I do think the feature is interesting, albeit distracting to put it on the Outline HUD.  And I know others will come onto GitHub and keep asking what the tick marks mean.

Perhaps instead of putting tick marks on the Outline HUD, you can put them next to the scroll bar?  One tick mark per heading, perhaps in the link color for the theme.  It would be similar to a minimap, but smaller.  (It would also be a pain to code, using paintEvent magic.)

Maybe another alternative would be opening a separate dialog to view chapter/section statistics, perhaps in graph form.  I do think the idea of showing the author whether their writing is lopsided (some chapters being too long, others too short) is a good one.  I'm sure we could come up with many different ways to approach displaying the information to the user.

Also, before submitting a pull request, please see my fairly recent [CONTRIBUTING.md](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) guide.  I know GitHub does not show it prominently when posting issues, so you probably didn't notice it.  But the short of it is, if you choose to go through with coding this, it will be a long while before I can get to the pull request.  Even if I accept it after a code review, I will expect extensive testing from you before you submit it.  (I have to stress that because I've gotten some buggy stuff in pull requests before that I have had to debug.)

**Comment by hirschenberger** [comment]
Hi, as I'm using this feature as it is for some time now, I don't think I'll change it further in my repo. I don't like the minimap approach, as there's no chapter names next to the markings, so it's not so obvious as in the Outline. Also I find a (minimal) minimap more distracting than a 3px line between the lines of the outline.

I've read the contribution file, you're free to merge or not. I mainly do this for improving my own tooling when writing. So I have no strong demand, getting the feature into the source.
