### ISSUE TITLE
RFC: Todo HUD window

### ISSUE THREAD

**Issue by hirschenberger** [wereturtle/ghostwriter#236]
Hey,

what do you think about a *Todo HUD*? It should contain all markdown checkbox entries like these:

- [ ] Do this
- [x] Do that

I'm currently writing a novel, and my workflow is, to use these as annotations and things to do or check. They are scattered around in the document and it would be nice to list them and jump to them by click.

**Comment by wereturtle** [comment]
I like the idea.  I think it would be useful.  Coding it would be similar to how the Outline HUD works.  Should you choose to submit a pull request, please test, test, test before doing so.  (As my contributing guide says, I'm very busy now, but I'll make an exception for you since what you've submitted so far works.)  Please also use safe coding practices.  I think the following sums it up:

**Don't do:**

```
// if statement without curly braces
if (true)
   callMyFunction();
```

**Do:**

```
// if statement with curly braces
if (true)
{
    callMyFunction();
}
```

**Don't do:**

```
if (variableValue == CONSTANT_VALUE)
```

**Do:**

```
if (CONSTANT_VALUE == variableValue)
```

And never, ever do pointer arithmetic.  I think that covers it.  Finally, please make sure your IDE is set to use four spaces in place of tabs.

Thanks!

**Comment by hirschenberger** [comment]
I have implemented an initial version, it's implemented similar to the outline HUD.

![tasklist](https://user-images.githubusercontent.com/1053180/28354002-6810644c-6c5e-11e7-963d-50eabaadf05a.png)

It works so far, but when I modify a task with `Ctrl-D`, it does not update the checkstate, whereas it does it when modifying the task by hand. I think there's some signal missing. I must take a further look into this.

I'd like to fade-out the text on the right side of the, as we can't display the whole contents. What do you prefer, an apha-channel fade out or an ellipsis (...) at the end of the text?

I also must cleanup the code make it your coding rules conforming and do more testing.

Should the task also be toggleable by clicking in the item or should it just jump to the entry and may be modified with `Ctrl-D` or manually?

I also just realized a small UI-design glitch, it's a common approach that checkboxes are squares and radiobuttons are round, do you think that may confuse users? I like the round buttons more.

**Comment by wereturtle** [comment]
> It works so far, but when I modify a task with Ctrl-D, it does not update the checkstate, whereas it does it when modifying the task by hand. I think there's some signal missing. I must take a further look into this.

Make sure you are doing it roughly the same way the headings are handled.  That means the change to the checkstate should be detected in the MarkdownHighlighter class.  You'll note the following two signals in this class for headings:

```
        /**
         * Notifies listeners that a heading was found in the document in the
         * given QTextBlock and with the given level and heading text.
         */
        void headingFound(int level, const QString& text, QTextBlock block);

        /**
         * Notifies listeners that a heading was discovered to have been removed
         * from the document at the given cursor position.
         */
        void headingRemoved(int position);
```
Then there is the destructor of the `TextBlockData` class.  You'll want to follow that example to detect that a block has been deleted entirely (because the `QPlaintTextEditor`and `QTextDocument` classes won't tell you which blocks were deleted or what they contained).  This calls `TextDocument::notifyTextBlockRemoved()`, which then emits two signals that you'll want to connect to and handle for your task case.

When you check off a checkbox in the new Tasklist HUD, you'll want to make a call directly to `MarkdownEditor::toggleTaskComplete()`.  That will automatically trigger syntax highlighter, which will then trigger everything else.

> I'd like to fade-out the text on the right side of the box, as we can't display the whole contents. What do you prefer, an apha-channel fade out or an ellipsis (...) at the end of the text?

I would say an ellipsis would be best, just because doing an alpha channel fade with a `paintEvent()` override would be a hassle.  But then, I'm not sure how that works for languages other than English.  We can just leave it as an ellipsis for now.

> Should the task also be toggleable by clicking in the item or should it just jump to the entry and may be modified with Ctrl-D or manually?

Definitely clicking on the item should toggle the task.  If you don't do it now, people will ask for the feature later.  :smile:

> I also just realized a small UI-design glitch, it's a common approach that checkboxes are squares and radiobuttons are round, do you think that may confuse users? I like the round buttons more.

Yes, checkboxes are the norm.  I've recently adopted the Papirus icon set, if that helps you find a nice checkbox icon.  I wouldn't worry about it too much.  I can always replace it later.  The biggest thing to make sure of is that the checkbox icon is colorized to match the foreground text in the HUD, per the theme configuration.  You'll probably want to do a separate `QGraphicsColorizeEffect` for each checkbox somehow, as I've noticed graphical glitches on different platforms when trying to apply the effect to a parent widget to cascade to the children.  It's best to do it directly to each child to get a consistent effect.  The other alternative is to take the SVG and draw it yourself into a QPixmap.  Be sure to test for HiDPI screens if you go this route.  You can test for HiDPI by setting `QT_SCALE_FACTOR=2` as an environment variable before launching the app.  This will scale the GUI by a factor of 2.  You'll want Qt 5.6 or later.  Qt 5.9 is best for this.  Of course, if you go with `QGraphicsColorizeEffect` over drawing your own colorized pixmap from the SVG, you won't need to test for this.  The bugs for HiDPI with the graphics effects were fixed in Qt 5.9.

>  Edit: I realized, that the Ctrl-D update problem goes away, if I disable the cursor.beginEditBlock() and cursor.endEditBlock() und the toggle function.

If you follow all of the above, you should (knock on wood) not need to remove the calls to `cursor.beginEditBlock()` and `cursor.endEditBlock()`.  These calls are necessary so that the modification of the text block counts as a single undo/redo operation.

Sorry in advance if you were aware of the above already.  It's hard to tell where you are at without seeing your code.  So I dumped the contents of my brain.  :smiley:

**Comment by hirschenberger** [comment]
So far so good.  #239

Unfortunately it does not work without removing the `cursor.beginEditBlock()` and `cursor.endEditBlock()`. I think there must be a signal emitted that the block actually changed. I'll take a look at it when I have some time.

I tested and the rest works pretty good. You may also take a look at it. I used `QItemDelegate` for the painting, it's an elegant mechanism. I forgot how nice Qt sometimes is.

I also included checkbox icons and colorized them like the others.

**Comment by wereturtle** [comment]
Thanks!  Sorry I haven't gotten back to you.  I've been working a lot of overtime.  As such, it'll probably be a couple more weeks before I can look through your code and start merging.  But I just wanted thank you so much for your contribution!

**Comment by jonaskoeppel** [comment]
Hey, 
First, thanks so much for the most amazing writer app! 
Second, has there been any follow-up on the ToDo HUD? It really would be an awesome feature! 

Thanks!
