### ISSUE TITLE
How to wirte formula？

### ISSUE THREAD

**Issue by aevilorz** [wereturtle/ghostwriter#238]
I‘m new for ghostwriter. My markdown file containing some formulation codes like:
```
\begin{eqnarray}
Hardlim(n) = 
\begin{cases}
0 & n \le 0 \\
1 & n \ge 0
\end{cases}
\end{eqnarray}
```
I cannot either preview it in html or export it to PDF, but i can export it to PDF using pandoc commands
So, how to solve it?
thx!

**Comment by jmhibben** [comment]
I'm not entirely sure about multi-line equations like that, but GhostWriter renders small inline equations just fine in a preview, so long as `Pandoc` is the seleccted rendered. I tried to copy your equation verbatim, but the preview either fails to render or only renders part of the equation. Since I don't have my LaTeX environment properly set up yet, I can't verify that it properly converts the equations when rendering to PDF.

Pandoc's documentation has a section [dedicated to math](http://pandoc.org/MANUAL.html#math) that I recommend you take a look at and experiment with. Unfortunately with some equations, preview rendering may not be possible.
