### ISSUE TITLE
Spell check not working in Solus

### ISSUE THREAD

**Issue by JohnBlood** [wereturtle/ghostwriter#240]
I'm having trouble with spell check in Ghostwriter. I'm using Solus. I installed Ghostwriter and Hunspell. I had sure to install the hunspell-en package. For some reason, all of the words in my documents are underlined. When I right click on it, it says "No spelling suggestions found." Application language is set to English. Dictionary language is set to American English. Ant idea how I can fix this?

**Comment by wereturtle** [comment]
Hi John,

I installed Solus with the Budgie desktop in a VM, and I could not replicate the issue.  To be fair, I did cheat a little bit.  I installed the version of *ghostwriter* available in the repo rather than compiling and installing from scratch.  I installed the hunspell-en package, and the spellchecking is working as I would expect.  I'm not sure what is going on in your installation.  Alas, I do not know enough about Solus to know what might be wrong.  Perhaps you could try reinstalling?  Also, trying installing another Junspell dictionary for a different language, and select that in *ghostwriter*, and then switch *ghostwriter* back to the English dictionary, in case for whatever reason the app didn't pick up the dictionary correctly.

Strangely, the package maintainer didn't install qt5-svg, so none of the buttons show up in the app.  So FYI, you'll probably want to install that if you want to see the SVG buttons.

**Comment by JohnBlood** [comment]
I ran some updates and the problem has been resolved. Sorry to bother you.

**Comment by wereturtle** [comment]
No worries!  I know it can be hard to track down what the problem is when something isn't working.
