### ISSUE TITLE
Love this!

### ISSUE THREAD

**Issue by DougBeney** [wereturtle/ghostwriter#249]
I greatly appreciate this project. I just wanted to let you know that I plan to help you out building a Mac version as well. 

Also, a feature I'd love to see in the future is some sort of library feature that would function very similarly to Sublime Text. 

Keep up the awesomeness!

**Comment by DougBeney** [comment]
Also, is there any way to tweak the line height? I was going to try with a custom theme, but couldn't figure it out.

**Comment by wereturtle** [comment]
Hi Doug!  Thanks for the kind offer to make a Mac build.

Unfortunately, I've found it's not really possible (at least with a *plain* text editor box) to tweak the line height.  I can't switch to the rich text editor due to some performance issues with it.  (Even then, with the rich text editor, tweaking the line height is a crazy hack.  I'm amazed the author of FocusWriter even figured that one out!)

**Comment by DougBeney** [comment]
Huh, interesting. 

I'm quite new to Qt. Why is such a simple feature, even with QTextEdit, such a complicated task? I did a bit of research and you weren't kidding. 

Are there any good alternative libraries for text editing in Qt that will offer more customization?

**Comment by wereturtle** [comment]
> Are there any good alternative libraries for text editing in Qt that will offer more customization?

None that I know of.
