### ISSUE TITLE
Ghostwriter looks weird on Wayland

### ISSUE THREAD

**Issue by belenos** [wereturtle/ghostwriter#251]
I'm using Ubuntu 17.10 Gnome and ghostwriter looks weird on Wayland session. When I run it on X, it looks fine.

![screenshot from 2017-08-27 12-35-51](https://user-images.githubusercontent.com/1954831/29751487-526779d4-8b24-11e7-9b4a-d2abe4d5ad1e.png)

**Comment by wereturtle** [comment]
Hmm.  Well, I installed Ubuntu 17.10 in VirtualBox.  Interestingly enough, I couldn't install *ghostwriter* from its PPA build that way, as Canonical had changed the hunspell version, and that PPA build had built against a previous version from when 17.10 was still in alpha.  I uploaded a second PPA package version to the PPA so that it could rebuild against the new hunspell, and then it installed fine.  It also looked normal, and not like it does in your screenshot.

I am thinking maybe Canonical also bumped up the Qt version or some other dependency after *ghostwriter*'s initial PPA build against 17.10 (and sometime before hunspell got updated), and perhaps that is why when you launched the app it didn't look right?  Go ahead and update with the PPA to get the new version.  Hopefully it works this time around.
