### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by ghost** [wereturtle/ghostwriter#268]
This is a nitpicky request. I use Ghostwriter on a Surface, and while it's not unusable in tablet mode, it's a bit clunky. I have to grab the scroll bar to scroll, because trying to scroll with just my finger ends up selecting text, the touch keyboard doesn't automatically pop up when I tap a new line (though to be fair, the keyboard not popping up is an ongoing issue with most desktop apps; Chrome is one of the few where it works consistently), etc. Would it be possible to add proper touch support?

**Comment by wereturtle** [comment]
I'm honestly not sure how to do that.  I'm just using a standard QPlainTextEdit.  I would imagine that perhaps this is what the QML side of Qt is for, rather than the C++ side, but I could be wrong.  I'll leave this issue open, in case a more experienced person comes along and has an idea of how to do this.

**Comment by abenson** [comment]
I don't have any touch screens so I don't know, but can you scroll with two fingers like a touchpad?

**Comment by Gizmaton** [comment]
Two finger scrolling does work, though I still have the "selecting lines of text while scrolling" problem.
