### ISSUE TITLE
ncurses

### ISSUE THREAD

**Issue by letarg0** [wereturtle/ghostwriter#274]
Is possible to create ncurses version?
I hate graphic. Speed is important.

**Comment by wereturtle** [comment]
Perhaps you don't realize this, but you are asking me to entirely rewrite the entire application in a completely different API from scratch?  It took me several *years* to get a Qt version off the ground with so many features, and I already have a full time job.  :anguished:

If speed is truly important to you, you might consider learning how to code with ncurses for yourself so that you can meet your own needs, as I have done for myself.  I look forward to your sharing your new application with the world!
