### ISSUE TITLE
Polish translation for ghostwriter

### ISSUE THREAD

**Issue by mleko69** [wereturtle/ghostwriter#280]
Cześć!
First of all thanks for ghostwriter. I've discovered it yesterday and I instantly fell in love with it. Here's a trlanslation to polish language:
[ghostwriter_pl.qm.zip](https://github.com/wereturtle/ghostwriter/files/1629280/ghostwriter_pl.qm.zip)

Just two things:
1) I couldn't translate these options and settings. Strings are missing?
![screenshot_20180114_122652](https://user-images.githubusercontent.com/22177132/34915395-3b488ea8-f926-11e7-8b29-48713224bb07.png)

![screenshot_20180114_122854](https://user-images.githubusercontent.com/22177132/34915411-811013f2-f926-11e7-9033-65d83920d504.png)

2) Is there a way to translate Quick Reference Guide?

Much love, Patryk.

**Comment by wereturtle** [comment]
Thank you for the thanks, and for volunteering to translate!

> 1. I couldn't translate these options and settings. Strings are missing?
That's strange.  I put in the tr macros.  I'll have to look into this further.  I will be announcing a formal "Update the translation" notice to all the translators in a couple of weeks.  Hopefully I'll have that fixed by then.  I'll also be sure to add you to that notification list.
> 2. Is there a way to translate Quick Reference Guide?
Yes!  Under the resources folder, you will notice the following files:

* quickreferenceguide_en.html (English HTML)
* quickreferenceguide_en.md (English Markdown)
* quickreferenceguide_ja.html (Japanese HTML)
* quickreferenceguide_ja.md (Japanese Markdown)

First, create your Polish version Markdown file, `quickreferenceguide_pl.md`, using the Pandoc flavor of Markdown.  Then, run it through Pandoc to create the HTML version.  Finally, add them both to the resources.qrc in the top directory for the source code.  (I can do that last part, if you need.)  Once you or I build, ghostwriter will pick these up automatically when Polish is selected for the application language.

**Comment by mleko69** [comment]
That sounds a bit complicated, but I'll take care of it in a free time. 
Yea, feel free to add me to that translators notification list. ;)
And, the last thing - where should I upload corrected translations (spelling and grammar fixes, corrected consistency of translations, etc)? Here as attachments or somewhere else?

**Comment by wereturtle** [comment]
You can reattach updates here, or else put in a pull request.  Thanks!

**Comment by wereturtle** [comment]
Hi @mleko69,

I hadn't realized you had attached a zip of only the .qm file and not the .ts file.  There should be a .ts that you originally edited with Qt Linguist.  Without the .ts file, I can't debug what went wrong with translating the Preferences dialog.

Thanks!

**Comment by mleko69** [comment]
Och, my bad. Here's the archive with all files. I'm busy with exam session atm, but translation is about 90% done. I'll take care of it as soon as possible. 

[ghostwriter_pl_all_files.zip](https://github.com/wereturtle/ghostwriter/files/1714787/ghostwriter_pl_all_files.zip)

**Comment by wereturtle** [comment]
Thanks!  I've committed your `.tl` file to the translations folder.  I also ran lupdate on it, so it should be in sync with the latest.  If you have not run that command yourself, you will want to download your updated `.tl` from the translations folder in the master branch before you resume.  Thanks again!

**Comment by wereturtle** [comment]
Hi @mleko69, do you know if/when you will be able to finish the translation?  I don't mind waiting, but I'd like to know about how long, or if you've decided you can't get to it.  Thanks!

**Comment by mleko69** [comment]
Hello,

I'll finish it tomorrow (it's 1:37 AM here ATM). There are few things about
which I'm not sure how to translate them. For example there is no
equivalent for "blockquote" in polish, but I can translate it into
something that means (more or less) "quote in in a block". I think I'll
simply take that "translate by purpose" approach so the translation will be
as elegant as possible, so... Expect some questions about options and
functions implemented in ghostwriter! ;)

Kind regards,
Patryk Andryszczuk.

17.03.2018 18:41 "wereturtle" <notifications@github.com> napisał(a):

**Comment by wereturtle** [comment]
No worries!  Take your time!
