### ISSUE TITLE
Support # links

### ISSUE THREAD

**Issue by 1e4** [wereturtle/ghostwriter#283]
Hi there,

Love GhostWriter thus far, it really makes writing Markdown an enjoyable experience.

On the HTML preview - `Ctrl+M` for windows, when linking to other headers the links don't work

```
[Getting Homestead](#getting-homestead)
```

Should result in a link to the #getting-homestead header for example. Would be great to see this implemented. An improvement would be when hovering headers over on the Outline box it would display the correct hash link to use to link to that header.

Thank you for such a great writing tool.

**Comment by wereturtle** [comment]
It works fine if you are using Pandoc as the previewer.  Make sure the Markdown flavor you are using supports this linking style.  Some don't.  (The built-in one, Sundown, does not, I'm afraid.)

**Comment by 1e4** [comment]
Ahh, I assumed the default one would because.. it's default. Thanks for clarifying, is there no intention to support it on the default? It would make sense, not sure how many others don't know about it.

**Comment by wereturtle** [comment]
I didn't write the default one (Sundown).  Sundown is the one Github used to use before switching over to to their own CommonMark flavor.  As for Pandoc, since it is in Haskell instead of C/C++, it's harder to enfold it as default.  Sundown is really meant as a fallback in case Pandoc or MultiMarkdown, etc., are not installed.  Ultimately, it is up to the individual user to choose their preferred Markdown flavor.
