### ISSUE TITLE
Accented characters not in utf-8

### ISSUE THREAD

**Issue by aries26** [wereturtle/ghostwriter#286]
Using Windows 10, in the editor, I can input french accented characters.
After exporting to HTML, that file has charset=utf-8. But when displayed in Firefox, the accented characters are displayed as «?». After changing text encoding to Occidental in the browser, they are ok.

**Comment by wereturtle** [comment]
This is because the Markdown processor is not generating the HTML as standalone.  That is, the HTML doesn't have the opening `<html>` and `<head>` tags, along with the UTF-8 encoding specified in a `<meta>` tag.  Firefox isn't smart enough to figure out that the content is UTF-8 without that tag.  The export functionality is generally intended for snippets that you can plug into your own HTML page structure.  The app will pass the `--standalone` option to Pandoc by default so that this is generated for you.  However, other exporters (such as MultiMarkdown) lack this capability and will only generate snippets without the `<meta>` tag in the head of the HTML.
