### ISSUE TITLE
Doesn't save in UTF-8 with BOM

### ISSUE THREAD

**Issue by cdokolas** [wereturtle/ghostwriter#29]
Ghostwriter (v1.2.2, Windows) saves files as UTF-8 but without BOM. These files are then not being read correctly by ghostwriter. Converting a saved file to add the BOM fixes it (ghostwriter correctly reads the file), but the BOM is lost with every save.

**Comment by wereturtle** [comment]
That's an interesting error.  I'm afraid I can't replicate it on my own Windows box.  I can create and reopen all files in UTF-8 from Ghostwriter without any problems.  I've also used Sublime Text to export the same file in both formats--UTF-8 with the BOM and UTF-8 without the BOM.  Ghostwriter was able to open both files from Sublime Text.

What version of Windows are you using?  I'm on version 7.  I'm curious if you're on Windows 10.  This could be a Qt library issue where it works one way on 7 and a different way on 10.  I'm also assuming you're using the prebuilt Windows executable I provided, rather than your own build against your own Qt version.  Correct?

**Comment by cdokolas** [comment]
Indeed I am on Windows 10 and using the pre-built executable (via the installer).

Did you check that Ghostwriter saves the file **with** BOM? Also, did you try non-ANSI chars in the document? (from both Ghostwriter and Sublime) Just cross-checking your tests... thanks.

**Comment by wereturtle** [comment]
Good news!  I managed to replicate the problem on Windows 7.  It helps to put in foreign language characters into the file.  Duh.  I'm having one of those days.  But now at least you don't have to be my test guinea pig.  :laughing:

Oddly enough, Linux is just fine.  It's just Windows.  Hopefully it's as simple as setting a flag forcing UTF-8 when reading in the file.  I'll play around with it over the weekend.

Thanks for pointing out the problem to me.
