### ISSUE TITLE
Unable to build with Qt v5.10.0

### ISSUE THREAD

**Issue by dbelyaev** [wereturtle/ghostwriter#296]
While trying to build from `master` with the latest release version of Qt (at this moment: v5.10.0), I am getting strange error:

```
21:18:42: Running steps for project ghostwriter...
21:18:42: Starting: "/opt/qt/5.10.0/gcc_64/bin/qmake" /home/dmitriy/vcs/ghostwriter/ghostwriter.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
Project ERROR: ghostwriter requires Qt 5.2 or greater
21:18:42: The process "/opt/qt/5.10.0/gcc_64/bin/qmake" exited with code 3.
Error while building/deploying project ghostwriter (kit: Desktop Qt 5.10.0 GCC 64bit)
When executing step "qmake"
21:18:42: Elapsed time: 00:00.
```
Looks like it came [from](https://github.com/wereturtle/ghostwriter/blob/master/ghostwriter.pro#L21):
```
lessThan(QT_VERSION, 5.2) {
    error("ghostwriter requires Qt 5.2 or greater")
}
```

Strange behaviour as it determines that 5.10.0 is less than 5.2. Is there a possible bug in Qt's lessThan implementation?

**Comment by pablorodz** [comment]
Hi!
I had the same issue. I've changed that line to

versionAtLeast($$QT_VERSION, 5.2)

I don't know if that will work for qt4, I didn't test it.

Regards,
Pablo


El 11/02/2018 18:47, "Dmitriy Belyaev" <notifications@github.com> escribió:

While tyring to build from master with the latest release version of Qt (at
this moment: v5.10.0), I am getting strange error:

21:18:42: Running steps for project ghostwriter...
21:18:42: Starting: "/opt/qt/5.10.0/gcc_64/bin/qmake"
/home/dmitriy/vcs/ghostwriter/ghostwriter.pro -spec linux-g++
CONFIG+=debug CONFIG+=qml_debug
Project ERROR: ghostwriter requires Qt 5.2 or greater
21:18:42: The process "/opt/qt/5.10.0/gcc_64/bin/qmake" exited with code 3.
Error while building/deploying project ghostwriter (kit: Desktop Qt
5.10.0 GCC 64bit)
When executing step "qmake"
21:18:42: Elapsed time: 00:00.

Looks like it came from
<https://github.com/wereturtle/ghostwriter/blob/master/ghostwriter.pro#L21>:

lessThan(QT_VERSION, 5.2) {
    error("ghostwriter requires Qt 5.2 or greater")
}

Strange behaviour as it determines that 5.10.0 is less than 5.2. Is there a
possible bug in Qt's lessThan implementation?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wereturtle/ghostwriter/issues/296>, or mute the thread

**Comment by dbelyaev** [comment]
Thanks for this workaround! I will try it.

> I don't know if that will work for qt4, I didn't test it.
I don't think that it should be a big issue as application needs Qt higher than 5.2 in order to build.

**Comment by c72578** [comment]
> versionAtLeast($$QT_VERSION, 5.2)
> I don't know if that will work for qt4, I didn't test it.

Just for the records:
`versionAtLeast()` was introduced in Qt 5.10:
https://doc.qt.io/qt-5/qmake-test-function-reference.html#versionatleast-variablename-versionnumber
