### ISSUE TITLE
Build with Qt 5.10.1 was failed on macos.

### ISSUE THREAD

**Issue by ansidev** [wereturtle/ghostwriter#309]
I tried to build app with Qt 5.10.1 but failed. If Qt version is 5.5.1, it's ok.
How I can contribute release package for macos?

**Comment by dbelyaev** [comment]
@ansidev 

First of all, you can read README.md (available on main page of this repository) which explains why you will not be able to build ghostwriter with Qt higher than v5.5 (short: Qt developers removed QtWebKit from Qt SDK in versions higher than 5.5 which ghostwriter depends on). I´ll suggest you to read [this issue](#78) where main developer (@wereturtle) explains this problem.

There is also a section about help needed with MacOs packages in main README. I suppose you can contact @wereturtle if you want and can help with it.

**Comment by wereturtle** [comment]
Yeah, I'm aware of the issue.  I've been in quite a pickle for some time over the old QtWebKit library that has been replaced with the QtWebEngine library in newer Qt versions.  You see, Debian and Ubuntu didn't start even including QtWebEngine in the repos until very recently (and I'm on an LTS), so it makes it difficult to port for everyone still on an LTS.  As soon as I'm on the next LTS, I'll be able to begin the port.  Then I should be able to do a Flatpak as well (since the Plasma library for Flatpak also only has QtWebEngine) for those still on an older LTS.  Then you should be able to build on MacOS as well.

In the meantime, I recommend using Qt 5.9 and downloading the [QtWebKit build from annulen](https://github.com/annulen/webkit).  (The libraries for the latest release also seem to be working with Qt 5.10 as well.)  You should be able to drop in the MacOS library build, header files, etc. and get a build going.  This is my own strategy for the upcoming Windows release.
