### ISSUE TITLE
Pasting images from clipboard

### ISSUE THREAD

**Issue by Noomene** [wereturtle/ghostwriter#31]
I have tried tens of markdown editors ... and not one of them (except Zim and Marxico) supports pasting images from the clipboard. Is it really that hard to implement this extremely easy feature?

**Comment by wereturtle** [comment]
By "pasting images from the clipboard", do you mean pasting raw image data, or pasting a previously copied image file (i.e., to paste the path to the image on disk)?

If you mean the latter scenario, where you copied an image file on your file system and are expecting a URL to be inserted for you, I think I can arrange for that in the next release.  It was probably an oversight on my part.  In the meantime, you can drag and drop images from your file system into the ghostwriter editor, and it will automatically create the URL for you.

I would imagine that most Markdown editors aren't doing the former (pasting raw image data) because in Markdown, images are really links to a file location.  Since in this case you are trying to paste raw image data from the clipboard, the application wouldn't know where to put the URL to the file, since no file exists.  Software such as Marxico and even GitHub itself get around this by uploading the image data as a file to the server, and then putting a URL to the new file location on the server within the Markdown document.  It's rather awkward for a desktop application to do the same for you.  In what file format and quality should it be stored?  Or in which location should the image data be stored?

Also, Zim isn't a Markdown editor.  It's a WYSIWYG wiki text editor.  It resolves the issues I raised above by storing a newly created image within its wiki file system whenever you paste raw data into it.  Unfortunately, it's rather awkward with a Markdown editor, as Markdown is plain text.  It would be very unconventional to create a special file format that zips Markdown plain text alongside associated images created from pasting.  Most users expect plain text files that they can port anywhere.  The only feasible solution is to create image files on the fly in the same directory as or in a sub-directory to the Markdown document.  The image files would have to have random and unique names.  It would be ugly, especially if the user has multiple Markdown files in the same directory and pastes images into them all.  Plus, the image files might not even be in the user's preferred location.

Nevertheless, if you can further specify your requirements as to where exactly you would like the image files to be stored and in what format/quality, I'll consider adding it as a new feature.

**Comment by Noomene** [comment]
Hi wereturtle,

Sorry for the late reply. And thanks for your reply/

By "pasting images," I mean just that, i.e. "pasting images." Just simple copy/paste of an image like the "normal" good classic way of copying and pasting from the clipboard. In the case of a markdown editor that would be by saving the raw copied image locally, pasting the local URL instead, and then rendering the image in the preview.

I understand that Markdown obviously wouldn't paste raw image data in a file which is text based to begin with. Actually in my case Marxico does not do that by uploading an image file to some server (which I would hate because I want to be able to use the app anywhere even when there is no internet, which happens quite often). Marxico does it by simply saving the image locally to some folder structure of its own (it saves them in some weird folder in the "My Documents" folder). It would have been better if one had the ability to configure where he would wants it to save the file, but anyway, it works for now.

The quality of the image or which file type should it be stored under does absolutely not matter now, since all I want is to have my notes with the relevant images available to my eyes whenever I need them. Obviously the quality of the image should not be downgraded from the quality you see on screen, so a simple screen shot would be enough.

Actually in some other markdown editors what I used to do was to screen capture what I want from the screen using windows snipping tool then I save it, and then I copy the file local URL and put it manually in the app. I think this should not be that difficult to code into any markdown editor app.

> Unfortunately, it's rather awkward with a Markdown editor, as Markdown is plain text. It would be very unconventional to create a special file format that zips Markdown plain text alongside associated images created from pasting.

Why is it awkward? Why can't it just be such that one can configure where the editor puts his .md file then configure where he would like any **attachements** to that main .md file be stored. As you succinctly pointed out, this can be in the same folder by default without any need for zipping anything, ugly I agree, or in any other user chosen folder, not that ugly as the user is the one who chose it. The main advantage of markdown editors is simplicity and text format. So simplicity also says that one can simply attach any file he wants by drag and drop to the main text file in the form of a local URL and also paste any image which can then be stored locally to some local folder that the user may choose specifically for the purpose of pasted-image-storage.

So those were my remarks. Thanks again for your reply.
Presently I am using a new editor called **Typora**. It made me realize that the preview panel of most markdown editors was redundant. It previews on the fly, just like Zim. So I found it quite interesting and practical. There is another one which I am testing right now, it is called **abricotine**, quite buggy, but quite promising.

Anyway, would really love to test your app once you finish implementing what you said you would add.

Regards,

**Comment by wereturtle** [comment]
Thanks for getting back to me.  I kind of don't like the idea of having the user specify a default location on where to store pasted images.  A subfolder located in the same directory as the file being edited makes sense, until the user pastes into a new (unsaved) file.  That's where your idea of having the user specify a default location comes in.  But I still don't like it because (a) it doesn't make your file very portable to other machines and (b) the user will probably want the image to ultimately be located alongside the file they are editing once they save the file.  In case (b), the user would have to move the file to the desired location and then finally update the URL in their Markdown text to point to the new location.  With so much hassle, you might as well just have the user paste into an image editor first, save the image, and then drag and drop the image into ghostwriter.

I'll still keep the feature in mind, but if I get to it, it probably won't be anytime soon.

Thanks again for the feedback, and good luck with the other editors you are using.

**Comment by Maggew** [comment]
How do I paste an image from clipboard?

So for example, I hit PrtScr or just navigate on web and (R) click > copy and paste into ghostwriter.

**Comment by orschiro** [comment]
@Maggew as of the comment above, this feature is not supported.

**Comment by Maggew** [comment]
You read those comments? All I can remember was seeing a giant wall of 
blurry text at like 4AM. Thanks for the heads up and GLHF!

Robert Orzanna wrote:

**Comment by rbajaj1997** [comment]
Hi @wereturtle, any chance we can have this feature? ReText (another markdown editor) supports this feature. Basically, if we have an image copied in our clipboard, we can paste the image directly and the application will ask for a location to save the image. 

The flow looks like this right now:
1. Have an image in the clipboard.
2. First save it in the system.
3. Then drag and drop it inside the application.

A more convenient flow:
1. Have an image in the clipboard.
2. Come inside the application and press Shift + Ctrl + V. 
3. A window opens up asking for a location to save the image and post that links it in the document.

This way we don't have to leave the application at all. What are your thoughts on this?

**Comment by RiedleroD** [comment]
could this be achieved by inserting inline base64 images? It can already be done with either 
`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
  //8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==">` 
or just 
`![]("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
  //8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==")`

In both cases, the image of a red dot is displayed correctly.

**Comment by wereturtle** [comment]
@RiedleroD That would be extremely huge for anything larger than a red dot.  I don't think most people would want to work with a document that cluttered.
