### ISSUE TITLE
HTML preview doesn't work with tabbed lists more than five layers deep, consolidates layers with spaces?

### ISSUE THREAD

**Issue by will-ca** [wereturtle/ghostwriter#344]
### Text:
```
* This
	* Is
		* A
			* List
				* With
					* Five
						* Layers
					* Like
				* So

* This
 * Is
  * A
   * List
    * With
     * Five
      * Layers
     * And
    * Spaces
```

### Result:

![image](https://user-images.githubusercontent.com/37680486/41249888-3852a86a-6d6a-11e8-8b80-4beab0d7bca8.png)

**Comment by wereturtle** [comment]
Hi,

For the first example, a lot of what you are seeing is because you are using the built-in Markdown processor, Sundown.  Installing Pandoc or MultiMarkdown will produce different results, more in line with what you are expecting.

Regarding the second list example, official Markdown typically requires at least 2 spaces for a list item to be considered an indented sub-item in a nested list.  One space is not sufficient, and the item will be considered to be in the same "level" as the preceding item in the list.  Sundown tends to bend or break some rules, which is why you see a few of your list items being indented.  However, Pandoc, MultiMarkdown, and especially CommonMark will be more strict.
