### ISSUE TITLE
[Various Enhacements]: To fork or not to Fork

### ISSUE THREAD

**Issue by pazos** [wereturtle/ghostwriter#355]
@wereturtle: after a few hours of reading the code (mainly to add proper support for macOS, and also to add support for linux appImage) I came with a few things that can be interesting for the project.

- Switch from sundown to [hoedown](https://github.com/hoedown/hoedown), which has some nice features and would be great to export to other formats (like pdf via latex) without relying on pandoc. Instead of copy-pasting the code in this repo I would fork it as another repo and add it to ghostwriter as a submodule (to keep track of the changes). 

- Deploy qt translations as part of the program deployment. Forking [qttranslations](https://github.com/qt/qttranslations) and including it as a submodule will allow us to bundle fresh translations (which is great for new languages support). Then we can automate the builing of translations (qt, qtbase and ghostwriter) for the user frictionless experience.

- Use a translations web framework, like transifex or pottle to allow unexperienced people to contribute with ghostwriter translations.

- Add rules for platform deployment (that means use windeployqt/macdeployqt and other helpers scripts, like [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) as part of the building & deployment stage.

All those features can be implemented in a few hours of work, but after reading the contributing guidelines I'm not sure If you are willing to support all those changes on the codebase because you're lacking the time.

My idea is to contribute back to the project, not creating a new one, but if you think that all those features won't get merged I would go for creating a new repo, forget about atomic PRs and keep it as tidy as posible for you (and others) to pull changes if you wish.

Some feedback would be great.

**Comment by wereturtle** [comment]
Thanks for your input.

> Switch from sundown to hoedown

I've picked Sundown because it isn't a moving target, which makes it easier to support.  I may add hoedown as an additional option in the future.

> Deploy qt translations as part of the program deployment. Forking qttranslations and including it as a submodule will allow us to bundle fresh translations...

Yes, it's somewhere on my to do list to pull in what FocusWriter is doing with its project file, which includes auto-building the translations with each call to qmake/make.  However, I don't want to maintain a fork of qttranslations, as these must match the version of Qt with which you are deploying.  Also, Linux users will already have qttranslations in their repos.  For Windows, I started by just bundling the qttranslations that came with my local Qt install with ghostwriter.  I'm sure we could do the same for MacOS.

> Use a translations web framework, like transifex or pottle to allow unexperienced people to contribute with ghostwriter translations.

That sounds interesting.  I wouldn't mind even someone else setting that up for everybody.  As long as the end product I receive in a pull request is a Qt Linguist file, I'm good.

> Add rules for platform deployment (that means use windeployqt/macdeployqt and other helpers scripts, like linuxdeployqt as part of the building & deployment stage.

I don't mind that.  I tend to run my own scripts and goodies for things like PPA/.deb bundling.  I've also finally got a Flatpak manifest working (whew!).  And it's got all the Markdown processors bundled with it! 
 Woohoo!

But like you said, I don't have a lot of time.  For Windows, I am hoping to pass the torch to someone else within the next few years.  But first I want to get MSVC compiling okay so I can leave things in a good state (QtWebEngine can only be used with MSVC in Windows).  I don't have plans to upgrade to Windows 10.  If my hard drive having Windows 7 dies, that's it for Windows builds for me.  I'm also finding it harder and harder to support Windows 10 users when I can't replicate issues on Windows 7.

For the long term, I'd love it if we could get some CI going for Windows builds (again from a volunteer).  Hopefully as Flathub matures I can likewise get some nightly Linux builds going.  It's a bit of a pipe dream right now, but I welcome volunteers to work things like this out.

So, yes, if you want to volunteer for build support stuff, I definitely wouldn't mind.

**Comment by pazos** [comment]
> I've picked Sundown because it isn't a moving target, which makes it easier to support. I may add hoedown as an additional option in the future.

Great pick, but Hoedown is sundown + bugfixes + better API. Both rendenders can coexist but we need to tweak include paths and headers' name to avoid building clashing. So my first idea was replace one for the another.

> However, I don't want to maintain a fork of qttranslations, as these must match the version of Qt with which you are deploying.

Not really, qtbase translation should be forward compatible within major QT versions.

> I don't mind that. I tend to run my own scripts and goodies for things like PPA/.deb bundling

Yeah, sure. For linux some scripting is good 👍 , but users willing to build from source on mac/windows would expect some sort of "runnning everywhere" magic executable after hitting make :p

> For Windows, I am hoping to pass the torch to someone else within the next few years. But first I want to get MSVC compiling okay so I can leave things in a good state (QtWebEngine can only be used with MSVC in Windows). I don't have plans to upgrade to Windows 10. If my hard drive having Windows 7 dies, that's it for Windows builds for me. I'm also finding it harder and harder to support Windows 10 users when I can't replicate issues on Windows 7.

I hate MSVC :P, I rather prefer to spend hours trying https://github.com/annulen/webkit


Finally, If you wish to see my progress on those tasks you can give it a try on this branch. https://github.com/pazos/ghostwriter/tree/ghostwriter-next

It has submodules implemented for qttranslations, hoedown and hunspell, automatic translations building (inside the app binary) and simpler logic for installing translations. I've also replaced sundown for hoedown and a few other things, which now I don't remember. If you are willing to merge *some* of this changes upstream then I can make a PR (and close the mac supporting one, because it is superseeded).

**Comment by pazos** [comment]
On a side note, with the actual implementation of hoedown it should be easy to export markdown as latex/pdf. Just need to merge [this PR](https://github.com/hoedown/hoedown/pull/189) in hoedown and use [texcaller](https://github.com/vog/texcaller) to interface with latex commandline tools (if they are installed).

We can even add support for rendering math equations/plots via [scidown](https://github.com/Mandarancio/scidown). Options: merge changes on [this PR](https://github.com/hoedown/hoedown/pull/222) in hoedown or add scidown as a separate renderer.

**Comment by wereturtle** [comment]
> Great pick, but Hoedown is sundown + bugfixes + better API. Both rendenders can coexist but we need to tweak include paths and headers' name to avoid building clashing. So my first idea was replace one for the another.

I took a quick glance through your ghostwriter-next fork.  It looks like you've pretty much got Hoedown "down".  Since you've already done the work, I wouldn't mind replacing Sundown with it.  It's probably not worth it to keep Sundown around.  Most people would just end up picking Hoedown.

> Not really, qtbase translation should be backwards compatible within major QT versions, so we're good bundling 5.11 translations even with an app built against qt5.5

Better safe than sorry.  Believe me, new Qt versions always do something to drive developers mad.

> I hate MSVC :P, I rather prefer to spend hours trying https://github.com/annulen/webkit

I feel your pain, and share your hatred of MSVC.  The stupid MSVC linker can't link Hunspell without the header files.  Gaaahhhhh!!!!!  Easy fix, but figuring out what it was really complaining about took a while.

> Finally, If you wish to see my progress on those tasks you can give it a try on this branch. https://github.com/pazos/ghostwriter/tree/ghostwriter-next

I took a quick look.  Nice stuff in there.  However, I'm not sure I want to import external Github repos.  I'd prefer to just keep a snapshot of Hoedown/Hunspell/etc.  That way we are not dependent on Github for a `git clone` in case it goes down or I choose to switch to a different code hosting service.

I think for now it would be best to maintain a separate fork, and do small, atomic pull requests.  That will make it easier for me to review.  So maybe after the MacOS updates are in, the next pull request you could do would be just for Hoedown, and then maybe the next one for deploy scripts, etc.

**Comment by wereturtle** [comment]
Sorry, but I had a second thought concerning Hoedown.  It looks like the roadmap for Hoedown is a rewrite to be CommonMark compliant.  My concern with that is there might be users out there relying on Sundown's own syntax flavoring, and replacing Sundown with Hoedown and eventually updating to this future Hoedown with result in those users showing up with pitchforks and torches on the issue tracker.

I know, the odds are astronomical, but it really wouldn't surprise me if one user's document written in Sundown ended up breaking in the future CommonMark-compliant Hoedown.

In which case, I think it's best to have the two live side-by-side in harmony.  We can make Hoedown the new default, and leave Sundown as backup for the hopefully rare user who needs that Sundown-flavored syntax.

**Comment by pazos** [comment]
Yes, sure, hoedown has a few quirks. I've noticed some differences in rendering vs sundown. Not really shady issues, but differences. I like the idea of keeping sundown as the default render (and leave ghostwriter backwards compatible) and add new implementations later on. I did some progress exporting latex from hoedown and would love to have that feature in the future, but there are a lot of ways to do that.

> I'm not sure I want to import external Github repos. I'd prefer to just keep a snapshot of Hoedown/Hunspell/etc. That way we are not dependent on Github for a git clone in case it goes down or I choose to switch to a different code hosting service.

Fair point. I love submodules as a way of organizing large projects and keep repos tidy. But I'm fine without pushing those to ghostwriter. 😄 

I am going to close this issue, since I see that you are open to merge new stuff, I will open specific issues/enhancements instead, one by one :p
