### ISSUE TITLE
Feature request: browse local files.

### ISSUE THREAD

**Issue by DeadEarnest** [wereturtle/ghostwriter#365]
- It would be a big help, if ghostwriter allowed to link local files to each other and browse between them.
- Even bigger help, if .md files would open as interpreted .html.

Right now I can reference local file and open it (.md shows as raw text), but I can not go back to the file that contains the reference.

BTW, I use ghostwriter for manuals at work, great work, keep it coming!

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.

**Comment by fresheneesz** [comment]
Please reopen this. This is an incredibly important feature to me. I'm looking for a good open source markdown editor to use and recommend to others, but this is a required feature for ease-of-use reasons. I'm currently using Typora, however that will eventually be a paid-for program and thus harder to recommend in the context of an open source set of guides. 

I would highly recommend you change your policy of closing feature requests. This is incredibly discouraging to people who want to help this project with their ideas (eg people who can't help by implementing features). I would recommend instead that you mark things like this as "future" or something like that instead of closing them. For people who can implement things (like me), it would be nice for them to be able to see a larger set of features than what you have prioritized, so they can choose the tasks they find most interesting.
