### ISSUE TITLE
No export with pandoc in newest release & no program start possible when using the installer

### ISSUE THREAD

**Issue by merlinuwe** [wereturtle/ghostwriter#366]
Hi, 

I recently installed ghostwriter 1.7.0. It works only from the zip-file, not from the installer (it does not start).

And I cannot export to html when I use any of the pandoc converters.

The error message:

```
Export ist fehlgeschlagen.
[WARNING] This document format requires a nonempty
```

As you see, pandoc is in the path:

```
Microsoft Windows [Version 10.0.17134.167]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\abc defg>pandoc -v
pandoc 2.2.2.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Default user data directory: C:\Users\abc defg\AppData\Roaming\pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

What can I do to solve these issues?

Greetings,

merlinuwe

**Comment by wereturtle** [comment]
Hi @merlinuwe 

I've patched ghostwriter to not show warnings from Pandoc as error dialogs.  Please download the new v1.7.1 release, and you should be good to go.

Regarding the installer, I'm afraid there's not much I can do about it, since I'm on Windows 7 and cannot replicate Windows 10 issues.  But at least the portable version is working for you.
