### ISSUE TITLE
Deny JS execution on HTML preview!

### ISSUE THREAD

**Issue by finex** [wereturtle/ghostwriter#376]
Hi,  I've found a problem which could have some security implications.

**Problem:**
Ghostwriter currently executes JS code when the HTML preview is active. 

**How to reproduce:**
Just put some JS code on the same line (without the code delimiter like \` or  \`\`\` ) like:

```
<script>alert('hallo');</script>
```

I'm currently not aware about malicious JS code which could exploit this bug, but I've uninstalled ghostwriter because I'm not feeling safe.

Regards.

**Comment by RealOrangeOne** [comment]
Due to the fact it's rendered in a pseudo-browser, there's no filesystem etc access, which is brilliant from a security standpoint. The vulnerability scope is limitted to that of running arbitrary javascript in an incognito browser window, ie _very_ little. 

I do however agree it should be fixed, asap. But i don't think it's enough to warrant uninstalling.

**Comment by optimaldc** [comment]
> Due to the fact it's rendered in a pseudo-browser, there's no filesystem etc access, which is brilliant from a security standpoint. The vulnerability scope is limitted to that of running arbitrary javascript in an incognito browser window, ie very little.

It's still quite awkward. For example, you might be able to send secret stuff via HTTP:
```
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script><script>$(document).ready(function() {$.get("http://ifconfig.me/", function(data) {alert(data);});});</script>
```

**Comment by wereturtle** [comment]
ghostwriter only puts in JavaScript into the browser preview if you yourself put JavaScript into your Markdown.  You're only as safe as the JavaScript that *you* choose to run.  It won't execute JavaScript otherwise.  You have to go out of your way right now to deliberately put in script tags that will execute malicious code.  Just don't put in your own malicious JavaScript between `<script>` tags, and you'll be perfectly safe.

Most people would consider it a nice feature to be able to preview their JavaScript.  It's up to you to use JavaScript, or not use JavaScript.  Also, as RealOrangeOne said, the browser preview has zero access to write to your hard drive.

**Comment by optimaldc** [comment]
> ghostwriter only puts in JavaScript into the browser preview if you yourself put JavaScript into your Markdown. You're only as safe as the JavaScript that you choose to run. It won't execute JavaScript otherwise.

This is not entirely true. What it opens is a way to execute JavaScript on someone else's machine (if they use ghostwriter and you know it) by sending them a Markdown-file containing the script. Especially with very large Markdown-files it's quite hard to detect this malicious code inside. You and RealOrangeOne still have a point and we have to take into account that it's a very, very niche way to get someone to run your script, and more than likely there are much better ways to get someone to run it, but it's still a way. We also must remember the potential attacker knows the limitations of the browser preview and has unlimited amount of time to try and break through it before actually sending out a bad file to someone.

I would suggest you consider either of the following:

1. Add a warning prompt (yes/no) before the live preview executes JavaScript from files _you open_ (not when you yourself write it).

2. Add a checkbox-option to enable / disable JavaScript.

Just my two cents. Great job on ghostwriter @wereturtle, it's the best Markdown-editor I've used!

**Comment by wereturtle** [comment]
Sorry, but such a patch is not going to happen.  The upcoming transition from WebKit to Chromium will feature React to help changes to large documents to render faster.  Having a prompt (provided I can even integrate tightly enough with WebKit or Chromium to detect JavaScript and selectively disable scripts) would be very inconvenient in the development of this feature.  Like you said, it's a niche scenario.  Don't open strange Markdown files.  It's as simple as that.  For extra security, set a plain text editor such as gedit or Kate to be the default for Markdown file extensions.  And if you really want to be secure, then for the love of Tux, don't use Windows!  :laughing:

**Comment by optimaldc** [comment]
> The upcoming transition from WebKit to Chromium will feature React to help changes to large documents to render faster.
Sounds like we can do a fun challenge. Once you are finished with a release version of the Chromium & React -update and someone is able to create a Markdown-file that gains access to a computer through ghostwriter, will you add a solution for this? 😉 


>  And if you really want to be secure, then for the love of Tux, don't use Windows!
+1 for this 😆
