### ISSUE TITLE
[Debian packaging] Resource files need clearification on license

### ISSUE THREAD

**Issue by gloomy-ghost** [wereturtle/ghostwriter#385]
under resources/images/:
close-hover.svg, close-pressed.svg, close.svg are not listed in COPYING

actually, since you own the copyright, can you relicense the assets under CC BY-SA 4 which is [compatible](https://creativecommons.org/2015/10/08/cc-by-sa-4-0-now-one-way-compatible-with-gplv3/) with GPL 3? There are also assets licensed under LGPL, so relicensing them using the same term cleans the copyright structure.

One more thing, since hunspell is tri-licensed, I suppose (IANAL applies) we can just choose one license to comply with, which means this project only needs to include the GPL declaration.

This seems to be a blocking issue for the package to enter Debian. I can submit a PR if you don't have time to do it, as long as you (who holds the copyright) declares that it is effective.

**Comment by wereturtle** [comment]
Hi @gloomy-ghost 
I've updated the license to CC BY-SA 4, and have ensured that the close buttons are included.  The Hunspell source code is only included for building with Windows.  Technically, you don't have to pull that part of the bundle in for Debian.  I think I'll just leave the license as is for that, since I like to respect the original license that came with it.  But, if it's still an issue, let me know, and I'll update it.
