### ISSUE TITLE
Math "\frac" command doesn't work in preview-pane via pandoc

### ISSUE THREAD

**Issue by 07ac365bcb** [wereturtle/ghostwriter#391]
Hi,

I'm having troubles showing math equations in the preview-pane. I'm using Ghostwriter 1.7.1 on Windows 7 and 10. I installed pandoc 2.3.1 and selected "Pandoc" in "Settings --> Preview Options".

**Example 1: LaTeX command \frac not working**
I strongly assume that there are other commands that don't work.
- Input: `$$\frac{1}{2}$$`
- Output: `Export fehlgeschlagen:[WARNING] Could not convert TeX math '\frac{1}{2}', rendering as TeX`
- Screenshot: ![grafik](https://user-images.githubusercontent.com/44701483/47915576-9c699200-dea3-11e8-9f57-174148aca809.png)

**Example 2: No problems with some other math operators**
I also checked the code snipped from issue #81, which does not throw an error message.
- Input: `$$\Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt$$`
- Output: Works as intended, even though the integral sign is too small and the upper and lower bounds are not aligned correctly.
- Screenshot: ![grafik](https://user-images.githubusercontent.com/44701483/47915703-fcf8cf00-dea3-11e8-9e41-e0eed962b96a.png)

**Question:**
Am I doing something wrong? How to display math in preview-pane?

**Comment by wereturtle** [comment]
I'm not sure.  You might be missing an installed module.  (Or I am, because I don't the the error message in the preview pane, but I also don't get an equation, either.  But I do see the second equation fine.)

It also might be something with Pandoc.  ghostwriter only uses a very basic command line for Pandoc, so I doubt that ghostwriter is the issue, per se.  Now, there might be a parameter that Pandoc wants that ghostwriter isn't providing.  If you find out that's the case after going through the user manual, let me know, and I'll consider a patch.

**Comment by daacosta** [comment]
This formula didn´t work either:

\underset{\vec{x}}min{f(\vec{x})}:\Re^N\rightarrow\Re

**Comment by wereturtle** [comment]
FYI, I've used the `--mathml` option as a fix instead of `--mathjax`, as mathjax requires the `--standalone` option to properly render the equations.  For the live preview, the copy HTML button needs to copy the HTML snippet, not a fully-formed, standalone document, for sake of pasting into blogs.
