### ISSUE TITLE
Hyphen is displayed as an en-dash in HTML preview pane

### ISSUE THREAD

**Issue by Kzer-Za** [wereturtle/ghostwriter#396]
The issue is observed only between two figures and only if you select MultiMarkdown as Markdown Flavor in "Settings -> Preview Options". But under these conditions it's there, see the attached screenshot. Compare the left pane and the right pane: if a hyphen is between two figures, it is indistinguishable from an en-dash.

![2018-11-19_20-11-45](https://user-images.githubusercontent.com/26425206/48723854-cc9d8880-ec38-11e8-8bb7-5d4dbdb64075.png)

**Comment by wereturtle** [comment]
This is likely because the smarty pants option for MultiMarkdown is turned on by default in the preview, which would automatically convert the double hyphens to a single dash.  I personally would like to leave it this way, because most people would probably want smarty pants turned on.  I would suggest doing escape characters to ensure the hyphens stay intact, like so:

    https://en.wikipedia.org/wiki/5\-\-4\-\-3_rule
