### ISSUE TITLE
Incorrect opening of links

### ISSUE THREAD

**Issue by jeff9315** [wereturtle/ghostwriter#424]
In a document named _main.md_, I have a link such as this in my document: ``* See [Travel Issues](./Travel-Issues.md))``. When I click the link in the HTML Preview of _main.md_, it takes me to the source code of the _Travel-Issues_ document within the HTMl preview pane and no way to get back to the HTML preview of either _main.md_ or _Travel-Issues.md_.

**Comment by wereturtle** [comment]
Sorry, this is really a limitation with WebKit (and likely Chromium as well whenever I get around to porting to it).  In order to allow browsing between anchor tags in the same document, I have to allow some local file browsing.  Ditto with allowing the inclusion of local JavaScript and CSS files.  To get back to where you had been, simply type something in your normal document, and the preview will update.
