### ISSUE TITLE
Better use of screen real estate

### ISSUE THREAD

**Issue by jggouvea** [wereturtle/ghostwriter#44]
Have been using Ghostwriter for weeks. Used it to finish a quite long novella (40,000 words).  My experience has been generally good (in fact Ghostwriter already is the best Markdown editor I ever used), but I'd like to add make some suggestions about usability:

1. Ditch proportional fonts,
2. Do not offer width options,
3. Redivide screen real estate,
4. Improve and move statistics,
5. Add an option for blockquotes,
6. Document the theme file format,
7. Menu collapsable in F11 mode.

Of course, you are free to disregard all of them (I will still use Ghostwriter), but if you talk to other authors about their opinion, perhaps you'll find that some of my suggestions are popular among them.  Anyway, I'll present my arguments to defend my views:

# Ditch proportional fonts

Proportional fonts are an eyesore when you are working with plain-text files, like Markdown. Most people editing such documents will gladly accept a good default "typewriter" font.  I have downloaded and installed a font called "Ttyp", which is really beautiful at 18 point size. It is clear, readable, beautiful and helps me read faster.

Another downside of working with proportional fonts is that your font selector dialog becomes clogged with meaningless (and often useless) fonts. A user may have some fonts installed because he needs them for other tasks, they don't need to appear on a text editor's menu.

# Do not offer width options

People editing Markdown files don't want much options.  Markdown is a format for people who want a KISS approach.  A good Markdown editor is one that does not stand in the way of writing *content*.

Texts with very long lines are tiresome to the eye.  So are texts with very short lines.  On average 60 characters wide is a good measure (per Bringhurst's *Elements of Typographical Style*).  I have written this text on a 60-char wide window. 

If you think proportional fonts should not be ditched, a measure of 60 em would be a good default.

# Redivide screen real estate

If you stick to a standard measure, you can consider the possibility of creating a fixed window division in three columns, like this:

    +-------------------------------------------------+
    |         |                             |         |
    | Outline |  Main screen area:          | Dynamic |
    |  (HUD)  |  Where text is shown.       |  Space  |
    |         |                             |         |
    |         |                             |---------|    
    |         |                             |  Clock  |
    +-------------------------------------------------+
    
The outline (which is already clickable) must be shown by default because it is very useful to organise the text.  When you reduce text width and make the outliner visible,  the user is stimulated to work in a structured way, which is good.  Remember:

> The user should be guided to better practices.  A program like Ghostwriter is already intended to create such a culture of structured, focused editing.  It is nice to provide tools to improve the user's workflow in ways that the user, perhaps, didn't even foresee.

The cheat sheet is useful, but should remain a separate window, like the preview.  The users don't need to keep seeing it all the time.

The "dynamic space" is an area whose context will change as the user works and changes are made to the document.  I think it would be interesting to have there the following bits of information, like the statistics.

Finally, a clock showing the system time, to the bottom-right side of the window.  As the user may be working on full screen mode, the taskbar clock will not be visible.  The necessity to exit full screen to see the time would be distracting.  Having the clock right there fixes this.

# Improve and move statistics

The "dynamic space" would be filled by statistical information like the following:

1. File created on dd/mm/yyyy
2. File previously edited on dd/mm/yyyy
3. Current word count
4. Current character count
5. Estimated page count (I can help you develop an algorithm for this, if necessary)
6. Session active for HH:MM since HH:MM today/yesterday
7. Words written this session
8. Words written to this file in this session
9. Sessions editing this file

Since you can't save this information to a plain-text file (not without making it invalid Markdown), the way to go would be creating an auxiliary file, like Vim or LaTeX do.   Ghostwriter already creates a .bk file, to have an extra .dat file would be no real issue.

I believe this suggestion, being the most useful, is sure to be the most challenging too.  I have no idea how you could do these things, I only think they'd be great to have.

# Add an option for blockquotes

The three styles available are already good, but why limit our imagination?  There is another viable option that would add visual appeal to the program:  indented blockquote. 

An indented blockquote is one that uses screen space to set the quote apart from the block text.  Like this:

>        This is an indented blockquote.  The blockquote 
         mark remains visible at the left, but the actual     
         text is added a wider inner margin to the left  
         side, making the quote more similar to a formatted 
         quote in a book.

I don't know how well GitHub will display this blockquote, but it looks Okay on GhostWriter, if you have the medium width set.  I had to add manual linebreaks to create the layout, though.
        
# Document the theme file format

Since GhostWriter comes with only two themes built-in (which is neither good nor bad *per se*), users should be stimulated to create and share their own themes.  I have already guessed something about the file format and created some themes using the GUI, but documenting the theme file format would allow more tech-savvy users to convert existing schemes for other programs, providing GhostWriter with more visual candy. 

# Menu collapsable in F11 mode

Since you claimed to have drawn inspiration from Focus Writer (which I don't particularly love), I guess you know what I mean: there's no need at all to have the menu bar visible when the user is working on full screen mode (F11). Hiding the menu would help the user have a cleaner ambient to work.

-----------------

Finally, I would like to thank you for your work on GhostWriter, which has been so useful to me. Keep your good work.  And when the website is ready, don't forget to add a PayPal button there, 'cos I'll send some modest retribution.

**Comment by wereturtle** [comment]
Hi,

Thanks for the input.  I'll address each of your points below.

# Ditch proportional fonts

Not sure what you mean.  I set the editor text to have a default typewriter/monospace font.  Other than that, you can go to Settings->Fonts to change the font to anything you want, including variable width ones.  You mentioned the menu fonts are also proportional, but I never set those to be so.  On the multiple computers I have this installed on, the menu fonts (as well as the Outline HUD fonts) are using whatever the OS system font is.  There seems to be something off with your Windows system settings if it's falling back to a proportional system font.  Unfortunately, I have no idea how to fix that for you without access to your PC to investigate further.

As far as removing all proportional fonts altogether as an option for the user to use, I love proportional fonts, since I can align my tables and view my code snippets really nicely.

# Do not offer width options

That was inspired by Byword.  I had originally experimented with making the width options based on character width.  For example, I had the Wide option to be 80 characters wide.  But I found it became inconsistent when the font size changed.  Suddenly a larger font would fill the whole editor, with no margin space available.  A small font size would make it a very narrow column of text indeed.  For consistency's sake, I went with percentage of the current monitor's width to determine the width option sizes.  Since I actually do use the different width options, it's here to stay.  I especially use the Full width option when working with To-Do lists.  I guess different people like different features for their workflow.

# Redivide screen real estate

I feel the HUD windows solve this, since you can place them anywhere.  You can drag them from their title bars to move them.  You can also press the X button to close them.  I was inspired by several Mac OS X Markdown editors that make use of different HUDs for displaying information and letting the user decide where they go and whether they are displayed.

# Improve and move statistics

This is an idea I've been playing with for a while.  I've been planning to put some statistical information in another HUD window.

# Add an option for blockquotes

See Format->Block Quote from the menu bar.  (Maybe you were using an old version that didn't have that yet?)  It will insert the block quote character for you.  You can also press `Ctrl+.` to insert it.  Finally, you can select multiple lines of text and use either this menu option or its shortcut key to turn all those lines into one big block quote.  If you ever want to strip the block quote formatting, use Format->Strip Block Quote on the current line where the cursor is, or on the selected lines of text.

FYI, look into that Format menu bar for other features.  There are a lot of cool shortcut keys listed there that I think you'll like.

# Document the theme file format

Good idea.  I'll have to get around to that.

# Menu collapsable in F11 mode.

This is harder than it sounds, if you want to do it correctly and polished.  I've seen some editors hide the menu bar, only to mistakenly remove the keyboard accelerators (i.e., valuable shortcut keys) associated with it by doing so.  Oops!  We don't want that.  It has to truly be invisible, with the accelerator keys plugged in.  I had also originally prototyped this in the early days of creating the tool, and decided that making the menu bar transparent with faded text would be the better option.  Apparently, it's still not working for everybody.

After another user requested this feature, I spent quite a few hours last week tinkering with and analyzing how to go about implementing it in the current framework. In order to do it in a very polished manner (which I would prefer to do, as it is the right way to do anything in life), it's going to take much more work than I have time for. This is because if I add this feature, I really, really want it to auto-fade the menu bar in and out (animated). This effect should happen as follows:

1. The user stops typing after a few seconds (fade in menu bar - tablet friendly)
2. The user resumes typing (fade out menu bar)
3. The user hovers the mouse over the menu bar area (fade in)
4. The user removes the mouse from the menu bar area (fade out)
5. The user activates a keyboard accelerator (fade in)
6. The user completes selecting menu option via keyboard (fade out)

On a technical level, I have to rearrange how the background color is applied on top of any background image in order to make this work. I also need to daisy chain the graphics effects (from QGraphicsEffect). That means making a QGraphicsEffect derivative that can apply multiple effects, since only one QGraphicsEffect can be applied to a widget at a time. This means in order to retain the drop shadow effect on the menu text, in addition to adding the fade effect, I would have to implement the drop shadow effect from scratch, rather than use the Qt library.

Sure, I could drop the entire fade animation and just set the text to transparent while removing the drop shadow effect, but that is not nearly as polished. I see it more as a band-aid solution. Regardless of how I go about it (band-aid or polished), the above use cases still apply, and will take time to thoroughly test.

The truth is, I already have a day job, and am about to start working a lot of overtime for quite some time. This feature is probably not going to happen, at least so long as I don't have any additional volunteers to help.

Since you are the second person to request this, I may consider doing it the "band-aid" way with no fade effect.  I'll be sad, however, that it won't appear as polished as it deserves to be.

I do agree that a clock would be nice, but ironically since I have the focus button and the full screen button in the lower right corner, I would end up putting the clock on the right side of the menu bar.  :laughing:  Don't worry, I can figure out how to not make it disappear, so long as I never introduce a fade effect to the menu bar.  I just worry that it will still distract the user if I put it there.  In which case, perhaps the lower left corner would be better?  What do you think?  I like where the buttons are in the lower right, and I probably won't move them.

Personally, I just keep a physical clock nearby when I write in full screen mode, or set a timer if I need to stop at a certain time.  But to each their own.

**Comment by wereturtle** [comment]
P.S.  Congratulations on completing your 40K-word novella!  That's quite an accomplishment, and I'm glad to hear that my little application did the job for you, even if it needs a few edges ironed out.

P.P.S.  Which version of Windows are you using?  I am wondering if a possible discrepancy in versions could be what is causing your monospaced font issue in the menus.  I'm still on 7, and I won't be upgrading to 10 anytime soon.  All the menus for me on 7 looks like the default OS font.

**Comment by jggouvea** [comment]
I am not using Windows, I use Debian Jessie. I compiled the cloned repository and installed it... :100: 

As I said before, I made my comments only to document my perceptions. If more people comment, you have a better guess of what your user base feels about the program. I expected that most of my remarks would be useless, impractical or misguided. Just remember that, as I said, the program is already very good and I don't plan to use another. The suggestions just hint at things that might make it better.

# Proportional fonts 
As for proportional fonts, perhaps there was some noise in communication. I mean fonts like Arial or Times, not like Courier. Monospaced fonts look and feel better when you are working with plain text (imo). There are some programs (even Qt programs) that won't consider proportional fonts. The suggestion was made to sanitize the font menu, which is huge.

# Width options
You clearly have a point. So long as the program still offers the medium option I liked, that's ok. 

# Screen real estate
The suggestion about widths was made foreseeing that if you fix the layout some way, then there's empty space available to put more content. The floating HUD is great, but it covers the text if you work in full-width mode, for instance.

# Blockquotes
I just suggested a fourth style, one closer to printed books.  You only have three options: plain, italic and fancy. Neither adds a wider left-margin.

# Statistcis
Probably very difficult and requiring a separate data file, but very much worth it. Consider it carefully.

# Menu collapsable
Most distraction-free editors don't even have a menu. If you can't have it collapsable, why don't you just hide it for good, or replace it by an icon at the corner, like Firefox does?

# Clock and Focus
The clock can be anywhere. It can even be shaded (to be highlighted on mouseover). 
My suggestion is that you could go full-screen, without anything to distract you, and just have a clock to know whether its' time to stop. If you think the lower right corner is not the best place, why don't you just put them with the statistics? Tip: the clock mustn't have seconds. Their movement would be distracting. Just hours and minutes.

And thanks for the congrats... Let's hope I win some literary prize with it.

**Comment by wereturtle** [comment]
Ah, some miscommunication on the fonts.  I was still just waking up when I started talking proportional fonts, and my brain got mixed up.  Some users seem to like having them over monospaced fonts.  (Sometimes I use them too depending on the mood, but I mostly use monospace.)  Glad everything is working for you on Debian.  I'm on Mint myself, and will probably jump to Ubuntu MATE in April.  (Beta testing it in a VM as we speak.)  I hope getting all the right dependencies to link against didn't cause you too much trouble.  It's on my to-do list to update the README file to list them all.  The QT svg and printsupport libraries come to mind.  They're tricky if you don't have them on your machine, because the app will compile and link without them fine, and even run, without complaint.  It just won't show certain buttons, like the fullscreen button or HUD close buttons, and it won't print your documents.

Yeah, the HUD can cover text, but I also worry that adding panels will squish the text to be off center from the screen.  I like my text to be dead smack in the middle of the window.  It's a trade off, to be sure.  That, and I had a moment of Mac envy, since all the very pretty Markdown editors seemed to be for Mac OS X.  We can't have that, now can we?

As for block quote indents, I would love to add them, and I had prototyped that extensively trying to get it right.  Unfortunately, there is a Qt limitation in QTextEdit to where if you change a text block's indent (or any other formatting other than syntax highlighting stuff), it adds that formatting change to the undo stack and triggering the syntax highlighting again.  Long story short, the feature resulted in a frozen undo stack.  Qt provides no way to install a custom undo manager into QTextEdit, so I have no means of modifying the behavior.  I'd have to implement my own text editor from scratch, font rendering and all, to make this feature work.  Naturally, I gave up at that point.

But if you can ever find a Qt application that figured it out (without messing up the undo stack), do let me know so I can incorporate the solution.  It was a feature I had wanted very much, not only for block quotes, but also for lists.  Sometimes I wish I had used GTK instead of Qt, because I know GTK could have done it, but I needed Qt's no-fuss cross-platform capability and smooth handling of syntax highlighting for large documents.

Thanks for your feedback.  I'll close this issue and open separate ones for the clock, menu autohide, and statistics features.
