### ISSUE TITLE
Exporting to PDF via Pandoc - "pdflatex not found"

### ISSUE THREAD

**Issue by alexvisontay** [wereturtle/ghostwriter#442]
## Exporting to PDF via Pandoc - "pdflatex not found"

- OS: Ubuntu 18.10
- Pandoc 2.2.1
- pdfTeX 3.14159265-2.6-1.40.19

I have `texlive-full` installed. Both Pandoc and pdfTeX work just fine separately.

**Comment by wereturtle** [comment]
Did you install the texlive-latex-extra package?  I'm not having this issue.

**Comment by theCalcaholic** [comment]
I have the same issue. texlive-full and texlive-latex-extra are installed.

In my case, the issue is, that I installed Ghostwriter via flatpak and it is therefore sandbox. If configured that way, the pdflatex command is available at `/var/run/host/bin/pdflatex`, but it's not in the `PATH` - therefore Ghostwriter won't find it. The easiest way would be to either add `/var/run/host/bin` (and maybe similar paths) to the PATH-variable or give a configuration option for manually overriding the pdflatex path.

**Comment by theCalcaholic** [comment]
Actually, I have to correct myself. It's not that easy, because pdflatex would not have access to the corresponding `/*/lib/*/` directories.
For the flatpak version of Ghostwriter, I'd recommend to bundle texlive-full with the package (as do e.g. the okular, inkscape or gimp packages)

**Comment by taw00** [comment]
I have the same problem. I'm on Fedora. This is a packaging issue via the Flatpak version. I am working around it now by installing the native RPM packaged application. It makes the Flatpak version unusable for me. Glad there seems to be a solution via @theCalcaholic's suggestion.

**Comment by taw00** [comment]
FYI: I poked the ghostwriter package maintainer for Fedora.
