### ISSUE TITLE
Task list does not previewed and toggled

### ISSUE THREAD

**Issue by alpersunter** [wereturtle/ghostwriter#451]
Creating a task like this:
```
- [x] Wash dishes
- [ ] Clean your room
``` 
does not render in HTML as a checkbox.
Also "Format > Toggle tasks completed" does not make any difference.
I am on Ubuntu 19.04 and installed ghostwriter via PPA.

**Comment by wereturtle** [comment]
That would be because none of the Markdown processors (Sundown, Pandoc, cmark, etc.) actually support tasklists.  Not even the GitHub-flavored cmark does.  I suppose GitHub must be doing some preprocessing voodoo to create the checkboxes.  The plain text checkboxes in the editor are really just there for convenience, if you happen to like using task lists while writing to keep track of things.
