### ISSUE TITLE
Autosave doesn't work for documents that haven't been saved yet

### ISSUE THREAD

**Issue by sbrl** [wereturtle/ghostwriter#473]
**Platform (please complete the following information):** Linux
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: Ubuntu Desktop 19.04
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: Unity 7.5

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: `v1.8.0`
 - If Windows, installation type [e.g., portable or full install]: n/a
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: PPA

**Describe the bug**

Autosave does not work for documents that have not been saved yet.

**To Reproduce**
1. Start working on a new document
2. Crash ghostwriter
3. Loose the last 30 minutes of work

**Expected behavior**
Ghostwriter autosaves unsaved documents to `/tmp` or something.

**Screenshots**
N/A

**Additional context**

I rage-quit. I've just lost at least 30 minutes of a blog post because when I went to save it and clicked on the "Documents" button in the sidebar of the save as box, Ghostwriter crashed!

I know I should save my documents regularly, but if Ghostwriter's going to crash on me when I'm trying to save it I suggest some sort of protection against loosing work here.

Sorry if this seems like a feature request, but I had to get this off my chest.

**Comment by wereturtle** [comment]
That's actually expected behavior.  (Not the crashing part, but not autosaving if you haven't given your document a path/name.  You need to save it the first time before it can autosave.)  There is a new feature request to have a "hot exit" feature similar to what Sublime Text offers.  Until I get around to implementing it, I'm afraid you'll have to give your documents names first before the autosave kicks in.  Even so, it only autosaves every 30 seconds, and upon graceful exit.  Ditto with backup files.

No need to rage quit.  I'm sorry you lost your work, but on the other hand, yes, you should save your documents regularly.  The license says there's zero warranty.  I do my best to keep major bugs out of the app that would ruin anyone's work.  But at the end of the day, safety is up to you.  Please don't get angry with someone who worked very hard to provide you with something totally free out of my own spare time.  I'm not your therapist.  I don't deserve to have you unload on me.  An issue tracker is not an appropriate place to get things off your chest.

**Comment by sbrl** [comment]
Sorry for opening the issue, I was just upset at the time.

Indeed, I should have saved it first. Ghostwriter doesn't indicate this in an obvious manner like my text editor Atom does (it has a big blue dot in the tabbed interface to remind you which documents you haven't saved).

Huh, "hot exit"? I'm not sure what that means.

Yeah, I'm not angry at you for the hard work you've put into _Ghostwriter_. It's an excellent piece of software! I'm just frustrated because it took me a while to write it, and it's not actually the first time I've lost work like that, as I end up hyper-focusing (I'm high-functioning autistic) on what I'm doing and forget to save at the beginning like I do with code.

It might help if it was a bit more obvious that I haven't yet saved the document? the asterisk `*` in the title bar is pretty easy to miss.

I think I'll stick with a different editor for now like _Atom_, since it preserves unsaved documents (and unsaved changes to documents). I'll certainly return to _Ghostwriter_, but it might be a little while.

**Comment by wereturtle** [comment]
Apology accepted.
