### ISSUE TITLE
top-menus are inaccessible if you exit and then restart while in full screen mode

### ISSUE THREAD

**Issue by taw00** [wereturtle/ghostwriter#480]
OS: Fedora Linux 29
Ghostwriter version: 1.7.4

If I use fullscreen in ghostwriter, then exit, when I come back, it comes back fullscreen again, BUT you can no longer get to the top menu. Even if you exit fullscreen. The work around is to exit fullscreen _and then_ exit the program and then come back. So... BUG.

**Comment by wereturtle** [comment]
Do you have the "Hide menu bar in full screen mode" option checked under Preferences?
Also, I'm not having this issue with version 1.8.0 in Ubuntu.  I suggest trying the latest version if you can.

**Comment by taw00** [comment]
I do have the "Hide menu bar ... " checked. And it hides it, appropriately. But if you move your arrow to the top left, it reappears. But that behavior ends if you take the actions I took in the initial report.

As for version. I'm on Fedora 29. I will be upgrading ... sometime this week. I will let you know.

**Comment by taw00** [comment]
Updated my machine (it's now shiny!)...
Fedora 31.
Gnome: 3.34.2
Ghostwriter: 1.8.0

Problem still exists:
0. "Hide menu bar in full screen mode" is on
1. F11 -- goes to full screen and top-menu hides
2. Arrow to top-left -- top-menu shows up
3. Go back to writing -- top-menu does not hide ever again (NEW ISSUE), except if you turn off that preference and then turn it on again .. then it works (but still has the original problem).
4. CTRL-Q or Quit from the menu
5. Open GhostWriter again (it will automatically go to full screen mode)
6. Notice the menu bar never returns :(
To get it back, I have to F11 to get out of full screen. Exit again and then come back.

Same behavior whether it is primary screen or external monitor.

**Comment by richo67** [comment]
I can confirm, very similar behavior possibly caused by same issue. First I am running:
- Manjaro Linux 19.0
- GNOME 3.34.2
- ghostwrite 1.8.0

Observed behavior:
- Option hide menu bar in full screen mode is turned ON
- start ghostwriter
- press F11 go to full screen
   - menu keeps visible
- press F11 go back to normal screen
   - menu visible
- open menu item (seems it doesn't matter which)
- press F11 go to full screen
   - menu visible
- press F11 to go back to normal screen
   - menu disappears - is not visible
- press F11 to go to full screen
  - menu is hidden and never appears back, when you press Alt-any combination to trigger menu item menu appears for this item and the menu bar again disappears.

**Comment by richo67** [comment]
I have just upgraded: I can also reproduce it on 1.8.1

**Comment by taw00** [comment]
Note. I am running 1.8.1 on Fedora 32 and this issue seems to have been resolved.
The issue of the menu never hiding again once you trigger it to unhide still remains, but that is a different issue.

Thanks @wereturtle for fixing this.
