### ISSUE TITLE
Search dialog seems to still have focus, even if it's out of focus.

### ISSUE THREAD

**Issue by DarkTrick** [wereturtle/ghostwriter#485]
**Platform (please complete the following information):**
- Linux XUbuntu 19.10 
- Desktop environment: xfce 4.14

**ghostwriter installation (please complete the following information):**
 - ghostwriter version: 1.7.4
 - installation type: deb file from official repos

**Describe the bug**
Search dialog seems to still have focus, even if it's out of focus.

**To Reproduce**
1. Mark a word
2. Ctrl+F for search
3. marked word appears marked inside the search box
4. click somewhere inside the editor

**Actual behavior**
5. The text within the search box is still marked, as if it would have the focus

**Expected behavior**
5. The text within the search box gets greyed out or so, to show it lost the focus.

**Screenshots**
If applicable, add screenshotSasdfasfs to help explain your problem.

**Additional context**
Might be related to https://github.com/wereturtle/ghostwriter/issues/482

**Comment by wereturtle** [comment]
Not happening in KDE.  I'm thinking it's an XFCE and Qt interaction thing.  In KDE, it's marked, but the highlighting is faded to indicate lack of focus.  It could also be a Qt theme thing (since it typically uses GTK 2 theme from your GTK-based desktop environment).  In other words, your theme for your Qt apps doesn't have a different color for marking selected words when they lose focus.
