### ISSUE TITLE
Ghostwriter opens a tcp connection to 104.16.85.20

### ISSUE THREAD

**Issue by steackfrite** [wereturtle/ghostwriter#503]
**Platform:**
 - Linux  5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux
 - Desktop Environment: Gnome

**ghostwriter installation:**
 - ghostwriter version: v1.8.1
 - If Linux, installation type: From repository

**Describe the bug**
I don't think this is a bug.
I noticed that Ghostwriter is creating a TCP connection on port 443 to 104.16.85.20.

See netstat command:
`
$ sudo netstat -ntap
tcp        0      0 10.8.0.26:45784         104.16.85.20:443        ESTABLISHED 2671/ghostwriter    
`

After one or two minutes the connection ends.

Why does ghostwriter needs this connection for?
It is supposed to be  an offline tool no?
I don't want my private docs to be uploaded on the internet.

**To Reproduce**
1. Launch Ghostwriter from the desktop
2. Check network connection: sudo netstat -ntap

**Expected behavior**
No internet access.

** Additional infos **
I didn't not check if this is the only IP that ghostwriter communicate with.
It might exist others.

**Comment by abenson** [comment]
I can recreate it here (packaged ghostwriter from Void, 1.8.1)

    cdn.jsdelivr.net.cdn.cloudflare.net has address 104.16.85.20

Which leads to [this](https://github.com/wereturtle/ghostwriter/blob/e8cf211e9e720b74d41b7c4a4f4c992a2cdb4b5f/src/HtmlPreview.cpp#L93). 

Maybe this should be moved to resources?

**Comment by steackfrite** [comment]
Aw man good job!

>| Maybe this should be moved to resources?
Do you mean I should move this topic from "issue" to somewhere else?
Sorry, I'm not familiar with github.

**Comment by ferdnyc** [comment]
> Aw man good job!
> 
> >| Maybe this should be moved to resources?
>
> Do you mean I should move this topic from "issue" to somewhere else?
> Sorry, I'm not familiar with github.

No, I think @abenson is suggesting (to the ghostwriter developers) that the JavaScript file in question should be moved into the ghostwriter resources file. (If that's permitted by its license, of course.)  That way it'll be available locally, instead of having to pull it from a remote content server.

There are already other JS and CSS files stored like that, this particular dependency just got left out.

**Comment by wereturtle** [comment]
This is due to the MathJax Javascript library being included from a website.  This was done as a quick fix, since adding the library as resource files wasn't working too well.  The thing with MathJax is that there is no single JavaScript file, due to the need to include fonts separately.  Plus using the separate JavaScript files as resource files results in one JavaScript file not being able to find another one that it is including.  My long-term fix will be to install the MathJax library to a proper directory location that ghostwriter will access.  This will take some work/coordination with the volunteers who contribute to the Windows and MacOS builds, however, since I cannot test on those platforms.  But I do plan on getting around to it.

**Comment by r-menezes** [comment]
perhaps using [KaTeX](https://katex.org/) could be an alternative to MathJax problems ?

it is indeed faster, and in the frontpage they claim:

> Self contained: KaTeX has no dependencies and can easily be bundled with your website resources.

**Comment by coinop-logan** [comment]
As a privacy-concerned user who uses this tool for journaling purposes, I'd really love to see this addressed.

**Comment by coinop-logan** [comment]
Thank you for addressing this!!

**Comment by asmwarrior** [comment]
Great work. Is there any preview binary version I can try this feature?
