### ISSUE TITLE
Can't insert unicode by typing its hex digits [Linux]

### ISSUE THREAD

**Issue by vicoutorama** [wereturtle/ghostwriter#505]
**Platform:**
 - Linux Mint 19.3, Cinnamon.

**ghostwriter installation:**
 - ghostwriter version: 1.8.1
 - Installed via PPA.

**Description**
Normally, in any program, I can type ctrl+shift+U and then type the unicode for a specific character that my keyboard doesn't have. For example: "00a7" for "§". This doesn't seem to work with ghostwriter.

**To Reproduce**
1. Open any file
2. Hold Ctrl+Shift+U together and then release
3. Type the unicode for any desired character
4. Hit Enter or Space
5. Nothing happens

**Expected behavior**
The character matching the hex typed should appear.

PS:
I'm not sure if this is a feature that has to somehow be added into the program, or if it's properly a bug. If i'm mistakenly requesting a new feature, pls warn me so that I can close the issue. Tnx!

**Comment by ferdnyc** [comment]
I can tell you that Qt standard widgets like QLineEdit, editable QComboBox, and even QSpinBox **DO** support numeric Unicode input (as well as emoji search with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>e</kbd>) by default, so support for the functionality is present in Qt.

What would be involved in making it work in ghostwriter's editing UI, I couldn't say.

**Comment by wereturtle** [comment]
I'm afraid Qt 5 does not support the `CTRL+SHIFT+U` shortcut.  This is an old issue where basically the Qt devs expected X11 to implement the feature.  However, X11 just doesn't.  And given how long the bug report against X11 has been neglected, I'm betting it never will be implemented in X11.  Unlike the Qt devs, the GTK devs made their own implementation of entering unicode characters apart from X11.  The Qt devs don't appear to want to do that.  Let's pray Wayland will give us better results.

I run KDE Plasma 5, myself, and believe me, I feel your pain.  This shortcut only works for me in GTK apps, such as Firefox.  :(

**Comment by ferdnyc** [comment]
@wereturtle 

I'm on Fedora 31, currently running under Wayland, though that's not my norm. (I'd been having some nvidia driver issues recently.) At least _there_, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>u</kbd> works perfectly in the QLineEdit fields in the https://github.com/OpenShot/openshot-qt interface... to my pleasant surprise, really, since I don't tend to use that feature myself, and we definitely did nothing at all on the OpenShot end to make that happen.

It's possible this is a Fedora patch to the Qt code, but I kind of doubt it. It's possible, if you're on a Debian-based distro, that the _lack_ of support there is down to some brokenness in their Qt packaging, something we've encountered more times than I can count.

(Often such things are down to missing platform plugins, since `apt` seems to err on the side of not installing such things unless the user has the foresight and foreknowledge to explicitly ask for them. Whereas Fedora's `rpm` dependencies are set up so that packages try to pull in anything that might possibly be useful, that way the user doesn't have to know to ask for it.)

**Comment by ferdnyc** [comment]
I should also mention that Fedora == fairly bleeding-edge Qt, currently 5.13.2 for Fedora 31, with the new Fedora 32 bringing Qt 5.14.<var>mumble</var> along. So this may be a recent Qt change.

Anyway, point is, though I'd have to check again on X11, at least under Wayland on recent Fedora releases, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>u</kbd> works in _other_ Qt interfaces, but not in Ghostwriter's.

**Comment by ferdnyc** [comment]
(To double-check, I just tested again with VLC. There, too, the input fields in the preferences window — which I assume are QLineEdits — activate Unicode hex-string input mode on <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>u</kbd>.)
