### ISSUE TITLE
Export does not actually work on Linux

### ISSUE THREAD

**Issue by jggouvea** [wereturtle/ghostwriter#53]
# Reproduction.

When you try the export command from the File menu a dialog pops up asking for the exporter command (several options available) and a file dialog is in the background. After selecting the exporter the pop up does not close and clicking on save in the file dialog does not save the document.

# Expected behaviour

After selecting you preferred exporter command (mine's multimarkdown) you should be able to save.

**Comment by wereturtle** [comment]
I tried it on both Qt 4.8 and Qt 5.2 compilations, at it is working for me.  A separate dialog should not be popping up for you.  The option to select the exporter should be contained within the file dialog.   Here is a picture of what you should be seeing:

![screenshot from 2016-03-08 22 33 02](https://cloud.githubusercontent.com/assets/10375170/13627237/e3aeea2e-e57d-11e5-94b0-35ec04bc674b.png)

I have tried this with Linux Mint 17.3, and the Ubuntu MATE 16.04 Beta under Qt 5.5.  In the latter case, ghostwriter is straight from my PPA, with no Qt build dependencies installed.  I have also tried multimarkdown versions 4.5.3 and 5.1.0.  Everything exported perfectly.

What version of Qt are you using?  This is very odd behavior.  I wish I could replicate it for you.  If you are on Qt 4, I suggest recompiling against Qt 5.  Maybe you will have better luck?  Make sure you have the following dependencies installed:

* qt5-default,
* qtbase5-dev,
* libqt5svg5-dev,
* qtmultimedia5-dev,
* libqt5webkit5-dev,
* libhunspell-dev,
* pkg-config
* libqt5concurrent5
* libqt5printsupport5
* libqt5svg5

**Comment by jggouvea** [comment]
This is what I actually see:
![captura de tela de 2016-03-09 11 43 36](https://cloud.githubusercontent.com/assets/10410111/13638859/ebce78a4-e5ec-11e5-9ab4-599310819f7c.png)

I have compiled Ghostwriter against Qt 5.5.1 installed from the Qt.io website (Debian Jessie has a quite old version of Qt 5 that is refused by most software I intended to use (namely Sigil, whose developer, for some reason, is always using a Qt version that is not in any current distro).

But, if you assure me that Ghostwriter would compile against the default Qt 5 of Debian Jessie (version 5.3.2) I will try to do it against it and will let you know. 

However, since my case may be the same as someone else's, I'll provide information for your analysis, perhaps you can detect the source of the problem and solve it for someone else.

~~~~~~~~~~~
jose@home:~$ uname -a
Linux home 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
jose@home:~$ cinnamon --version
Cinnamon 2.2.16          
jose@home:~$ /opt/qt/5.5/gcc_64/bin/qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /opt/qt/5.5/gcc_64/lib
~~~~~~~~~

Ghostwriter: 

ghostwriter v1.3.1-3-g77e7c4d
Copyright © 2014-2016 wereturtle

**Comment by jggouvea** [comment]
It works as expected using Qt 5.3.2 from Debian Jessie.

**Comment by wereturtle** [comment]
Whew!  I'm so happy to hear that!

What's interesting about your screenshot is that Qt seems to be using the system file chooser dialog.  It's supposed to be rendering a Qt-based file chooser dialog, due to my adding a custom drop-down menu and checkbox inside.  Very strange.  But I'm glad it's working for you now.

**Comment by jggouvea** [comment]
The problem has reappeared. The situation is now the same, both with Qt 5.3.2 shipped by Debian Jessie and Qt 5.5.1 from Qt.io.
The only thing that changed is that I have uninstalled ALL kde packages (about 100 mB of stuff I didn't use).
I suspect you are using some kde code or something.
Have no clue how to solve this.

**Comment by jggouvea** [comment]
Succeeded in compiling using Qt 4 and the problem does not occur. So, it's not KDE-related.

**Comment by wereturtle** [comment]
There's not a drop of KDE code in ghostwriter.  It's all pure Qt libraries.  I can't get it to replicate.  Not good.  But maybe uninstalling KDE packages inadvertently removed a Qt 5 library that is required?

**Comment by odessa2** [comment]
QT 5.6 in Archlinux, I have the same problem. Is there any solution yet?

**Comment by wereturtle** [comment]
I have issue #78 opened to work on it soon.  I have to port to the new libraries.

This finally explains why the AUR for Manjaro KDE was working great, but couldn't link against QWebKit libraries with Manjaro XFCE.  KDE Plasma 5.5 is in lockstep with Qt 5.5, so there is no Qt 5.6 on that flavor.  The XFCE version would, however, pull in 5.6 instead as a dependency.

**Comment by wereturtle** [comment]
I finally replicated the issue.  I had to get a Debian Jessie-based distro running in a VM to do so, since Ubuntu-based distros and/or distros having KDE Plasma installed were behaving fine.

It appears Qt was reverting to using the native file dialog, rather than the Qt one, which you can embed as a widget into other widgets (such as my export dialog).  I figure there must be a missing dependency or some setting discrepancy between the different distros, but for the life of me I couldn't figure it out.

Fortunately, there was an API setting (QFileDialog::DontUseNativeDialog) for QFileDialog to pass into setOption which forces the Qt dialog over the native one.  This fixed the issue.  I leave this information here in case some other poor soul runs across this issue when embedding QFileDialog in another widget.

Go ahead and give the fix a try.  Let me know if you run into any further complications.
