### ISSUE TITLE
ghostwriter shows horizontal scrollbar on some cyrillic text

### ISSUE THREAD

**Issue by suhr** [wereturtle/ghostwriter#55]
The text is:
 > Вики-книга как-бы говорит, что нужно проверять реальность, ведь сон же это как ИРЛ. Радуга прямо говорит, что нужно пытаться вызывать ощущения, которые *как реальные, но фантомные,* а затем переходить к разделению, которое также *как реальное, но фантомное.* Немного разбавляет картину KingYoshi с его постоянной внимательностью, где всё-же отмечается (правда, в основном в сноске в гитбуке), что сон ощущается *не совсем* так, как реальность.

![horizontal scrollbar](https://cloud.githubusercontent.com/assets/65870/13743674/38d7c37a-e9f4-11e5-932f-6e645b5beadd.png)

**Comment by wereturtle** [comment]
I can't replicate this error, but it seems that while word wrapping, Qt decided that there's a character that extends slightly past the margin, which is what triggered the horizontal scroll bar.  I already have the text editor set to word wrap if a single word takes up past the width of the editor, but apparently the behavior in Qt is buggy.  To workaround, I have explicitly set the horizontal scroll bar policy to be always off.  Since I can't replicate the bug myself, you'll have to let me know if this works or not.

**Comment by suhr** [comment]
Yep, it's fixed now.
