### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by jggouvea** [wereturtle/ghostwriter#56]
I volunteer to translate the program to my language.

In fact I am halfway to finishing the pt_BR language file.

Who else can contribute? Because there's no point in having only one translation.

**Comment by suhr** [comment]
I'm translating ghostwriter in https://github.com/wereturtle/ghostwriter/pull/37.
Lazy translation process is slow, but I probably can speed up it.

**Comment by jggouvea** [comment]
How can I send the translation I just finished?

I am adding it here in a zip file, because that's the only way I could figure out

[ghostwriter_pt-BR.ts.zip](https://github.com/wereturtle/ghostwriter/files/181583/ghostwriter_pt-BR.ts.zip)

**Comment by wereturtle** [comment]
Hi @jggouvea , @suhr , @piyo-gh , and @tajmone !

The master branch is now under feature-freeze for release 1.4.0.  It is now safe to update the translation files without worrying about whether I'll be adding more text for you to translate.  This will be the last major release for a long while, as I'll be taking a long break after this release, with my only contributions being bug fixes.  (Yes, I'm afraid I need to get back to my own writing now.  The irony is that I made this tool to help me focus on my writing.  Oh, how I procrastinate!)

If you have a bit more time to donate, please pull in the latest from the master branch.  I've updated the translation files to clean up some confusing spots and accidental tr usages.

I'll wait to release until you are finished translating.  Of course, if you don't think you'll be able to get around to it anytime soon, feel free to let me know.  Likewise, if you need more time, there's no rush.  Just keep me posted.  I'm thinking maybe I can release in a month or so?  Will that give you enough time?

Please also note that there is a resources/quickreferenceguide_en.md file for you to translate.  This is the Quick Reference Guide help file.  If you think you have the time, you can copy this file and rename it quickreferenceguide_&lt;language_code&gt;.md.  For example, for Brazilian Portuguese, you would name it `quickreferenceguide_pt_BR.md, just like you would your .ts file.  Put in the resources folder.  When you are finished translating your copy, you can use Pandoc to export it to HTML.  (Alternatively, you can skip creating a Markdown document and just go straight off the HTML file, but I figure the Markdown file is easier to work with.)  Likewise place this HTML file into the resources folder.  Once I add your new HTML file to the resources.qrc file, ghostwriter will automatically load the correct Quick Reference Guide based on the application locale the user sets.

(You don't have to do any of this if you don't have time, of course.  Whatever you are willing to donate is highly appreciated.)

Please put in a pull request when you are ready for me to merge.

Thanks in advance!

**Comment by piyo-gh** [comment]
I tried, but unfortunately some words cannot be translated.

"Very Easy", "Easy", "Standard", "Difficult", "Very Difficult", "&lt; 1m", "&lt; 1", "250 words per page"

![freecommander_2016-05-31_11-53-35](https://cloud.githubusercontent.com/assets/18474085/15662139/e8c14da8-2728-11e6-92d6-c7391915010a.png)

**Comment by jggouvea** [comment]
Hello,

I rushed to finish the translation fast enough not to delay the schedule. Despite the quickness, I had time to fix some previous translations that were a bit fuzzy. Since I am really on a rush these days, I am enclosing the translation files so that you can commit them.

Thank you very much for the program you have made (which is, by now, mostly perfect) and count on me for translations whenever necessary.

Good night.

J.G.

**Comment by wereturtle** [comment]
Hi @jggouvea, I think you forgot to attach the translation you made.  At least, I'm not seeing it.

Thanks!

**Comment by wereturtle** [comment]
Hi @piyo-gh , I managed to fix the issue with some of the translations not showing up.  Apparently my string constants were being initialized first before the translation could be loaded.  Oops!  It should show up now.  Thanks for pointing the problem out.

**Comment by tajmone** [comment]
Re: [wereturtle/ghostwriter] Internationalisation (#56)


Hello wereturtle,

I really apologyze for such a late reply: I've been away for some days and didn't read my emails.

I've just read this message and hadn't had the time to check the repo's updates. If I am not too late, I should manage to update the Italian translation -- it might take me a couple of days. Is it too late?

Tristano

Tuesday, May 31, 2016, 3:17:04 AM, you wrote:





Hi @jggouvea , @suhr , @piyo-gh , and @tajmone !
The master branch is now under feature-freeze for release 1.4.0. It is now safe to update the translation files without worrying about whether I'll be adding more text for you to translate. This will be the last major release for a long while, as I'll be taking a long break after this release, with my only contributions being bug fixes. (Yes, I'm afraid I need to get back to my own writing now. The irony is that I made this tool to help me focus on my writing. Oh, how I procrastinate!)
If you have a bit more time to donate, please pull in the latest from the master branch. I've updated the translation files to clean up some confusing spots and accidental tr usages.
I'll wait to release until you are finished translating. Of course, if you don't think you'll be able to get around to it anytime soon, feel free to let me know. Likewise, if you need more time, there's no rush. Just keep me posted. I'm thinking maybe I can release in a month or so? Will that give you enough time?
Please also note that there is a resources/quickreferenceguide_en.md file for you to translate. This is the Quick Reference Guide help file. If you think you have the time, you can copy this file and rename it quickreferenceguide_<language_code>.md. For example, for Brazilian Portuguese, you would name it `quickreferenceguide_pt_BR.md, just like you would your .ts file. Put in the resources folder. When you are finished translating your copy, you can use Pandoc to export it to HTML. (Alternatively, you can skip creating a Markdown document and just go straight off the HTML file, but I figure the Markdown file is easier to work with.) Likewise place this HTML file into the resources folder. Once I add your new HTML file to the resources.qrc file, ghostwriter will automatically load the correct Quick Reference Guide based on the application locale the user sets.
(You don't have to do any of this if you don't have time, of course. Whatever you are willing to donate is highly appreciated.)
Please put in a pull request when you are ready for me to merge.
Thanks in advance!
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.





-- 
Best regards,
 Tristano                            mailto:tajmone@gmail.com

**Comment by tajmone** [comment]
Re: [wereturtle/ghostwriter] Internationalisation (#56)


Hi wereturtle,

since my last email I had a chance to view the updates, and realized that there wasn't a lot to translate, so I just went for it and made a pull request.

Since I don't have a compiled executable of the latest version (no Qt on my machine right now) I couldn't double check all translated strings. But from the context of previous version, I should have got it right.

Let me know if everything is ok.

Tristano

Tuesday, May 31, 2016, 3:17:04 AM, you wrote:






—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.





-- 
Best regards,
 Tristano                            mailto:tajmone@gmail.com

**Comment by wereturtle** [comment]
Hi Tristano,

Thanks for the quick turnaround.

There seem to be a lot of merge conflicts, plus missing translations.  I don't think you were working with the latest that is on the master branch.

If it's not too much trouble, would you mind doing a fresh `git pull` from your local master branch?  Alternatively, you can just grab the .ts file off the GitHub page and update it, and then attach it in a message on this thread.  I can hand merge if need be.

Thanks!

P.S.  Don't worry, there's plenty of time to get this done!

**Comment by dhbwmawhd** [comment]
@wereturtle How far off is `v1.4.0`? The issues for that planned release have all been close. I could open a pull request for German over the weekend. Got like 70% of it already.

**Comment by wereturtle** [comment]
@dhbwmawhd I was giving more time to release v1.4.0 out of the hope that I would get a couple more translations in.  I'll probably release next weekend or the weekend after.  If more translations come in after that, I'll have to make a 1.4.1 version with the new translations.

Thank you in advance for your translation!
