### ISSUE TITLE
change editor line-height

### ISSUE THREAD

**Issue by nicolastaffin** [wereturtle/ghostwriter#565]
Hi, thanks for the great software, really.
I'd like to increase line height in editor and i did not find where to do it. It would be very important to me. as it is too tight for me to feel comfortable to write.

 Is there a way to do it somewhere, even in a config file ?
Thanks.

**Comment by miker** [comment]
Would zoom in/out work for you? Ctrl +/- zooms like in a browser. This is only a visual change of course.

**Comment by madig** [comment]
Zoom does not change the line-height. Think instead of the line spacing controls in word processors (1x, 1.2x, 1.5x, 2x, ...). This is useful to have, since line-spacing meta information is embedded into fonts by the designer, but set arbitrarily with at least three different ways to chose from, and with applications free to apply the spacing information however they please. Add that different scripts may need different line-spacing and you've got a need for fine-tuning.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
