### ISSUE TITLE
Strange behaviour of HUDs and background.

### ISSUE THREAD

**Issue by jggouvea** [wereturtle/ghostwriter#57]
I have compiled the last update of the repo and got this:
![tiling](https://cloud.githubusercontent.com/assets/10410111/13861373/bba6028e-ec6b-11e5-8133-22ba0b93a68b.png)
Tiled background from the OldPaper custom theme is not tiled to fill the entire screen, but only the previous size of the screen. This behaviour is not only when I maximize, it happens too after I maximize, quit the application and start again. I have logged off and on the desktop and changed many desktop settings and it remains.

I'd like to know if other people using the MATE desktop environment (which I have switched to) have encountered the same problem. I suspect this is a bug from MATE's window manager.

![hud](https://cloud.githubusercontent.com/assets/10410111/13861375/be113bb0-ec6b-11e5-9597-9afa34c2db9e.png)

This is more annoying: HUDs only appear centred onscreen and cannot be moved.

**Comment by jggouvea** [comment]
The window centering problem is solved if you uncheck the "disable workarounds" option in the dconf-editor. For this reason I believe the same problem happens with older Gnome versions too, but not with the newest.

**Comment by jggouvea** [comment]
The tiling background problem does not happen if you select the theme AFTER loading the program.

**Comment by wereturtle** [comment]
Sorry about that.  The tiling issue was a regression from when I refactored some code for hiding the menu bar in full screen mode.  It should be fixed now.

I'm glad you were able to figure out the HUD issue, because I couldn't replicate it (and I'm in MATE as well).  Nice to know that workaround for dconf-editor, in case I ever run into that in the future.  Thanks.
