### ISSUE TITLE
CriticMarkup Support

### ISSUE THREAD

**Issue by tajmone** [wereturtle/ghostwriter#60]
> CriticMarkup is a way for authors and editors to track changes to documents in plain text. As with Markdown, small groups of distinctive characters allow you to highlight insertions, deletions, substitutions and comments, all without the overhead of heavy, proprietary office suites.

> http://criticmarkup.com/

The good thing about CriticMarkup is that it doesn't interfere with markdown tools that don't support it — its just a small set of extra markdown markers, which can be added to any MD flavour without disrupting anything. 

MultiMarkdown-5 already supports it:

http://fletcher.github.io/MultiMarkdown-5/criticmarkup.html

Presently, there is a Python CLI tool to manage CriticMarkup changes (accept, reject, hyde, ecc.); and hopefully we might soon see standalone binary shell/CLI tools that could be added to a markdown conversion toolchain.

There are also some CriticMarkup plugins/extension for various code editors supporting markdown (Vim, SublimeText, and others), and **MultiMarkdown Composer 2** fully supports it natively.
[ see: http://criticmarkup.com/tool-list.php ]

It would be nice to have in ghostwriter the option to enter/exit "revision" mode, and have it track changes by adding CriticMarkup syntax to the source as it gets modified. And to have it also automatically recknognize CriticMarkup syntax, highlighting revised text and allowing to accept/reject revisions from a right-click context menu.

CriticMarkup Syntax & Features boil down to five types of operations/Critic marks:
- Addition {++ ++}
- Deletion {-- --}
- Substitution {~~ ~> ~~}
- Comment {>> <<}
- Highlight {== ==}{>> <<}

Markdown is used a lot in the context of version control. CriticMarkup adds a layer of simplicity to collaborative writing with tools like Git: diffing becomes an "in-doc" affair, allowing atomic acceptance and/or rejection of text changes even after full merging (without having to revert in history).

**Comment by wereturtle** [comment]
The problem with CriticMarkup is that it is orthogonal to Markdown, which is why I'm not particularly fond of it.  For example, the following code span has CriticMarkup.  Did the author intend to demonstrate CriticMarkup, or did the author actually want to delete part of the code span?

    Here is a `code{-- span--}` example.

If you truly have your heart set on this feature, you are welcome to implement it and put in a pull request.  It's just not my own radar.  Given my limited time, I tend to focus on bug fixes or, at most, low-hanging fruit for new features.

The relevant spots where you would make your modifications to implement this feature are:

* MarkdownEditor (.h/.cpp) - detect insertions and deletions to put in CriticMarkup
* MainWindow (.h/.cpp) - put in new menus under buildMenuBar(); add new HUD window to display all CriticMarkup edits for quick navigation
* MarkdownHighlighter (.h/.cpp) - put in CriticMarkup color highlighting; notify MainWindow of CriticMarkup changes in document to be displayed in CriticMarkup HUD (follow Outline.cpp as example)
* MarkdownTokenizer (.h/.cpp) - parse CriticMarkup for the MarkdownHighlighter
* Theme (.h/.cpp) - add new CriticMarkup colors
* ThemeFactory (.h/.cpp) - read in CriticMarkup colors into Theme
* ThemeEditorDialog (.h/.cpp) - allow user to set CriticMarkup colors
* AppSettings (.h/.cpp) - add sundry CriticMarkup options
* Make a similar class to Outline (.h/.cpp) for CriticMarkup navigation in the document.

So, definitely not low-hanging fruit, but it's doable, if you are willing.

**Comment by tajmone** [comment]
Thanks for the precious indications. C++ isn't exatly my league, but I could try it though. Surely knowing where to look would make the task easier.

I can understand that markdown users have mixed feelings toward CriticMarkup. Mainly, it's a feature handy for those who work on non-scientifical, non-computer related texts—usually for novels; especially in collaborative editing on platforms like GitBook, and the like.

In that kind of use  one wouldn't stumble in disambiguation problems relating to tags or code.

Possibly, if ghostwriter in the future will expose part of its API via customizable plugins, this feature could be added as a custom extension/plugin in some scripting language (JS, Lua, ecc.).

Any plans on that?

**Comment by wereturtle** [comment]
I probably won't put in a plugin API at such a low level.  It would slow down the editor significantly, especially for large documents.  One of my goals with this application is high performance no matter the size of the document.

Regarding my last bullet point in my prior post, I had a second thought.  If you choose to give it a try yourself, the Outline class isn't as high-performance as you'd want it to be for Critic Markup.  Right now, there is an edge case where if a user has, say, hundreds of headings, the entire application will slog down every time you put in new text.  This is because the outline HUD has to search through each text block in the editor to get updated cursor positions for the headings (for navigation) whenever text is added or deleted.  It's usually not a big deal, because most sane people would never have that many headings, not even for their dissertation.  But for Critic Markup, the potential is there for hundreds of markup points in the document.  Hence, modeling off the Outline class for producing a Critic Markup navigation HUD isn't the best way to go.  The thing is, I'm not sure if there is a better way.  QPlainTextEdit (from which MarkdownEditor inherits) and its doppelganger, QTextEdit, have a poor API when it comes to simply pointing to the QTextBlocks in the document (so that you don't have to update cursor positions).  I think the QTextBlock class might be a temporary wrapper to the real underlying text block in the document.  Thus, if you just have Outline or your Critic Markup navigation class point to a QTextBlock, the QTextBlock won't truly be getting updated to point to the underlying text block between calls.  You'll understand once you start playing around with QPlainTextEditor and QTextBlock.  As it is, I've had to do a lot of weird hacks for the outline navigation and setext header highlighting to work.  The Qt API isn't that powerful for certain use cases.  But maybe you'll be able to figure something out.  I just thought I'd give you a heads up, in case you end up trying your own Critic Markup implementation.

**Comment by tajmone** [comment]
I agree with your choice of performance above all, after all it's ghostwriter's strength point.

I have dwelved into QTextEdit documentation in the past (the PyQt version, but it's the same), I was considering using it for a markdown related project, but I ended up discarding it — even if I liked many of its features, it seemd to me that its internal rich text format could be problematic: a subset of HTML which left out some very common features, so I feared it might break up things at some point along the growth of a project. It seemed to me also that Qt5 didn't bring enormous changes to the QText family of controls.

It is rather possible that adding the CrticMarkup format to the syntax highliter and other contex-aware functions might end up slowing things up — it would also have to be aware of which block elements is inheriting, and the inline elements it might be encompassing. And I guess that cases of edits that span across elements borders (not a rare occurance at all) would require breaking up and subdividing elements at both the block level as well as inline. 
So, if a huge presence of headings is already jeopardizing performance, in the implementation of CriticMark there is a potential for a massive slowdon, even in medium sized documents.

My knowledge of Qt is only at a very basic "read the API documentation" level, so I wasn't aware of the real-case-scenario problems of this sort.

Thanks a lot for the answers, and the precious hints on how to approach attempts in this direction.

**Comment by wereturtle** [comment]
Drat, I didn't even think about the multiline spanning for CriticMarkup.  Yes, that would start to get hair-raising to parse.  I already have HTML comments spanning multiple lines, but those are easy because I don't have to parse them again for more "nested" highlighting.  We'd probably have to start using binary OR operator for the block state flags in the syntax highlighter to combine regular Markdown parsing states with the CriticMarkup states, to make it easier.

It's too bad QTextEdit and QPlainTextEdit are so inflexible on some things.  Sadly the Qt devs are more focused on QML and mobile apps these days to spiffy up the old C++ API.  For example, I've wanted to have block quotes and lists indent after the first line.  QTextEdit won't let me indent the text block without adding the formatting to the undo stack.  Performing an undo operation triggers the syntax highlighter twice, which ultimately causes the undo operations to "freeze" to where you can never undo anything past the point that the indent was introduced.  There's no way to bypass adding the indent formatting to the undo stack, as the API for that isn't exposed.  I'd have to basically create my own text editor from scratch, with my own font rendering, to implement the feature.  Obviously, nobody would have time to create that from scratch.  It's a real shame.  In some ways, QTextEdit are QPlainTextEdit are so easy and efficient, and yet in other ways they are maddeningly inflexible.

Sorry for the rant.  But anyway, yes, if you don't think you'll ever be able to implement this feature, it's probably best to close this issue.

**Comment by tajmone** [comment]
This confirms what I suspected might be some case problems with Qt. When I was carrying out some research to plan to create an MD editor that would integrate with Git or Fossil, I came to the conclusion I would have gone either for Electron or Webkit — but Electron actracted me mostly, not only for the astonishing results of Atom editor, but because main scirpt is independent of browser view.

With that said, the downside it's the bloat of having the Chromium codebase underneath (which is rather huge, especially if you think that quite often people end up having the same codebase replicated in different apps), plus some loss in speed performance if the project grows big. Of course, creating a Chrome extension would make the whole project much lighter, since it could rely on the Chrome engine already in place, avoiding redundancy. But somehow relying on Chrome browser didn't appeal to me (though nothing wrong with it).

But true, one can't reinvent the wheel each time. When it comes to GUI frameworks, it's still not easy to find some nice middleware truly crossplatform. But I hope that all these new trends and experimenting with CSS/HTML GUI designs will soon bring about some new tools, truly crossplatform and easy to integrate in any language.

Presently, I'm testing on a project using Scintilla. I like it, and even though is more code-editing oriented, it seems to be tamable to handle markdown. Just struggling a bit with Lexers and styling.
