### ISSUE TITLE
Menu font size for High DPI displays

### ISSUE THREAD

**Issue by tekblupace** [wereturtle/ghostwriter#610]
First off thanks for the awesome app.
I was wondering if there was a way to change the menu font size when using High DPI displays?

**Comment by wereturtle** [comment]
Please try launching ghostwriter from a terminal window with the QT_DEVICE_PIXEL_RATIO environment variable set:

    $ QT_DEVICE_PIXEL_RATIO=2 ghostwriter

You will want to set it to the DPI ratio of your monitor.  Note that I've had issues in the past with fractional values (a la "1.5"), so stick to integral values, like 2 or 4, for now.

If this resolves the issue, then the problem is with Cinnamon.  Which wouldn't surprise me because GTK-based distro flavors tend to forget the DPI settings for Qt apps.  :(

For more information on the Cinnamon DPI scaling factor issue, see [this bug report here](https://github.com/linuxmint/cinnamon-settings-daemon/issues/135)

_Originally posted by @wereturtle in https://github.com/wereturtle/ghostwriter/issues/612#issuecomment-849394031_
