### ISSUE TITLE
Exporting MarkDown to MarkDown

### ISSUE THREAD

**Issue by tajmone** [wereturtle/ghostwriter#63]
In exporting there are no options to export in MarkDown format. Exporting markdown to markdown allows quite a few benefits — at least, with Pandoc it does.

First, you can use the export function to convert from one MD flavour to another.

Second, exporting a doc to itself, maintaining the same format, is a trick to cleanup the MD source. 
With Pandoc this trick allows some extra features as well.

- Pandoc defaults to 80 columns wrapping, which means that all text blocks will be "paginated" to 80 columns, giving a cleaner feel to the raw source. Using the `--columns=` option one can customize the width.

- All lazy syntax will be cleaned up

- Pandoc will apply default (or chosen) styling to the document (ATX vs Setext headers, and so on) giving uniformity to the document.

- The `--smart` option will convert straight quotes, dashes, ecc.

- The `--standalone --toc` options will create an auto-generated TOC at the beginning of the document — quite useful for working with API docs, READMEs, ecc. (The `-s` / `--standalone` is required for this to work).

And possibly quite a few other useful hacks one could apply to the document he is working on.

I am not sure how the other Markdown processors handle this approach, but with Pandoc it works greatly. After all, Pandoc parses the input into an AST, and then from the AST it "compiles"/converts the required format. Since most md parsers I've seen use some kind of AST, any markdown processor should allow convertion to the same format as the input.

It might be nice to have some quick way to process the current open document without going through the export process — somethink like a "refresh/cleanup" menu entry. This would allow changes to happen in memory, instead of directly on file, so cleanup will not affect the document until saved, and user could revert to previous state by non-saving.

Like for Export and HTML Preview, it should allow to choose which processor to use, and memorize last choice — this choice adds a step to what would otherwise be an immediate action, but the introduction of a per-doc markdown flavour association (or by file extensions) would allow a "set it and forget it" approach, allowing for "cleanup" to act immediately, without intermediate format-choice windows.

**Comment by jggouvea** [comment]
This would be a nice feature to have.

**Comment by wereturtle** [comment]
FYI, I've already got a checkbox in the export dialog for the `--smart` option for all exporters.

As to why I don't put in more GUI options for all the various features of Pandoc and other exporters?  Well, there's the issue of maintenance.  A new version of Pandoc or MultiMarkdown, etc., could change the format of the command line parameters.  I'd have to keep up with each new version while maintaining support for older versions.  The more command line parameters I support, the higher the risk of future breakage.  And, Pandoc has a lot of options.  It's rather burdensome to make a GUI for them.  Even if I just stick to Markdown to Markdown conversion options, someone else will eventually come along wanting the other options.  I'd prefer to keep the camel's nose out of the tent.

My other reason is that I want it to be simple for new users.  Advanced users can use the command line or make a script.  New users would be overwhelmed by too many options.  I figured that supporting the most popular formats and smart typography toggling would be sufficient.  And the reason that I support a checkbox for smart typography is because it is the one universal feature supported across multiple Markdown exporters.  This makes it easy to build a consistent export dialog.

But thanks for the suggestion nevertheless.
