### ISSUE TITLE
No Autosave until after first save. No warning of such

### ISSUE THREAD

**Issue by kimcosmos** [wereturtle/ghostwriter#637]
Autosave only applies after first save. there is no warning of this (nowdays) unusual behavior. Some people don't have batteries and sometimes systems or GUIs need restarting without quitting.  I had a file open for a week with 6300 words when I had a power outage and the file was not in recent history (unlike others I have created). On testing I see that the autosave setting does not apply until after the first manual save. It does not use the first line as filename, as is the simple standard way.   \
SO I am understandably upset. I must now rewrite it all from memory ASAP before it is lost for good
5.9.16-1-Manjaro x86_64, Mate 1.24.1
GW 2.0.1-1
This is not the [fast exit issue](https://github.com/wereturtle/ghostwriter/issues/75#issue-146907480) which now prompts to save on exit.  
Even back in 2016 resumption of temporary files was an expected feature. By now its absence is shocking. It certainly shocked me. At the very least it needs a prominent warning that saving is essential. So people engrossed in their writing don't lose a weeks work from knocking loose a power cord.

**Comment by JoelMon** [comment]
Out of curiosity, what's that use case for not manually saving a document after working on it for a week?


To clarify, the problem is that the the document is already saved on the system. When the user opens and edits the document, it doesn't auto save *until* the first manual save by the user?

**Comment by kimcosmos** [comment]
No, the document is not already saved, and thus cannot autosave.
The use case is ease of use. For a decade at least I only need to remember
to rename a document as it will be restored if the app crashes. I was
expecting that as this is described as an editor that gets out of the way.
So the use case is its core feature... focus on writing

**Comment by JoelMon** [comment]
> No, the document is not already saved for a week, and thus cannot autosave.

I see, so you start a new document and don't save for a prolong amount of time and expect a backup to be created.

> Is it only a bug on my computer? Or is this a missing feature? 

It's definitely not a bug. As far as a missing feature, I'm not sure if the thought that a user would work on a document for such a long time without an initial save has crossed the developer(s) mind since it isn't common practice to work on a document for days without saving.

> The use case is not closing the document whilst working on it... However long it takes. I switch to it whenever I think of something new to add. No need to wait for loading, no need to scroll to the right spot. 

You can save the document and not close the editor. Everything will remain exactly as you left it and you will have the document saved with auto saved working from that point onward.

> For a decade at least I have only needed to remember to rename a document as it will be restored if the app crashes. I was expecting that, as this is described as an editor that gets out of the way. Thus I forgot to ever save it as I never closed it. So the use case is its core feature... focus on writing. Like a giant formatted desktop sticky note. Its a common writing technique - get the ideas down ASAP. Any label is tentative and can change. So a filename is unimportant and distracting as it should often change. Immediately upon starting to rewrite it I changed the title and focus to broaden it. Sadly I still have to rewrite that 6k words before I can reorganise it under the new title.

If I may suggest, I think there's room for improving your workflow tremendously without changing it except for one tiny detail. In other words, by doing one small step at the beginning of your project, you'll be able to keep the way you currently do things without the worry that you might loose your work at any second.

When you start a new project --- be it a novel, documentation, speech, song lyrics, etc --- Your first step would be to open the editor you'll be typing in. Go ahead and click `File` and `Save As`. You only do this *once* in the life of the document you are working on.

You mentioned that you normally have to change the filename as you work. That's fine, just give it a generic name that means nothing, such as `file.md` or `x.md`, and save it on the desktop if you like. The specific location doesn't matter as long you can find it again if needed. Don't touch the filename again until you finish your work. From this point on, continue typing your work as if it were an electronic sticky note, as you said. You don't need to modify, look at, or think about the filename again. The auto-save will work after this.

The significance of saving once at the very beginning of your project is that:
1. You have given the document a place where it can live.
2. Ghostwriter will know *where* you'll would like to save your auto-saved files (unless you make an initial save, Ghostwriter wouldn't know where to save the backups).
3. In case of an emergency, there's a copy of your work somewhere predictable and you don't loose productivity.

After that, you continue working for weeks or months on end as you are used to and auto-save will have your back.

Now, if you would like one more tip that will again increase the safety of your hard work by a huge amount while only costing you an insignificant amount of effort or thinking, it would be this: When you take a break from working on your document, click `File`, `Save`. This will save your work up to the point you are currently at. `Save` is not the same as `Save As`. Ghostwriter knows where your file is located so `Save` will save all of your hard work without asking you for a filename or location to the file. In other words, it's 100% non-intrusive to your workflow. To make it even simpler, you can use `Ctr+s` (hold down control and press *s*) to save your work.

Also, in `Settings`, `Preference` make sure you have `Auto save` and `Backup on save` checked.




![image](https://user-images.githubusercontent.com/6587811/126047038-e189f236-cb22-4bda-93fd-4690847d57ac.png)

**Comment by wereturtle** [comment]
Thanks @JoelMon.  This post was making me seriously contemplate shutting down the issue reporting feature in GitHub.  After a while, the lack of respect for the contributing guidelines, the whining that it doesn't do X like app Y does, or the random rage posts start to get to you.  So, thanks for dealing with this individual.  :)

As for you, @kimcosmos, all I can say is that I am truly NOT sorry you lost your work.  Take this bad experience as a lesson learned in the school of hard knocks.  It is just not a normal usecase ANYWHERE to not save one's document after a WEEK of having it open.  Even under the best circumstances, a power outage can cause corruption in the middle of a save.  This sadly happened to a user a while ago where ghostwriter had just autosaved to an already saved file and the power went out.  Poof!  Corrupted!  Lesson:  Save, save, save.  Then backup.  Save some more, backup.   Make CTRL+S a subconscious action taken regularly as you type.

I happen to already be working on the "hot exit" feature where it will save to a temporary spot until you formally save it.  But even then, never trust any app with your precious data.  Not even even the commercial stuff like Word.  Form good habits.  It will save you some grief down the road.

**Comment by kimcosmos** [comment]
I switched to Joplin and of course it immediately saved based on the first line. OK I had to install a input.css for TOC but it didn't delete anything. My issue was that a warning is required. Something you have not addressed in your whiny replies. 
How do you know what is normal for writers wanting an editor that gets out of the way? 
Is this the same hot exit you have been working on for 5 years?
Of course I had autosave on, that was why I did not save.
I already said that I can't save with a meaningless name and expect to remember where it is. You seem too interested in whining about obvious problems that, from the start, I said I did not have.
My point in the title is that before working for 5 years on a hot exit you could put a warning in the autosave settings that it will not autosave until manually saved first. You seem too offended to try to understand what I am saying.
Lesson learnt. Ghostwriter is an inconsiderate as the DOS editor I was using 40 years ago.
I agree with you however. YOu should close the issues. You are only using them to whine and complain. Its not a good look.

**Comment by wereturtle** [comment]
> My issue was that a warning is required.

I know, but you could have said it more nicely.  I'm not your slave that you can just yell at and boss around.  If you don't like the FOSS app that has NO WARRANTY then use something else.  I'm glad you found a suitable replacement.  Next time, realize that FOSS software doesn't have a warranty and that you should make sure the features work as you expect before you commit your precious work to them.  That is my bottom-line point.

> Something you have not addressed in your whiny replies.

"Autosave" means different things to different people.  For example, it took a while before Atom would "autosave" an untitled text buffer. Prior to that commit, you had to give it a name first before autosave would work.  That's the point where ghostwriter is.  There actually is a warning in the title bar--that wee asterisk next to the word "untitled" that lets you know your document needs to be saved."

![image](https://user-images.githubusercontent.com/10375170/126217901-e6be12c9-3a85-44a6-aca1-81d3a67baae1.png)

> How do you know what is normal for writers wanting an editor that gets out of the way?

I know what is safe.  I just don't consider your use case of leaving an untitled/unsaved document open for a WEEK as normal because it's UNSAFE.  Quit blaming and LEARN, for your own sake.  *Always test that an app does what you think it does before committing real work to it.*

> I already said that I can't save with a meaningless name and expect to remember where it is. You seem too interested in whining about obvious problems that, from the start, I said I did not have.

You are the one who is WHINING WHINING WHINING.  You could have simply stated the issue you were having without the blaming, and proposed your simple solution.  Instead, you WHINED.

> My point in the title is that before working for 5 years on a hot exit you could put a warning in the autosave settings that it will not autosave until manually saved first. You seem too offended to try to understand what I am saying.

You're purposely coming here to OFFEND and unload your frustration.  It doesn't exactly make me want to be bothered fixing your issue the way you want it fixed.  I'm not your slave.  Learn to ask nicely.  I swear, I don't take this kind of abuse at work.  Instead I get thanks and raises and such.  I put the same quality of work into my pet FOSS project, and I get yelled at and whined at.  What is my motivation to do anything for you, exactly?

And yes, hotexit has taken 5 years.  I've had to deal with real life, real job, real health issues, etc.  It just hasn't been my highest priority.  You'll find plenty of other FOSS maintainers have the same time constraints due to real life.  Get over it.

> Lesson learnt. Ghostwriter is an inconsiderate as the DOS editor I was using 40 years ago.

I didn't realize ghostwriter came with an AI built-in that makes it able to be inconsiderate.  Oh, wait, you're calling ME inconsiderate.  I get it.  I put countless hours of work out for free that you can personally evaluate and use at your discretion if it fits your use case, and I'm inconsiderate because you made assumptions about the tool (which is GPL 3 licensed and comes with NO WARRANTY) without testing it first.  I bet if you made such complaints to the Microsoft support forum they wouldn't let you call them that.  They'd close your WHINEY POST faster than you could spit.

> I agree with you however. You should close the issues. 

Wish granted.  But keep treating others like you treat me, you might find even your favorite pet software closes its issue tracker because the folks on the other end also get sick of yours and others' attitudes.

> You are only using them to whine and complain. 

Most of my replies are to help people or get more steps to replicate bugs.  This is not a bug.  My contributing guidelines say to only report bugs.  I wonder if there's any posts on Github you've ever made that did anything but whine and complain?

> Its not a good look.

Why should I care what it looks like?  I get nothing for putting my code out.  My real name is not disclosed.  I haven't earned one red dime for this.  And yet people like you come here expecting me to be their personal slave.  Just politely closing the posts asking for new feature requests (which I have said no to in the contributing guidelines) sucks up personal time that I could have spent actually working on ghostwriter.  Sad, but true.

Anyway, since we're using each other to vent frustration, thanks for the therapy session. I feel much better now closing the issue tracker.

To all the kind people who might be reading this wondering why the issue tracker is closed, I'm truly sorry.  After a while, it gets old, discouraging, etc.  I'm reaching burnout, and for my own sanity, closing the issue tracker is what I must do.  I can't imagine what maintainers of far larger projects go through.  But now I know why the maintainer of FocusWriter never had his issue tracker open.  I will, of course, do my best to maintain ghostwriter even without the bug reports coming in.  Hopefully I catch the bugs in a timely manner.
