### ISSUE TITLE
[Feature Request] Transparent BG Option

### ISSUE THREAD

**Issue by FluxCapacity** [wereturtle/ghostwriter#66]
First off, total noob here.

But I'd love to see the option to set transparency in the background.  Perhaps where you select the BG color under themes, 8-digit hex could be accepted and a transparency slider could be added.

**Comment by wereturtle** [comment]
You mean for the window itself to go transparent such that you can see your desktop and underlying windows?  I'm afraid that isn't feasible.  I would have to write my own custom window painting code to do that, including window decorations like the minimize and maximize buttons.  I would also lose native look and feel by doing so.  Sorry about that.

**Comment by FluxCapacity** [comment]
As someone who is considering learning how to code, is that something that could be done by forking the project and adding the feature with novice experience?

**Comment by wereturtle** [comment]
I wouldn't consider that novice level.  You have to code things like moving and resizing the window from scratch.  The reason you have to do all this is that Qt is letting the window manager (i.e. Windows or your Linux desktop) draw the window, which is why you can't have transparency for the window by default.  You have to override that default behavior by drawing the window, including it's frame and all the minute handling of it, if you want to set the window transparency.

If you still want to try, the HudWindow class shows a very basic example of drawing a window.  It doesn't have full functionality, however.  The size grip is currently taking care of window resizing automatically, but I had to write my own code for a close button and to move the window with the mouse.   There are a few Qt code examples out there from people who have tried to draw their own window frames from scratch, including minimize, maximize, etc. functionality.  I'd start with a Google search and see where you end up.

Good luck!
