### ISSUE TITLE
i18n — Exposing the Quick Guide

### ISSUE THREAD

**Issue by tajmone** [wereturtle/ghostwriter#68]
During translation I've notice that the Quick Guide is not exposed via Qt Linguist for translation. Instead, it's to be found amongst the resources in the source files:

`/resources/quickreferenceguide.md`

It seems it's then integrated into binaries as a resource. Maybe, in view of the translations coming in, it might be good to implement a way of having ghostwriter seek for the refguide on disk (maybe in MD format, and convert it to HTML on the fly?), using some language prefix to select the proper file according to locale (if the file is present, else fallback for the English version.

Eg: looking for `quickreferenceguide_en.md`, or `quickreferenceguide_it.md`, and so on.

Maybe the English version could be incorporated in the binary resources, but in case of localization the file might be seeked-for in the `translations` folder, like for the locales files...

Which also brings up another issue: the languages extensions to use for i18n. I've looked at the Portoguese translation, and it clearly adopts the double specification, whilist the English file goes with just `_en`. With Italian translation files, it only worked with the short versions (`_it` instead of `_it-IT`). In Italian this is not a big issue (Italian Italian and Swiss Italian are basically the same, but for other languages it might not be so, I gather that Spanish is spoken quite differently in countries other than Spain, and so on).

**Comment by wereturtle** [comment]
OK, the first issue I fixed by having ghostwriter lookup which quickreferenceguide HTML file to load by locale.

Precedence is as follows:

1. Try to load quickreferenceguide_language_country.html first.  For example. for English, Great Britain locale, try to load quickreferenceguide_en_GB.html.
2. If 1 fails, try to load quickreferenceguide_language.html. For example, if the locale's language is Italian, try to load quickreferenceguide_it.html.
3. Fall back to quickreferenceguide_en.html, which will always be available.

The quickreferenceguide_en.md is just for my own personal ease of use, so that I don't have to edit the raw HTML whenever I want to update the guide.  I use Pandoc to convert it to HTML.  Translators are welcome to use the same method if they want, but it is not necessary.  They can go purely off the HTML when translating.  Only the HTML is included in the end product that is bundled.

For the second issue, I think the hyphen might be causing the problem.  Instead of `_it-IT`, try `_it_IT` (with an underscore) in the translation file name.  Qt should pick it up then.

**Comment by tajmone** [comment]
great! When I'll have the translation ready I'll upload it in `/resources/` following the above naming convention! I'd too go for the md 2 HTML convertion convenience — source files never hurt.
