### ISSUE TITLE
"Document has changed" warning appears twice

### ISSUE THREAD

**Issue by tajmone** [wereturtle/ghostwriter#69]
Every time I change with an external tool a document which is open in ghostwriter, the warning "Document has changed/Want to reload?" pops up twice in a row.

This on Win 10 OS; Ghostwr. 1.3.1 Portable release.

**Comment by wereturtle** [comment]
I can't replicate this on Windows 7, and since I don't have Windows 10 to replicate the issue, I'm afraid you'll have to do a little sleuthing yourself to help narrow down how to best fix it.

Check out this [link](https://forum.qt.io/topic/41401/solved-qfilesystemwatcher-reports-change-twice) regarding Notepad++ causing QFileSystemWatcher to signal a file change twice.  Apparently other editors can save files using the same method that would trigger the file changed signal twice.

I would suggest trying just plain old Notepad as your second editor to see if this issue occurs.

If it is the case that your second editor is recreating the file with size zero and then saving the contents from scratch again, then I don't think there's much we can do to fix this issue.  It's just the way the editor modifies the file twice every time it saves.  I wouldn't be comfortable putting in a fix-it hack that might cause other unwanted side affects.

**Comment by tajmone** [comment]
Yes. I carried out the test and confirm: Notepad++ document changes trigget the warning in ghostwriter twice, while MS Notepad only triggers it once. So the problem is on the other app side.

Also changing a document with Pandoc causes the double warning.

Strange indeed. It makes sense that some apps clear a file (saving it as zero) and then fill it with contents and resave it. Other changes-aware applications, interacting with Notepad++ and Pandoc, are only triggered once by changes. I guess it has to do with the library implemented to check for filesystem changes.

I was reading about such cross platform libraries just the other day, and from what I gather they actually rely on a different set of system internals for each OS — Obtaining Directory Change Notifications (in Windows), inotify, kqueue, ecc. There are different libraries, like fswatch, efsw, fsnotify, ecc, but they all have in common a range of different behaviours/functions for each OS, simply for the fact that each OS has a different system architecture regarding how file system monitoring and notifications are handled.

No big deal anyhow. It's just strange that it quews such notifications — after all, once a file has changed it doesn't make much difference it has changed once, twice or thrice: changed is changed and it requires reloading. This type of warning should be triggered only once after each realoding/saving vs changed state occurance.

**Comment by wereturtle** [comment]
All right, I'll close this issue, then.  Thanks!
