### ISSUE TITLE
Ghostwriter creates numerous, empty "untitled-[number].md" during startup.

### ISSUE THREAD

**Issue by dagdrommer** [wereturtle/ghostwriter#696]
**Platform (please complete the following information):**
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: Arch Linux, Native-Repo, KDE-Plasma

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 2.1

**Describe the bug**
Every time I start ghostwriter, no matter if a ghostwriter instance is already up and running, or if its the first start, ghostwriter writes two empty markdown files (untitled-[number].md) in my ~/Documents/ folder.
This behavior appears no matter if I open ghostwriter by double clicking an already existing md-file, by opening the last accessed, or by starting a new empty instance.
The created empty md-files furthermore don't get automatically removed after finishing editing a document and they clutter the Documents folder (unless they are removed manually).
If I deactivate autosave the files won't appear on program start.

**To Reproduce**
- Autosave: enabled
- Backup file on save: disabled
- Load last used document on start: enabled

**Expected behavior**
I expect that the files are not created and if in a temp folder that is cleaned up after the program exits.

**Comment by woland7** [comment]
Same, for me on Arch Linux with KDE Plasma. One gets created at startup and the other at shutdown.

Following.

**Comment by mjis1** [comment]
I found this bug may be related to Auto save setting, we could turn that setting off before fixed.

**Comment by tildagail** [comment]
I'm seeing this problem as well in Xubuntu. If autosave is enabled, one .md file is always created and saved on startup, and another one on shutdown, regardless of how I open the program.

Further information: if I open ghostwriter, select 'new' from the menu and type something in that file, then close ghostwriter without saving, I end up with three files - an empty untitled-1.md that was created on startup, an untitled-2.md that has my typing in it, and an untitled-3.md that was created on closing the program.

**Comment by dagdrommer** [comment]
I can also reproduce the behavior described by @tildagail .
I can also confirm that the problem disappears when autosave is turned of.

Further, I think the whole bug is related to the new function of the gw version 2.1.0: "Untitled documents are now autosaved to a draft folder when autosave is enabled."

**Comment by mruiz42** [comment]
I will look into it and see what I can do.

**Comment by tildagail** [comment]
@mruiz42 Looking at your PR, it seems that checking the file using `document->isEmpty()` inside the `createDraft()` function will prevent an empty file being saved accidentally, but earlier in the code when `createDraft` can be called (lines 231-235 and 282-286, the same empty file passes a check of `document->characterCount() > 0`.

So the bug might actually be that checking for a character count of more than 0 doesn't eliminate empty files, which seems... weird. Looking at the qt docs, though, it seems that a qtextdocument always has at least one character ([link](https://doc.qt.io/qt-5/qtextdocument.html#characterCount)) so `characterCount()` will always return a result of at least 1. If the `isEmpty()` check works later on in the code, would it prevent the unwanted `createDraft()` function calls to change lines 234 and 285 from `(d->document->characterCount() > 0)` to  `(!d->document->isEmpty())`?

**Comment by mruiz42** [comment]
@tildagail Thanks for that! I tried what you said and it appears that changing the `characterCount() > 0` check to `> 1` changes the behavior of the program and seems to stop this bug. You were right, QTextDocument has a size of 1 during this check when the file should be empty. 

This check is implemented twice. There is a watch function in the constructor (line 236) and again in `DocumentManager::setAutoSaveEnabled`. I would propose changing this to check either `isEmpty()` or `characterCount() > 1`. I think that a check for `Qt::qtextdocument.isEmpty()` should be used here. I will update my PR because this fix seems to better address this issue.

After doing some testing, it looks like the behavior is fixed so that only a new document will create it's own `untitled-xx.md` file and the program will not create any new drafts until the user creates a new document.

**Comment by not-AMM** [comment]
Hey! I think this problem is still present, but not in the same way. I've pressed keys by accident and GhostWriter automatically saves the file `Untitled-[number].md`. As I said, it doesn't save the file at startup, but it does if you press any character key (Enter, Space and so also create a new file).

**Comment by mruiz42** [comment]
@not-AMM This may be working as the feature was originally intended. From what I recall, when you start writing in a document it will auto save a 'draft' so that you don't lose your work. I do think this feature can be improved somewhat by:

1. Possibly changing the name of the `untitled-xx.md` file to `draft-xx.md` or `ghostwriter-draft-xx.md` to prevent confusion.
2. An option that will 'delete' the draft file once it has been appropriately named. (eg. rename and move the draft file when the user decides to save it instead of keeping 2 copies of the same draft.)
Not sure if it's worth implementing though, since feature requests are not currently being considered by wereturtle.

You can disable this feature in settings by unchecking 'Auto save', I believe.

**Comment by not-AMM** [comment]
@mruiz42 I understand. I agree with you, my main problem is that there are a ton of `Untitled(x).md` for everytime I click any key by accident. I just wanted to clarify and, as you say, improve it a little. 

In any case, thanks for reading and working on GhostWriter!
