### ISSUE TITLE
Ghostwriter memory use hugely increases during long sessions

### ISSUE THREAD

**Issue by tildagail** [wereturtle/ghostwriter#708]
Operating system: Xubuntu 20.04
Desktop environment: XFCE 4.14

Description of the problem:

After working on the same file for a long session (I kept the same file open for about 5 hours) my computer became extremely sluggish. Ghostwriter crashed (I think) and everything else returned to its normal speed.

I'm not positive Ghostwriter crashed, because I tried to save and close the program, so those things may have happened on a delay. I lost one sentence off the end of the file, though, which makes me suspect a crash rather than a normal close.

Subsequent checking of everything I'd had open at the time showed that Ghostwriter's memory usage would increase steadily as I typed. With Ghostwriter and xfce's task manager open side by side, in a session of 1 hour 37 minutes (and 859 words added) I observed Ghostwriter's memory use rise from an initial 170 MB to over 4 GB. 

Steps to reproduce the problem:

1. Open any .md file in Ghostwriter
2. Type or otherwise interact with the file text for a period of time. The memory usage increases with each alteration to the file (typing, deleting, cut/copy/paste, undo/redo all have the same memory-increasing effect)

Expected behaviour:

Memory use remains approximately steady, with only minor fluctuations for file size and activity. 

Versions tested:

2.1.0 (PPA and build from source) and 2.0.2 (build from source)

**Comment by wereturtle** [comment]
Sorry, I'm not able to replicate this on Fedora.  I will leave the issue open in case someone else can both replicate it and figure out what the difference is.

**Comment by mruiz42** [comment]
DE: Gnome 41
Distro: Arch Linux
System: Intel 8650U + 32GB RAM
Test time: ~10 minutes
Ghostwriter Version: 2.1.1

Steps taken to reproduce:

- Launch ghostwriter application (which initially has ~231M & 2.5% CPU and 4 associated QtWebEngineProcess at 66, 58, 59, 13MB respectively.)
- Copy and paste large amount of text into document (added 48,000 words and memory is now at 361MB) cpu idle at 2.5%
- Delete the 48000 words using ctrl+a and delete results in 100% cpu for some time until deletion is successful. 
- Now memory jumps to 3GB! cpu idle at 1.7%
- Repeat previous steps to see if memory will go higher
- Memory jumps to 5GB and cpu idle at 1.7%
Curious, I will try to see what memory implications there are when opening a large ~50k word markdown file.
- Relaunch ghostwriter 2.1.1
- Resources initially start at ~250MB and 2.5% CPU
- Undo/redo do not function as they did before since change list is not preserved and I suspect this may be the culprit
- Deleting a large body of text will use a lot of resources (50k words deleted causes the ~250MB jump to ~3GB )

Now that I think about it, of course its being saved in memory, isn't this by design?? If you delete text, the changes are preserved so that you can go forward and backwards (ctrl + z & shift + ctrl + z) in the change list? Although, it is a large amount of memory being used for text. 

Issue confirmed on my end. I would assume memory is not being released when text is being deleted? This may be related to a QText Object and how Qt manages memory ??

I would say this is worth looking into since there may be some optimizations possible to reduce system footprint when dealing with large bodies of text. @wereturtle any ideas?

**Comment by branflakes2** [comment]
I'm experiencing this as well on arch.

Valgrind complains a lot about QtWebengine and re2 - didn't dig too beep but started taking a look at issues in their respective projects. I wasn't able to find any open or closed leak issues in re2, but found this: https://bugreports.qt.io/browse/QTBUG-99534 - Unsure if it's related.

I'm using the latest qt5 webengine (5.15.8-1)

**Comment by wereturtle** [comment]
Thanks for the detailed steps.  I can now confirm the bug.  I'm going to guess this is new Qt bug (though I could be wrong).  I don't see any memory jumps in QtWebEngine processes when this occurs.  I switched to the Pandoc processor to see if that spawned (in case the issue is in rendering the Markdown), but it was not spawned yet once the memory started leaking.

If you can narrow down which Qt module is the culprit, you can report the issue to the Qt devs.  I'll keep looking at my end in the meantime.

**Comment by wereturtle** [comment]
I take it back.  It appears that the issue is the notifications being singaled whenever a text block is removed.  This in turn triggers reparsing of the Markdown document with cmark-gfm.  For each time a block is removed.  However, just removing the parsing is not enough.  There is still a significant delay when deleting so much text, and that's due to just the signal being issued each time a text block gets removed.  If I remove this signal from the destructor in textblockdata.h, the issue goes away entirely.

Well, back to the drawing board for that logic.  Ugh.

**Comment by mruiz42** [comment]
@wereturtle What step were you on in fixing this issue? I can try testing the latest commit or if you point me towards something I can try to see if I can figure something out.
