### ISSUE TITLE
Broken keyboard shortcuts

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#71]
Dear @wereturtle,

Thank you so much for your work on ghostwriter! 

It is by far the best Markdown experience that I had on Linux so far. :-)

I noticed, however, that keyboard shortcuts don't work on Ubuntu 15.10.

Do you have any advice for me?

Thankfully,

~Robert

**Comment by wereturtle** [comment]
I take it you are using the Unity interface?  There's an updated note about that in the README.md file on the main Github page for this repository.  None of the Qt 5 applications have their shortcuts from their menus working in Unity at the moment.  Here is the note I put in the README file for the two workarounds:

**Note to Unity Users:** If you are running Ubuntu with the Unity desktop environment, you should be aware of a bug with how Qt 5 application menus are displayed in the global menu.  Please see [this bug in Launchpad](https://bugs.launchpad.net/appmenu-qt5/+bug/1380702).  At the moment, the shortcuts (such as Ctrl+C, Ctrl+V, etc.) in *ghostwriter's* menus are not available within Unity.  This is true of other Qt 5 applications.  A common workaround is to remove the appmenu-qt5 package.  To do so, open a terminal window, and type the following:

    sudo apt-get remove appmenu-qt5

This will fix the issue for all your Qt 5 applications, including *ghostwriter*.  However, it also places the menus for the application into the application's window, rather than into the global menu.

An alternative workaround is to compile ghostwriter for yourself using Qt 4.8.  Shortcuts should properly work in the global menu for Qt 4.8 applications.  Regardless of your preferred workaround, this appmenu-qt5 bug should be fixed in the near future.  You can use the Launchpad link above to monitor the status of this bug.

**Comment by orschiro** [comment]
Thank you very much for your response!

  

I have overlooked this point in the readme and will follow the bug report you
linked to.

  

Warmly,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 3 2016, at 6:26 pm, wereturtle &lt;notifications@github.com&gt; wrote:  

> Closed [#71](https://github.com/wereturtle/ghostwriter/issues/71).

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/weretur
tle/ghostwriter/issues/71#event-612764368)![](https://github.com/notifications
/beacon/AAKbw0qxiwgPxeLpW9-QYwS_KH9EanIuks5pz-o3gaJpZM4H-gkN.gif)
