### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by sdcote** [wereturtle/ghostwriter#722]
**Platform (please complete the following information):**
 - Windows 10

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [2.1.1]
 - If Windows, installation type [portable]:

**Describe the bug**
Multiple instances of the application are opened if the same document is opened multiple times. This can be confusing and lead to data loss. Additionally, it is not clear if resource usage is increased by opening multiple instances of the sam document.

**To Reproduce**
1. Associate .md files with the Ghostwriter application.
2. Double-Click on a document to edit.
3. Double-Click on a document to edit again.

**Expected behavior**
When Ghostwriter loads with a filename as would be the case with associated filetypes, it first checks if any other instances of Ghostwriter are running with that same file. If so, context is switched to that instance, If not, a new instance is created.

**Screenshots**
![ghostwriter-multiple_instances](https://user-images.githubusercontent.com/564533/148574926-0aa60e5d-6294-48cf-89c0-78a3b34ce367.png)

**Additional context**
While a workaround of notifying the user that the file was changed by another instance does exist, it is possible that the user often may not know which version is correct. If a document is opened many times, the user could be confused about which updates to accept and could potentially lose data/information.

While this may not seem a likely scenario for most people, developers and operators who use markdown can have many documents open at one time and scrolling through the list to find the document they need is tedious and error-prone.

Note that this could be addressed with a Multi-Document Interface (MDI) with different documents opened in the same instance and allowing the user to select the appropriate "tab" for editing.

**Comment by will-ca** [comment]
I personally disagree. It is my responsibility as a user to be aware of what documents I have open, and it is a feature to be able to have multiple instances of the same application or document open (E.G. to have the original contents side-by-side for a rewrite).

I find it very annoying when software tries to be "helpful", as opposed to being *useful*, by automatically assuming that the user must have made an error and overriding explicitly user-requested actions with arbitrary fallbacks. The notification would be fine. But if I tell my computer to open a new instance of an application, *it should open a new instance of that application*.

**Comment by sdcote** [comment]
It depends on the use case. For deliberate authoring activities, I completely agree with you. The user tends to be focused on the activity and the final product. They will have a deliberate workflow in mind. The product should respect the users' scenarios.

Markdown is fast becoming the go-to format for development and operations professionals. Operations and support activities involve opening and editing a great many documents (and applications) at once. Tabbing through dozens of open applications to find the one of particular interest can be difficult and time-consuming. Tabbing through all the open markdown documents to find the one of current interest slows the user down. The once free competitor Typora was good in this role. Other applications support this mode of operations with tabbed interfaces to help the user target and find the needed document.

Ghostwriter already automatically saves your document as you work which is a fantastic feature for those who edit hundreds of documents a day. In hectic environments, it can save your bacon. Now if you combine that with the ability to simply click on a document knowing the latest version will be staring at you...Ghostwriter could save huge amounts of time.

Products should support the principle of least surprise. It should simultaneously support multiple workflows and use cases. In our case, we were surprised that we could have multiple versions of the same document open at once. Other editors will warn the user of opening the same document multiple times and give them the option of reloading the document (losing changes), loading the document in a separate editor, or switching to the document already open. Some will even allow side-by-side comparisons for a rewrite scenario like you mentioned.

While this may sound like a feature request, we entered it as an issue as it has already caused data loss. Due to the past corruption of documents, Ghostwriter is not recommended for use in our environments. If this issue is addressed, we can reconsider our use of Ghostwriter.

In the end, the application should be configurable to support _only_ the features the user wants while supporting the _widest variety_ of use cases possible. That is one of the challenges of product management.

**Comment by will-ca** [comment]
@sdcote Is the workflow you describe within scope for Ghostwriter? "Dozens of open applications" and tabbed editing certainly don't sound compatible with the aims of an "aesthetic, **distraction-free** Markdown editor".

When you have dozens of files open, you should really be using an application that lets you jump to the required document by filename instead of having to tab through applications, or even click from a file manager. Jetbrains IDEs, VS/VS Code, Komodo, GH Atom, and basically every IDE in existence all have robust Markdown support, often also with live preview. They also have systems to avoid accidental data loss like you describe. I left auto-save on in Android Studio because it suits the workflow, but I'd find it endless frustrating and more than a little bit limiting (likely increasing the risk of data loss) if it were compulsory to use in all applications.

> Products should support the principle of least surprise.

Yes. And that means a new window should probably be opened when the user asks for it, as is predictable and consistent, rather than the application trying to guess what the user intends.

> It should simultaneously support multiple workflows and use cases.

Seems foolhardy IMO. Also somewhat contradictory to the [established and proven norms](https://en.wikipedia.org/wiki/Unix_philosophy) at the core of nearly all modern computer technologies.

Ghostwriter seems to bill itself as a simple tool to use. It is rather good at that.

Other tools already exist for the use cases you describe. If Ghostwriter tries to become those tools, it will lose the value it has in the niche it currently occupies, while also failing to provide any major advantage over those tools in their niches. Ghostwriter will likely never be VS Code. It doesn't have to be.

> In the end, the application should be configurable to support only the features the user wants while supporting the widest variety of use cases possible.

Sounds a bit like feature creep and maintenance hell.

You can have more than one application. Why try to force all the functionality into one place? You wouldn't argue that a hammer should support "the widest variety of use cases possible" by being abused as a screwdriver.

---

I do think a "File has changed. Reload?" notification, "File is already open. Open in read-only?" warning, or "Automatically reload changes?" checkbox would be a welcome addition.

But seriously, why not just use VS Code with a Markdown extension? You are literally describing VS Code.

**Comment by sdcote** [comment]
Fair enough. We just won't use Ghostwriter.

**Comment by sdcote** [comment]
I think this has been completely misinterpreted as some form of slight against Ghostwriter. It is not. It is simply a bug report that was met with a passionate response. 

In evaluating the use of markdown editors to take notes, we noticed one of the tools being evaluated behaved differently from the rest. We opened an issue because we honestly felt this was an oversight and your team would want to know about it. 

We got our answer and accepted it. Your software is not designed to be used as we intend. Issue closed.

It is clear that this struck a nerve with your team and for this, I apologize. Please don't think this is anything but our trying to help you make your product better through user feedback. As a developer, I know how valuable such feedback can be.

Your team has the final say as to what gets implemented; no one is forcing you to do anything, especially without compensation. We took the advice given and used a different tool.
