### ISSUE TITLE
Disable cursor blinking (v2.1.1)

### ISSUE THREAD

**Issue by mfakih294** [wereturtle/ghostwriter#726]
Admittedly, for some people, having a blinking cursor is a distraction while writing. However, I haven't a way to disable it, even when the Linux keyboard setting disabled it (it doesn't blink in other applications). I tried this workaround and it didn't work either: https://github.com/igogo/qt5noblink.

**Comment by wereturtle** [comment]
Unfortunately I've had to hand-draw the cursor since newer versions of Qt sometimes draw an invisible cursor or strangely colored one depending on the background color of the theme.  Someday I'll return to having Qt draw the cursor when I can find a workaround to this bug.  In the meantime, most people seem to want a blinking cursor.
