### ISSUE TITLE
Ghostwriter not opening?!

### ISSUE THREAD

**Issue by athrvvvv** [wereturtle/ghostwriter#765]
**Screenshot**
<br>
![May-06-2022 09-16-12 AM](https://user-images.githubusercontent.com/98272709/167066348-49d4a198-aafd-4d1b-8e55-748d2eb85428.png)
<br>
**Iam using the latest version of ghostwriter., I tried opening it as administrator but it sucks (Not opening):-**
Additional info :-
Windows OS 10
4GB ram

**Comment by wereturtle** [comment]
There are multiple reasons why Windows won't open an EXE file.  Google is your friend here.  Remember that this is an unsigned EXE, so Windows might be trying to protect/nanny you.  Did you check the Properties -> Security tab permissions for your user? (Right click on the executable to get to the properties.)

**Comment by wereturtle** [comment]
Also, see if you see the setting to "unblock" the executable.  Right click on `ghostwriter.exe` and make sure the Unblock checkbox is checked, like so:

![image](https://user-images.githubusercontent.com/10375170/171321305-f44ac576-e3ad-4ef6-9a1c-f19fb28b49bd.png)

**Comment by kevin-wijnen** [comment]
Worth to mention that F-Secure does see the Windows Portable 2.1.3 release as a "Trojan:W32/CryptoRansomwareBehaviour.B!DeepGuard" program (F-Secure's DeepGuard protection detects the install as a crypto ransomware program). Any clarification on this? F-Secure let me use it initially before it got shutdown due to the detection, and refuses to let the computer open it (unless I make an exception for the program). 
![afbeelding](https://user-images.githubusercontent.com/58944808/172071084-b4334a59-6360-4d19-aa6d-83d482bc775b.png)


This does not seem to be a "generic false alarm" notification as I've gotten used to by F-Secure (those tend to be of the "Suspicious:W32 ..." classification). VirusTotal however does not see anything wrong with the release ([ZIP file](https://www.virustotal.com/gui/file/b9f2ce448eb9b9e2ed3ab4d7ddb736ce34e64f13e59df1fdda117c9837c1dafc), [standalone executable](https://www.virustotal.com/gui/file/23a9e316d9a629d4f0a40e87c500217bb3d0754d89a9168e03fb2019a5e6e235)).

**Comment by wereturtle** [comment]
@kevin-wijnen The latest Windows executable was built with AppVeyor and uploaded from there.  I have scanned it with clamav and Window's own built-in AV.  No alarms were tripped.  If you think F-Secure's alarm is legitimate, please contact the AppVeyor devs at appveyor.com and let them know their servers might be infected.  Personally, I'm leaning towards false alarm.  I definitely didn't slip any "crypto ransomware" into the source code.

**Comment by wereturtle** [comment]
Closing this issue as there was no reply from the author after two weeks.
