### ISSUE TITLE
themes not function

### ISSUE THREAD

**Issue by ajeep8** [wereturtle/ghostwriter#797]
I'm using ghostwriter 2.1.4 on ubuntu 20.04，and 

```
git clone https://github.com/jggouvea/ghostwriter-themes
```

mv themes to ~/.config/ghostwriter/themes, re-open ghostwriter， but no new themes in Settings-Themes.

**Comment by ajeep8** [comment]
I find out version 1.8.0 has custom themes and custom css, that's what I need.

Why v2 remove these 2 functions?

**Comment by wereturtle** [comment]
Version 2 does have custom themes.  However, they are not backwards-compatible with version 1.8.0.  This is because I switched to using JSON instead of .ini files.  You can easily make a theme by going to Settings -> Themes under the menu bar.

As far as the custom CSS goes, I thought it would be better for the CSS to match the theme for the best overall distraction-free writing experience.  iAWriter and Byword do much the same on MacOS.  After all, the point of the preview is to make sure the Markdown is valid and will display correctly, not to preview an entire website.
