### ISSUE TITLE
Support official Ubuntu package

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#82]
Dear all, 

I thought it was a good thing for Ghostwriter to be present in the official Ubuntu repositories. 

If you think so as well, then you can leave your vote here: 

https://bugs.launchpad.net/ubuntu/+bug/1576068

Warmly,

~Robert

**Comment by wereturtle** [comment]
It is more ideal to get it into Debian, so that it eventually gets into Ubuntu in addition to other Debian-based distros.  For that, we need a sponsor from Debian to mentor the person doing the packaging and perform the upload.  I obviously already have a .deb package ready for the PPA.  Just tweak it for Debian and double check that it's following the Debian packaging guidelines.

The hard part is getting the sponsor.  There's a whole process for that, and no guarantee that a Debian developer will want to sponsor, but we can hope.  I'm trying to get release 1.4 out the door, get bug reports, and fix the bugs.  That will be the golden version that I want to go into Debian.

If anyone wants to make friends with a Debian sponsor, that would be very fantastic and would save me a lot of time.  I don't really have the bandwidth to do all the packaging for every Linux distro out there, so it would be a boon if people who are involved with their favorite Linux distro can maintain the ghostwriter package for that distro.

Also, a Snappy package for Ubuntu 16.04 would be great.

**Comment by orschiro** [comment]
> It is more ideal to get it into Debian, so that it eventually gets into Ubuntu in addition to other Debian-based distros.

Is the reverse possible, too? Thus having a package from Ubuntu first into Debian second?

~Robert

**Comment by wereturtle** [comment]
Yes, it is possible.  However, I wouldn't count on the Ubuntu developers having the time to look at the package submission.  The impression I have is that they don't even have time to look at the non-free commercial applications that are submitted to them for the store (due largely to being in a transition state between the new Snappy way and ye olde Software Centre way of doing things).  I'd be surprised if they'd have the staff to get around to evaluating a free app.  Besides, it is in their own packaging guide that they prefer you try Debian first.  Once it's in Debian, you can request the Ubuntu devs to backport it into Ubuntu so that users don't have to wait for them to harvest the latest software from Debian Sid into the next Ubuntu release.

**Comment by orschiro** [comment]
That's reasonable. Thanks for the explanation!

~Robert
