### ISSUE TITLE
Any way to tweak export parameters?

### ISSUE THREAD

**Issue by nonplayer** [wereturtle/ghostwriter#92]
I swear to god this application is almost perfect! I just can't figure out how to tweak the PDF export through pandoc on windows so the margins aren't so enormous. Any chance of a options button to customize export params?

**Comment by wereturtle** [comment]
Well, I try to keep the export options simple so that I don't have to keep up with new versions of Pandoc, MultiMarkdown, etc. so much, as options can be added or, worse, removed/modified (and thereby break functionality).  However, now that you mention it, the default PDF margins are awfully huge.  How do one-inch margins sound?  It looks like I can add margin options to Pandoc as command line parameters.

**Comment by nonplayer** [comment]
1-inch margins are acceptable. I've taken a round-about approach by first exporting to Docx, then exporting to PDF from MS Word, which gives a bit more control over output. But a margin selector would be a nice touch for the PDF export. Thanks!
