### ISSUE TITLE
View Preview/Outline/Cheatsheet as Toggles

### ISSUE THREAD

**Issue by nonplayer** [wereturtle/ghostwriter#93]
The shortcuts to turn on the Preview, Outline panel, and Cheat Sheet are nice, but the only way to close them is by then X-ing out. Would be nice to be able to use the same shortcuts to dismiss them, so Ctrl-L would enable the Outline, then hitting Ctrl-L would close it again.

**Comment by wereturtle** [comment]
Need to also have currently focused HUD close with the press of the Escape key.

**Comment by wereturtle** [comment]
FYI, I decided against `Ctrl+L` toggling the Outline HUD visibility, simply because if it's already displayed, then the user might just want to have the focus shift to it away from the editor rather than have it close.  However, if you want to close it via shortcut key, I made it so that  once any HUD has focus, the `Esc` key can be pressed to close.

As for the HTML Preview, you can already close that via shortcut key with `Alt+F4`.
